// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: protos/hand_wrench_srv.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Protos {

  /// <summary>Holder for reflection information generated from protos/hand_wrench_srv.proto</summary>
  public static partial class HandWrenchSrvReflection {

    #region Descriptor
    /// <summary>File descriptor for protos/hand_wrench_srv.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static HandWrenchSrvReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Chxwcm90b3MvaGFuZF93cmVuY2hfc3J2LnByb3RvEgZwcm90b3MigAEKDUl0",
            "ZW1NYXNzRm9yY2USEQoJY2FzZV9uYW1lGAEgASgJEhMKC2Rlc2NyaXB0aW9u",
            "GAIgASgJEhEKCWl0ZW1fbWFzcxgDIAEoARIQCghsZm9yY2VfeBgEIAEoARIQ",
            "CghsZm9yY2VfeRgFIAEoARIQCghsZm9yY2VfehgGIAEoASJ8ChRJdGVtTWFz",
            "c0ZvcmNlUmVxdWVzdBIxCglvcGVyYXRpb24YASABKA4yHi5wcm90b3MuSXRl",
            "bU1hc3NGb3JjZU9wZXJhdGlvbhIoCgRkYXRhGAIgASgLMhUucHJvdG9zLkl0",
            "ZW1NYXNzRm9yY2VIAIgBAUIHCgVfZGF0YSKcAgoVSXRlbU1hc3NGb3JjZVJl",
            "c3BvbnNlEjEKCW9wZXJhdGlvbhgBIAEoDjIeLnByb3Rvcy5JdGVtTWFzc0Zv",
            "cmNlT3BlcmF0aW9uEj0KBnN0YXR1cxgCIAEoDjItLnByb3Rvcy5JdGVtTWFz",
            "c0ZvcmNlUmVzcG9uc2UuT3BlcmF0aW9uU3RhdHVzEhMKC2Rlc2NyaXB0aW9u",
            "GAMgASgJEi8KEGl0ZW1fbWFzc19mb3JjZXMYBCADKAsyFS5wcm90b3MuSXRl",
            "bU1hc3NGb3JjZSJLCg9PcGVyYXRpb25TdGF0dXMSCwoHU1VDQ0VTUxAAEgkK",
            "BUVSUk9SEAESCwoHVElNRU9VVBACEhMKD0lOVkFMSURfUkVRVUVTVBADKioK",
            "Fkl0ZW1NYXNzRm9yY2VPcGVyYXRpb24SBwoDR0VUEAASBwoDU0VUEAFiBnBy",
            "b3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Protos.ItemMassForceOperation), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Protos.ItemMassForce), global::Protos.ItemMassForce.Parser, new[]{ "CaseName", "Description", "ItemMass", "LforceX", "LforceY", "LforceZ" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Protos.ItemMassForceRequest), global::Protos.ItemMassForceRequest.Parser, new[]{ "Operation", "Data" }, new[]{ "Data" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Protos.ItemMassForceResponse), global::Protos.ItemMassForceResponse.Parser, new[]{ "Operation", "Status", "Description", "ItemMassForces" }, null, new[]{ typeof(global::Protos.ItemMassForceResponse.Types.OperationStatus) }, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum ItemMassForceOperation {
    /// <summary>
    /// Get: 获取物品质量与力
    /// </summary>
    [pbr::OriginalName("GET")] Get = 0,
    /// <summary>
    /// Set: 设置物品质量与力
    /// </summary>
    [pbr::OriginalName("SET")] Set = 1,
  }

  #endregion

  #region Messages
  public sealed partial class ItemMassForce : pb::IMessage<ItemMassForce>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ItemMassForce> _parser = new pb::MessageParser<ItemMassForce>(() => new ItemMassForce());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ItemMassForce> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Protos.HandWrenchSrvReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ItemMassForce() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ItemMassForce(ItemMassForce other) : this() {
      caseName_ = other.caseName_;
      description_ = other.description_;
      itemMass_ = other.itemMass_;
      lforceX_ = other.lforceX_;
      lforceY_ = other.lforceY_;
      lforceZ_ = other.lforceZ_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ItemMassForce Clone() {
      return new ItemMassForce(this);
    }

    /// <summary>Field number for the "case_name" field.</summary>
    public const int CaseNameFieldNumber = 1;
    private string caseName_ = "";
    /// <summary>
    /// 配置名称
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string CaseName {
      get { return caseName_; }
      set {
        caseName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "description" field.</summary>
    public const int DescriptionFieldNumber = 2;
    private string description_ = "";
    /// <summary>
    /// 配置描述
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Description {
      get { return description_; }
      set {
        description_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "item_mass" field.</summary>
    public const int ItemMassFieldNumber = 3;
    private double itemMass_;
    /// <summary>
    /// kg
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double ItemMass {
      get { return itemMass_; }
      set {
        itemMass_ = value;
      }
    }

    /// <summary>Field number for the "lforce_x" field.</summary>
    public const int LforceXFieldNumber = 4;
    private double lforceX_;
    /// <summary>
    /// N
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double LforceX {
      get { return lforceX_; }
      set {
        lforceX_ = value;
      }
    }

    /// <summary>Field number for the "lforce_y" field.</summary>
    public const int LforceYFieldNumber = 5;
    private double lforceY_;
    /// <summary>
    /// N
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double LforceY {
      get { return lforceY_; }
      set {
        lforceY_ = value;
      }
    }

    /// <summary>Field number for the "lforce_z" field.</summary>
    public const int LforceZFieldNumber = 6;
    private double lforceZ_;
    /// <summary>
    /// N
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double LforceZ {
      get { return lforceZ_; }
      set {
        lforceZ_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ItemMassForce);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ItemMassForce other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (CaseName != other.CaseName) return false;
      if (Description != other.Description) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(ItemMass, other.ItemMass)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(LforceX, other.LforceX)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(LforceY, other.LforceY)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(LforceZ, other.LforceZ)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (CaseName.Length != 0) hash ^= CaseName.GetHashCode();
      if (Description.Length != 0) hash ^= Description.GetHashCode();
      if (ItemMass != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(ItemMass);
      if (LforceX != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(LforceX);
      if (LforceY != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(LforceY);
      if (LforceZ != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(LforceZ);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (CaseName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(CaseName);
      }
      if (Description.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Description);
      }
      if (ItemMass != 0D) {
        output.WriteRawTag(25);
        output.WriteDouble(ItemMass);
      }
      if (LforceX != 0D) {
        output.WriteRawTag(33);
        output.WriteDouble(LforceX);
      }
      if (LforceY != 0D) {
        output.WriteRawTag(41);
        output.WriteDouble(LforceY);
      }
      if (LforceZ != 0D) {
        output.WriteRawTag(49);
        output.WriteDouble(LforceZ);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (CaseName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(CaseName);
      }
      if (Description.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Description);
      }
      if (ItemMass != 0D) {
        output.WriteRawTag(25);
        output.WriteDouble(ItemMass);
      }
      if (LforceX != 0D) {
        output.WriteRawTag(33);
        output.WriteDouble(LforceX);
      }
      if (LforceY != 0D) {
        output.WriteRawTag(41);
        output.WriteDouble(LforceY);
      }
      if (LforceZ != 0D) {
        output.WriteRawTag(49);
        output.WriteDouble(LforceZ);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (CaseName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CaseName);
      }
      if (Description.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Description);
      }
      if (ItemMass != 0D) {
        size += 1 + 8;
      }
      if (LforceX != 0D) {
        size += 1 + 8;
      }
      if (LforceY != 0D) {
        size += 1 + 8;
      }
      if (LforceZ != 0D) {
        size += 1 + 8;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ItemMassForce other) {
      if (other == null) {
        return;
      }
      if (other.CaseName.Length != 0) {
        CaseName = other.CaseName;
      }
      if (other.Description.Length != 0) {
        Description = other.Description;
      }
      if (other.ItemMass != 0D) {
        ItemMass = other.ItemMass;
      }
      if (other.LforceX != 0D) {
        LforceX = other.LforceX;
      }
      if (other.LforceY != 0D) {
        LforceY = other.LforceY;
      }
      if (other.LforceZ != 0D) {
        LforceZ = other.LforceZ;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            CaseName = input.ReadString();
            break;
          }
          case 18: {
            Description = input.ReadString();
            break;
          }
          case 25: {
            ItemMass = input.ReadDouble();
            break;
          }
          case 33: {
            LforceX = input.ReadDouble();
            break;
          }
          case 41: {
            LforceY = input.ReadDouble();
            break;
          }
          case 49: {
            LforceZ = input.ReadDouble();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            CaseName = input.ReadString();
            break;
          }
          case 18: {
            Description = input.ReadString();
            break;
          }
          case 25: {
            ItemMass = input.ReadDouble();
            break;
          }
          case 33: {
            LforceX = input.ReadDouble();
            break;
          }
          case 41: {
            LforceY = input.ReadDouble();
            break;
          }
          case 49: {
            LforceZ = input.ReadDouble();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// 物品质量与力请求
  /// </summary>
  public sealed partial class ItemMassForceRequest : pb::IMessage<ItemMassForceRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ItemMassForceRequest> _parser = new pb::MessageParser<ItemMassForceRequest>(() => new ItemMassForceRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ItemMassForceRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Protos.HandWrenchSrvReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ItemMassForceRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ItemMassForceRequest(ItemMassForceRequest other) : this() {
      operation_ = other.operation_;
      data_ = other.data_ != null ? other.data_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ItemMassForceRequest Clone() {
      return new ItemMassForceRequest(this);
    }

    /// <summary>Field number for the "operation" field.</summary>
    public const int OperationFieldNumber = 1;
    private global::Protos.ItemMassForceOperation operation_ = global::Protos.ItemMassForceOperation.Get;
    /// <summary>
    /// 操作类型: 获取或设置
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Protos.ItemMassForceOperation Operation {
      get { return operation_; }
      set {
        operation_ = value;
      }
    }

    /// <summary>Field number for the "data" field.</summary>
    public const int DataFieldNumber = 2;
    private global::Protos.ItemMassForce data_;
    /// <summary>
    /// 物品质量与力，当操作类型为`Set`时才会设置
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Protos.ItemMassForce Data {
      get { return data_; }
      set {
        data_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ItemMassForceRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ItemMassForceRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Operation != other.Operation) return false;
      if (!object.Equals(Data, other.Data)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Operation != global::Protos.ItemMassForceOperation.Get) hash ^= Operation.GetHashCode();
      if (data_ != null) hash ^= Data.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Operation != global::Protos.ItemMassForceOperation.Get) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Operation);
      }
      if (data_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Data);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Operation != global::Protos.ItemMassForceOperation.Get) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Operation);
      }
      if (data_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Data);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Operation != global::Protos.ItemMassForceOperation.Get) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Operation);
      }
      if (data_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Data);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ItemMassForceRequest other) {
      if (other == null) {
        return;
      }
      if (other.Operation != global::Protos.ItemMassForceOperation.Get) {
        Operation = other.Operation;
      }
      if (other.data_ != null) {
        if (data_ == null) {
          Data = new global::Protos.ItemMassForce();
        }
        Data.MergeFrom(other.Data);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Operation = (global::Protos.ItemMassForceOperation) input.ReadEnum();
            break;
          }
          case 18: {
            if (data_ == null) {
              Data = new global::Protos.ItemMassForce();
            }
            input.ReadMessage(Data);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Operation = (global::Protos.ItemMassForceOperation) input.ReadEnum();
            break;
          }
          case 18: {
            if (data_ == null) {
              Data = new global::Protos.ItemMassForce();
            }
            input.ReadMessage(Data);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// 物品质量与力响应
  /// </summary>
  public sealed partial class ItemMassForceResponse : pb::IMessage<ItemMassForceResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ItemMassForceResponse> _parser = new pb::MessageParser<ItemMassForceResponse>(() => new ItemMassForceResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ItemMassForceResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Protos.HandWrenchSrvReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ItemMassForceResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ItemMassForceResponse(ItemMassForceResponse other) : this() {
      operation_ = other.operation_;
      status_ = other.status_;
      description_ = other.description_;
      itemMassForces_ = other.itemMassForces_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ItemMassForceResponse Clone() {
      return new ItemMassForceResponse(this);
    }

    /// <summary>Field number for the "operation" field.</summary>
    public const int OperationFieldNumber = 1;
    private global::Protos.ItemMassForceOperation operation_ = global::Protos.ItemMassForceOperation.Get;
    /// <summary>
    /// 操作类型: 获取或设置
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Protos.ItemMassForceOperation Operation {
      get { return operation_; }
      set {
        operation_ = value;
      }
    }

    /// <summary>Field number for the "status" field.</summary>
    public const int StatusFieldNumber = 2;
    private global::Protos.ItemMassForceResponse.Types.OperationStatus status_ = global::Protos.ItemMassForceResponse.Types.OperationStatus.Success;
    /// <summary>
    /// 操作状态: 成功、错误、超时、无效请求
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Protos.ItemMassForceResponse.Types.OperationStatus Status {
      get { return status_; }
      set {
        status_ = value;
      }
    }

    /// <summary>Field number for the "description" field.</summary>
    public const int DescriptionFieldNumber = 3;
    private string description_ = "";
    /// <summary>
    /// 操作描述: 成功、错误、超时、无效请求
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Description {
      get { return description_; }
      set {
        description_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "item_mass_forces" field.</summary>
    public const int ItemMassForcesFieldNumber = 4;
    private static readonly pb::FieldCodec<global::Protos.ItemMassForce> _repeated_itemMassForces_codec
        = pb::FieldCodec.ForMessage(34, global::Protos.ItemMassForce.Parser);
    private readonly pbc::RepeatedField<global::Protos.ItemMassForce> itemMassForces_ = new pbc::RepeatedField<global::Protos.ItemMassForce>();
    /// <summary>
    /// 物品质量与力，当操作类型为`Get`时才会返回
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Protos.ItemMassForce> ItemMassForces {
      get { return itemMassForces_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ItemMassForceResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ItemMassForceResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Operation != other.Operation) return false;
      if (Status != other.Status) return false;
      if (Description != other.Description) return false;
      if(!itemMassForces_.Equals(other.itemMassForces_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Operation != global::Protos.ItemMassForceOperation.Get) hash ^= Operation.GetHashCode();
      if (Status != global::Protos.ItemMassForceResponse.Types.OperationStatus.Success) hash ^= Status.GetHashCode();
      if (Description.Length != 0) hash ^= Description.GetHashCode();
      hash ^= itemMassForces_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Operation != global::Protos.ItemMassForceOperation.Get) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Operation);
      }
      if (Status != global::Protos.ItemMassForceResponse.Types.OperationStatus.Success) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Status);
      }
      if (Description.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Description);
      }
      itemMassForces_.WriteTo(output, _repeated_itemMassForces_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Operation != global::Protos.ItemMassForceOperation.Get) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Operation);
      }
      if (Status != global::Protos.ItemMassForceResponse.Types.OperationStatus.Success) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Status);
      }
      if (Description.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Description);
      }
      itemMassForces_.WriteTo(ref output, _repeated_itemMassForces_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Operation != global::Protos.ItemMassForceOperation.Get) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Operation);
      }
      if (Status != global::Protos.ItemMassForceResponse.Types.OperationStatus.Success) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Status);
      }
      if (Description.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Description);
      }
      size += itemMassForces_.CalculateSize(_repeated_itemMassForces_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ItemMassForceResponse other) {
      if (other == null) {
        return;
      }
      if (other.Operation != global::Protos.ItemMassForceOperation.Get) {
        Operation = other.Operation;
      }
      if (other.Status != global::Protos.ItemMassForceResponse.Types.OperationStatus.Success) {
        Status = other.Status;
      }
      if (other.Description.Length != 0) {
        Description = other.Description;
      }
      itemMassForces_.Add(other.itemMassForces_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Operation = (global::Protos.ItemMassForceOperation) input.ReadEnum();
            break;
          }
          case 16: {
            Status = (global::Protos.ItemMassForceResponse.Types.OperationStatus) input.ReadEnum();
            break;
          }
          case 26: {
            Description = input.ReadString();
            break;
          }
          case 34: {
            itemMassForces_.AddEntriesFrom(input, _repeated_itemMassForces_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Operation = (global::Protos.ItemMassForceOperation) input.ReadEnum();
            break;
          }
          case 16: {
            Status = (global::Protos.ItemMassForceResponse.Types.OperationStatus) input.ReadEnum();
            break;
          }
          case 26: {
            Description = input.ReadString();
            break;
          }
          case 34: {
            itemMassForces_.AddEntriesFrom(ref input, _repeated_itemMassForces_codec);
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the ItemMassForceResponse message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      /// <summary>
      /// 操作状态
      /// </summary>
      public enum OperationStatus {
        [pbr::OriginalName("SUCCESS")] Success = 0,
        [pbr::OriginalName("ERROR")] Error = 1,
        [pbr::OriginalName("TIMEOUT")] Timeout = 2,
        [pbr::OriginalName("INVALID_REQUEST")] InvalidRequest = 3,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
