// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: protos/robot_state.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Protos {

  /// <summary>Holder for reflection information generated from protos/robot_state.proto</summary>
  public static partial class RobotStateReflection {

    #region Descriptor
    /// <summary>File descriptor for protos/robot_state.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static RobotStateReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Chhwcm90b3Mvcm9ib3Rfc3RhdGUucHJvdG8SBnByb3RvcxoccHJvdG9zL2hh",
            "bmRfd3JlbmNoX3Nydi5wcm90byInCgZIZWFkZXISEQoJdGltZXN0YW1wGAEg",
            "ASgDEgoKAmlkGAIgASgDIkYKEEVuZEVmZmVjdG9yU3RhdGUSEAoIcG9zaXRp",
            "b24YASADKAESEAoIdmVsb2NpdHkYAiADKAESDgoGZWZmb3J0GAMgAygBIkAK",
            "CkpvaW50U3RhdGUSEAoIcG9zaXRpb24YASADKAESEAoIdmVsb2NpdHkYAiAD",
            "KAESDgoGdG9ycXVlGAMgAygBIiUKEEFybUZvcmNlRmVlZGJhY2sSEQoJbWF4",
            "X2ZvcmNlGAEgAygBIpQCCgpSb2JvdFN0YXRlEh4KBmhlYWRlchgBIAEoCzIO",
            "LnByb3Rvcy5IZWFkZXISKgoIZWVfc3RhdGUYAiABKAsyGC5wcm90b3MuRW5k",
            "RWZmZWN0b3JTdGF0ZRInCgtqb2ludF9zdGF0ZRgDIAEoCzISLnByb3Rvcy5K",
            "b2ludFN0YXRlEj8KGGl0ZW1fbWFzc19mb3JjZV9yZXNwb25zZRgEIAEoCzId",
            "LnByb3Rvcy5JdGVtTWFzc0ZvcmNlUmVzcG9uc2USOQoSYXJtX2ZvcmNlX2Zl",
            "ZWRiYWNrGAUgASgLMhgucHJvdG9zLkFybUZvcmNlRmVlZGJhY2tIAIgBAUIV",
            "ChNfYXJtX2ZvcmNlX2ZlZWRiYWNrYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Protos.HandWrenchSrvReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Protos.Header), global::Protos.Header.Parser, new[]{ "Timestamp", "Id" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Protos.EndEffectorState), global::Protos.EndEffectorState.Parser, new[]{ "Position", "Velocity", "Effort" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Protos.JointState), global::Protos.JointState.Parser, new[]{ "Position", "Velocity", "Torque" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Protos.ArmForceFeedback), global::Protos.ArmForceFeedback.Parser, new[]{ "MaxForce" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Protos.RobotState), global::Protos.RobotState.Parser, new[]{ "Header", "EeState", "JointState", "ItemMassForceResponse", "ArmForceFeedback" }, new[]{ "ArmForceFeedback" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// 头文件，包含时间戳和消息ID
  /// </summary>
  public sealed partial class Header : pb::IMessage<Header>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Header> _parser = new pb::MessageParser<Header>(() => new Header());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Header> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Protos.RobotStateReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Header() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Header(Header other) : this() {
      timestamp_ = other.timestamp_;
      id_ = other.id_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Header Clone() {
      return new Header(this);
    }

    /// <summary>Field number for the "timestamp" field.</summary>
    public const int TimestampFieldNumber = 1;
    private long timestamp_;
    /// <summary>
    /// 时间戳 (纳秒)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Timestamp {
      get { return timestamp_; }
      set {
        timestamp_ = value;
      }
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 2;
    private long id_;
    /// <summary>
    /// 消息ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Header);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Header other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Timestamp != other.Timestamp) return false;
      if (Id != other.Id) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Timestamp != 0L) hash ^= Timestamp.GetHashCode();
      if (Id != 0L) hash ^= Id.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Timestamp != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Timestamp);
      }
      if (Id != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(Id);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Timestamp != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Timestamp);
      }
      if (Id != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(Id);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Timestamp != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Timestamp);
      }
      if (Id != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Id);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Header other) {
      if (other == null) {
        return;
      }
      if (other.Timestamp != 0L) {
        Timestamp = other.Timestamp;
      }
      if (other.Id != 0L) {
        Id = other.Id;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Timestamp = input.ReadInt64();
            break;
          }
          case 16: {
            Id = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Timestamp = input.ReadInt64();
            break;
          }
          case 16: {
            Id = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class EndEffectorState : pb::IMessage<EndEffectorState>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<EndEffectorState> _parser = new pb::MessageParser<EndEffectorState>(() => new EndEffectorState());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<EndEffectorState> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Protos.RobotStateReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EndEffectorState() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EndEffectorState(EndEffectorState other) : this() {
      position_ = other.position_.Clone();
      velocity_ = other.velocity_.Clone();
      effort_ = other.effort_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EndEffectorState Clone() {
      return new EndEffectorState(this);
    }

    /// <summary>Field number for the "position" field.</summary>
    public const int PositionFieldNumber = 1;
    private static readonly pb::FieldCodec<double> _repeated_position_codec
        = pb::FieldCodec.ForDouble(10);
    private readonly pbc::RepeatedField<double> position_ = new pbc::RepeatedField<double>();
    /// <summary>
    /// none: 0
    /// lejuclaw: 夹爪 ==> X2
    /// qiangnao, revo2, qiangnao_touch: 灵巧手: ==> X12
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<double> Position {
      get { return position_; }
    }

    /// <summary>Field number for the "velocity" field.</summary>
    public const int VelocityFieldNumber = 2;
    private static readonly pb::FieldCodec<double> _repeated_velocity_codec
        = pb::FieldCodec.ForDouble(18);
    private readonly pbc::RepeatedField<double> velocity_ = new pbc::RepeatedField<double>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<double> Velocity {
      get { return velocity_; }
    }

    /// <summary>Field number for the "effort" field.</summary>
    public const int EffortFieldNumber = 3;
    private static readonly pb::FieldCodec<double> _repeated_effort_codec
        = pb::FieldCodec.ForDouble(26);
    private readonly pbc::RepeatedField<double> effort_ = new pbc::RepeatedField<double>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<double> Effort {
      get { return effort_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as EndEffectorState);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(EndEffectorState other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!position_.Equals(other.position_)) return false;
      if(!velocity_.Equals(other.velocity_)) return false;
      if(!effort_.Equals(other.effort_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= position_.GetHashCode();
      hash ^= velocity_.GetHashCode();
      hash ^= effort_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      position_.WriteTo(output, _repeated_position_codec);
      velocity_.WriteTo(output, _repeated_velocity_codec);
      effort_.WriteTo(output, _repeated_effort_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      position_.WriteTo(ref output, _repeated_position_codec);
      velocity_.WriteTo(ref output, _repeated_velocity_codec);
      effort_.WriteTo(ref output, _repeated_effort_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += position_.CalculateSize(_repeated_position_codec);
      size += velocity_.CalculateSize(_repeated_velocity_codec);
      size += effort_.CalculateSize(_repeated_effort_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(EndEffectorState other) {
      if (other == null) {
        return;
      }
      position_.Add(other.position_);
      velocity_.Add(other.velocity_);
      effort_.Add(other.effort_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10:
          case 9: {
            position_.AddEntriesFrom(input, _repeated_position_codec);
            break;
          }
          case 18:
          case 17: {
            velocity_.AddEntriesFrom(input, _repeated_velocity_codec);
            break;
          }
          case 26:
          case 25: {
            effort_.AddEntriesFrom(input, _repeated_effort_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10:
          case 9: {
            position_.AddEntriesFrom(ref input, _repeated_position_codec);
            break;
          }
          case 18:
          case 17: {
            velocity_.AddEntriesFrom(ref input, _repeated_velocity_codec);
            break;
          }
          case 26:
          case 25: {
            effort_.AddEntriesFrom(ref input, _repeated_effort_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class JointState : pb::IMessage<JointState>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<JointState> _parser = new pb::MessageParser<JointState>(() => new JointState());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<JointState> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Protos.RobotStateReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public JointState() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public JointState(JointState other) : this() {
      position_ = other.position_.Clone();
      velocity_ = other.velocity_.Clone();
      torque_ = other.torque_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public JointState Clone() {
      return new JointState(this);
    }

    /// <summary>Field number for the "position" field.</summary>
    public const int PositionFieldNumber = 1;
    private static readonly pb::FieldCodec<double> _repeated_position_codec
        = pb::FieldCodec.ForDouble(10);
    private readonly pbc::RepeatedField<double> position_ = new pbc::RepeatedField<double>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<double> Position {
      get { return position_; }
    }

    /// <summary>Field number for the "velocity" field.</summary>
    public const int VelocityFieldNumber = 2;
    private static readonly pb::FieldCodec<double> _repeated_velocity_codec
        = pb::FieldCodec.ForDouble(18);
    private readonly pbc::RepeatedField<double> velocity_ = new pbc::RepeatedField<double>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<double> Velocity {
      get { return velocity_; }
    }

    /// <summary>Field number for the "torque" field.</summary>
    public const int TorqueFieldNumber = 3;
    private static readonly pb::FieldCodec<double> _repeated_torque_codec
        = pb::FieldCodec.ForDouble(26);
    private readonly pbc::RepeatedField<double> torque_ = new pbc::RepeatedField<double>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<double> Torque {
      get { return torque_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as JointState);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(JointState other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!position_.Equals(other.position_)) return false;
      if(!velocity_.Equals(other.velocity_)) return false;
      if(!torque_.Equals(other.torque_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= position_.GetHashCode();
      hash ^= velocity_.GetHashCode();
      hash ^= torque_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      position_.WriteTo(output, _repeated_position_codec);
      velocity_.WriteTo(output, _repeated_velocity_codec);
      torque_.WriteTo(output, _repeated_torque_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      position_.WriteTo(ref output, _repeated_position_codec);
      velocity_.WriteTo(ref output, _repeated_velocity_codec);
      torque_.WriteTo(ref output, _repeated_torque_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += position_.CalculateSize(_repeated_position_codec);
      size += velocity_.CalculateSize(_repeated_velocity_codec);
      size += torque_.CalculateSize(_repeated_torque_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(JointState other) {
      if (other == null) {
        return;
      }
      position_.Add(other.position_);
      velocity_.Add(other.velocity_);
      torque_.Add(other.torque_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10:
          case 9: {
            position_.AddEntriesFrom(input, _repeated_position_codec);
            break;
          }
          case 18:
          case 17: {
            velocity_.AddEntriesFrom(input, _repeated_velocity_codec);
            break;
          }
          case 26:
          case 25: {
            torque_.AddEntriesFrom(input, _repeated_torque_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10:
          case 9: {
            position_.AddEntriesFrom(ref input, _repeated_position_codec);
            break;
          }
          case 18:
          case 17: {
            velocity_.AddEntriesFrom(ref input, _repeated_velocity_codec);
            break;
          }
          case 26:
          case 25: {
            torque_.AddEntriesFrom(ref input, _repeated_torque_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// 手臂力反馈（各手臂 xyz 中最大的力）
  /// </summary>
  public sealed partial class ArmForceFeedback : pb::IMessage<ArmForceFeedback>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ArmForceFeedback> _parser = new pb::MessageParser<ArmForceFeedback>(() => new ArmForceFeedback());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ArmForceFeedback> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Protos.RobotStateReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ArmForceFeedback() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ArmForceFeedback(ArmForceFeedback other) : this() {
      maxForce_ = other.maxForce_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ArmForceFeedback Clone() {
      return new ArmForceFeedback(this);
    }

    /// <summary>Field number for the "max_force" field.</summary>
    public const int MaxForceFieldNumber = 1;
    private static readonly pb::FieldCodec<double> _repeated_maxForce_codec
        = pb::FieldCodec.ForDouble(10);
    private readonly pbc::RepeatedField<double> maxForce_ = new pbc::RepeatedField<double>();
    /// <summary>
    /// 各手臂 xyz 中最大的力，归一化到 0-255，索引0=左臂, 索引1=右臂，方便扩展
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<double> MaxForce {
      get { return maxForce_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ArmForceFeedback);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ArmForceFeedback other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!maxForce_.Equals(other.maxForce_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= maxForce_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      maxForce_.WriteTo(output, _repeated_maxForce_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      maxForce_.WriteTo(ref output, _repeated_maxForce_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += maxForce_.CalculateSize(_repeated_maxForce_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ArmForceFeedback other) {
      if (other == null) {
        return;
      }
      maxForce_.Add(other.maxForce_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10:
          case 9: {
            maxForce_.AddEntriesFrom(input, _repeated_maxForce_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10:
          case 9: {
            maxForce_.AddEntriesFrom(ref input, _repeated_maxForce_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class RobotState : pb::IMessage<RobotState>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RobotState> _parser = new pb::MessageParser<RobotState>(() => new RobotState());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<RobotState> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Protos.RobotStateReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RobotState() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RobotState(RobotState other) : this() {
      header_ = other.header_ != null ? other.header_.Clone() : null;
      eeState_ = other.eeState_ != null ? other.eeState_.Clone() : null;
      jointState_ = other.jointState_ != null ? other.jointState_.Clone() : null;
      itemMassForceResponse_ = other.itemMassForceResponse_ != null ? other.itemMassForceResponse_.Clone() : null;
      armForceFeedback_ = other.armForceFeedback_ != null ? other.armForceFeedback_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RobotState Clone() {
      return new RobotState(this);
    }

    /// <summary>Field number for the "header" field.</summary>
    public const int HeaderFieldNumber = 1;
    private global::Protos.Header header_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Protos.Header Header {
      get { return header_; }
      set {
        header_ = value;
      }
    }

    /// <summary>Field number for the "ee_state" field.</summary>
    public const int EeStateFieldNumber = 2;
    private global::Protos.EndEffectorState eeState_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Protos.EndEffectorState EeState {
      get { return eeState_; }
      set {
        eeState_ = value;
      }
    }

    /// <summary>Field number for the "joint_state" field.</summary>
    public const int JointStateFieldNumber = 3;
    private global::Protos.JointState jointState_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Protos.JointState JointState {
      get { return jointState_; }
      set {
        jointState_ = value;
      }
    }

    /// <summary>Field number for the "item_mass_force_response" field.</summary>
    public const int ItemMassForceResponseFieldNumber = 4;
    private global::Protos.ItemMassForceResponse itemMassForceResponse_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Protos.ItemMassForceResponse ItemMassForceResponse {
      get { return itemMassForceResponse_; }
      set {
        itemMassForceResponse_ = value;
      }
    }

    /// <summary>Field number for the "arm_force_feedback" field.</summary>
    public const int ArmForceFeedbackFieldNumber = 5;
    private global::Protos.ArmForceFeedback armForceFeedback_;
    /// <summary>
    /// 左右臂最大力反馈数据（可选）
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Protos.ArmForceFeedback ArmForceFeedback {
      get { return armForceFeedback_; }
      set {
        armForceFeedback_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as RobotState);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(RobotState other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Header, other.Header)) return false;
      if (!object.Equals(EeState, other.EeState)) return false;
      if (!object.Equals(JointState, other.JointState)) return false;
      if (!object.Equals(ItemMassForceResponse, other.ItemMassForceResponse)) return false;
      if (!object.Equals(ArmForceFeedback, other.ArmForceFeedback)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (header_ != null) hash ^= Header.GetHashCode();
      if (eeState_ != null) hash ^= EeState.GetHashCode();
      if (jointState_ != null) hash ^= JointState.GetHashCode();
      if (itemMassForceResponse_ != null) hash ^= ItemMassForceResponse.GetHashCode();
      if (armForceFeedback_ != null) hash ^= ArmForceFeedback.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (header_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Header);
      }
      if (eeState_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(EeState);
      }
      if (jointState_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(JointState);
      }
      if (itemMassForceResponse_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(ItemMassForceResponse);
      }
      if (armForceFeedback_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(ArmForceFeedback);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (header_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Header);
      }
      if (eeState_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(EeState);
      }
      if (jointState_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(JointState);
      }
      if (itemMassForceResponse_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(ItemMassForceResponse);
      }
      if (armForceFeedback_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(ArmForceFeedback);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (header_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Header);
      }
      if (eeState_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(EeState);
      }
      if (jointState_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(JointState);
      }
      if (itemMassForceResponse_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ItemMassForceResponse);
      }
      if (armForceFeedback_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ArmForceFeedback);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(RobotState other) {
      if (other == null) {
        return;
      }
      if (other.header_ != null) {
        if (header_ == null) {
          Header = new global::Protos.Header();
        }
        Header.MergeFrom(other.Header);
      }
      if (other.eeState_ != null) {
        if (eeState_ == null) {
          EeState = new global::Protos.EndEffectorState();
        }
        EeState.MergeFrom(other.EeState);
      }
      if (other.jointState_ != null) {
        if (jointState_ == null) {
          JointState = new global::Protos.JointState();
        }
        JointState.MergeFrom(other.JointState);
      }
      if (other.itemMassForceResponse_ != null) {
        if (itemMassForceResponse_ == null) {
          ItemMassForceResponse = new global::Protos.ItemMassForceResponse();
        }
        ItemMassForceResponse.MergeFrom(other.ItemMassForceResponse);
      }
      if (other.armForceFeedback_ != null) {
        if (armForceFeedback_ == null) {
          ArmForceFeedback = new global::Protos.ArmForceFeedback();
        }
        ArmForceFeedback.MergeFrom(other.ArmForceFeedback);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (header_ == null) {
              Header = new global::Protos.Header();
            }
            input.ReadMessage(Header);
            break;
          }
          case 18: {
            if (eeState_ == null) {
              EeState = new global::Protos.EndEffectorState();
            }
            input.ReadMessage(EeState);
            break;
          }
          case 26: {
            if (jointState_ == null) {
              JointState = new global::Protos.JointState();
            }
            input.ReadMessage(JointState);
            break;
          }
          case 34: {
            if (itemMassForceResponse_ == null) {
              ItemMassForceResponse = new global::Protos.ItemMassForceResponse();
            }
            input.ReadMessage(ItemMassForceResponse);
            break;
          }
          case 42: {
            if (armForceFeedback_ == null) {
              ArmForceFeedback = new global::Protos.ArmForceFeedback();
            }
            input.ReadMessage(ArmForceFeedback);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (header_ == null) {
              Header = new global::Protos.Header();
            }
            input.ReadMessage(Header);
            break;
          }
          case 18: {
            if (eeState_ == null) {
              EeState = new global::Protos.EndEffectorState();
            }
            input.ReadMessage(EeState);
            break;
          }
          case 26: {
            if (jointState_ == null) {
              JointState = new global::Protos.JointState();
            }
            input.ReadMessage(JointState);
            break;
          }
          case 34: {
            if (itemMassForceResponse_ == null) {
              ItemMassForceResponse = new global::Protos.ItemMassForceResponse();
            }
            input.ReadMessage(ItemMassForceResponse);
            break;
          }
          case 42: {
            if (armForceFeedback_ == null) {
              ArmForceFeedback = new global::Protos.ArmForceFeedback();
            }
            input.ReadMessage(ArmForceFeedback);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
