# This message defines the information for a single gesture.
# It includes the name, a list of aliases, and a description of the gesture.

# The name of the gesture.
string gesture_name

# A list of aliases for the gesture. These can be alternative names or shortcuts.
string[] alias

# A description of the gesture, providing more detailed information about its purpose and usage.
string description