/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to CXX Translator
  File name: ImuData.idl
  Source: ImuData.hpp
  Cyclone DDS: v0.10.2

*****************************************************************/
#ifndef DDSCXX_IMUDATA_HPP
#define DDSCXX_IMUDATA_HPP

#include <array>

namespace leju
{
namespace msgs
{
class ImuData
{
private:
 std::array<double, 3> gyro_ = { };
 std::array<double, 3> acc_ = { };
 std::array<double, 3> free_acc_ = { };
 std::array<double, 4> quat_ = { };

public:
  ImuData() = default;

  explicit ImuData(
    const std::array<double, 3>& gyro,
    const std::array<double, 3>& acc,
    const std::array<double, 3>& free_acc,
    const std::array<double, 4>& quat) :
    gyro_(gyro),
    acc_(acc),
    free_acc_(free_acc),
    quat_(quat) { }

  const std::array<double, 3>& gyro() const { return this->gyro_; }
  std::array<double, 3>& gyro() { return this->gyro_; }
  void gyro(const std::array<double, 3>& _val_) { this->gyro_ = _val_; }
  void gyro(std::array<double, 3>&& _val_) { this->gyro_ = _val_; }
  const std::array<double, 3>& acc() const { return this->acc_; }
  std::array<double, 3>& acc() { return this->acc_; }
  void acc(const std::array<double, 3>& _val_) { this->acc_ = _val_; }
  void acc(std::array<double, 3>&& _val_) { this->acc_ = _val_; }
  const std::array<double, 3>& free_acc() const { return this->free_acc_; }
  std::array<double, 3>& free_acc() { return this->free_acc_; }
  void free_acc(const std::array<double, 3>& _val_) { this->free_acc_ = _val_; }
  void free_acc(std::array<double, 3>&& _val_) { this->free_acc_ = _val_; }
  const std::array<double, 4>& quat() const { return this->quat_; }
  std::array<double, 4>& quat() { return this->quat_; }
  void quat(const std::array<double, 4>& _val_) { this->quat_ = _val_; }
  void quat(std::array<double, 4>&& _val_) { this->quat_ = _val_; }

  bool operator==(const ImuData& _other) const
  {
    (void) _other;
    return gyro_ == _other.gyro_ &&
      acc_ == _other.acc_ &&
      free_acc_ == _other.free_acc_ &&
      quat_ == _other.quat_;
  }

  bool operator!=(const ImuData& _other) const
  {
    return !(*this == _other);
  }

};

}

}

#include "dds/topic/TopicTraits.hpp"
#include "org/eclipse/cyclonedds/topic/datatopic.hpp"

namespace org {
namespace eclipse {
namespace cyclonedds {
namespace topic {

template <> constexpr const char* TopicTraits<::leju::msgs::ImuData>::getTypeName()
{
  return "leju::msgs::ImuData";
}

template <> constexpr bool TopicTraits<::leju::msgs::ImuData>::isKeyless()
{
  return true;
}

#ifdef DDSCXX_HAS_TYPE_DISCOVERY
template<> constexpr unsigned int TopicTraits<::leju::msgs::ImuData>::type_map_blob_sz() { return 418; }
template<> constexpr unsigned int TopicTraits<::leju::msgs::ImuData>::type_info_blob_sz() { return 100; }
template<> inline const uint8_t * TopicTraits<::leju::msgs::ImuData>::type_map_blob() {
  static const uint8_t blob[] = {
 0x9a,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0xf1,  0xe3,  0xf2,  0x3a,  0xe7,  0x40,  0xa1,  0x82, 
 0x9f,  0xd5,  0xe0,  0x2f,  0x64,  0xc0,  0xb3,  0x00,  0x82,  0x00,  0x00,  0x00,  0xf1,  0x51,  0x01,  0x00, 
 0x01,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x72,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00, 
 0x16,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x01,  0x00,  0x90,  0xf3,  0x01,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x00,  0x00,  0x03,  0x0a,  0x41,  0xe1,  0xdb,  0x58,  0x00,  0x00,  0x16,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x00,  0x00,  0x01,  0x00,  0x90,  0xf3,  0x01,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00, 
 0x03,  0x0a,  0x16,  0x73,  0x44,  0x8e,  0x00,  0x00,  0x16,  0x00,  0x00,  0x00,  0x02,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x90,  0xf3,  0x01,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0x03,  0x0a,  0x2a,  0xdc, 
 0x55,  0x1a,  0x00,  0x00,  0x16,  0x00,  0x00,  0x00,  0x03,  0x00,  0x00,  0x00,  0x01,  0x00,  0x90,  0xf3, 
 0x01,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0x04,  0x0a,  0x21,  0xd7,  0xdc,  0x6a,  0x00,  0x00, 
 0xd7,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0xf2,  0x39,  0x9b,  0xf5,  0xcb,  0xcd,  0x85,  0xe6, 
 0xbc,  0x0a,  0x0b,  0x1d,  0xd3,  0x62,  0x89,  0x00,  0xbf,  0x00,  0x00,  0x00,  0xf2,  0x51,  0x01,  0x00, 
 0x1c,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x14,  0x00,  0x00,  0x00,  0x6c,  0x65,  0x6a,  0x75, 
 0x3a,  0x3a,  0x6d,  0x73,  0x67,  0x73,  0x3a,  0x3a,  0x49,  0x6d,  0x75,  0x44,  0x61,  0x74,  0x61,  0x00, 
 0x97,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00,  0x1f,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x90,  0xf3,  0x01,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0x03,  0x0a,  0x00,  0x00, 
 0x05,  0x00,  0x00,  0x00,  0x67,  0x79,  0x72,  0x6f,  0x00,  0x00,  0x00,  0x00,  0x1e,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x00,  0x00,  0x01,  0x00,  0x90,  0xf3,  0x01,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00, 
 0x03,  0x0a,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00,  0x61,  0x63,  0x63,  0x00,  0x00,  0x00,  0x00,  0x00, 
 0x23,  0x00,  0x00,  0x00,  0x02,  0x00,  0x00,  0x00,  0x01,  0x00,  0x90,  0xf3,  0x01,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x00,  0x00,  0x03,  0x0a,  0x00,  0x00,  0x09,  0x00,  0x00,  0x00,  0x66,  0x72,  0x65,  0x65, 
 0x5f,  0x61,  0x63,  0x63,  0x00,  0x00,  0x00,  0x00,  0x1f,  0x00,  0x00,  0x00,  0x03,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x90,  0xf3,  0x01,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0x04,  0x0a,  0x00,  0x00, 
 0x05,  0x00,  0x00,  0x00,  0x71,  0x75,  0x61,  0x74,  0x00,  0x00,  0x00,  0x00,  0x22,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x00,  0x00,  0xf2,  0x39,  0x9b,  0xf5,  0xcb,  0xcd,  0x85,  0xe6,  0xbc,  0x0a,  0x0b,  0x1d, 
 0xd3,  0x62,  0x89,  0xf1,  0xe3,  0xf2,  0x3a,  0xe7,  0x40,  0xa1,  0x82,  0x9f,  0xd5,  0xe0,  0x2f,  0x64, 
 0xc0,  0xb3, };
  return blob;
}
template<> inline const uint8_t * TopicTraits<::leju::msgs::ImuData>::type_info_blob() {
  static const uint8_t blob[] = {
 0x60,  0x00,  0x00,  0x00,  0x01,  0x10,  0x00,  0x40,  0x28,  0x00,  0x00,  0x00,  0x24,  0x00,  0x00,  0x00, 
 0x14,  0x00,  0x00,  0x00,  0xf1,  0xe3,  0xf2,  0x3a,  0xe7,  0x40,  0xa1,  0x82,  0x9f,  0xd5,  0xe0,  0x2f, 
 0x64,  0xc0,  0xb3,  0x00,  0x86,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00,  0x02,  0x10,  0x00,  0x40,  0x28,  0x00,  0x00,  0x00,  0x24,  0x00,  0x00,  0x00, 
 0x14,  0x00,  0x00,  0x00,  0xf2,  0x39,  0x9b,  0xf5,  0xcb,  0xcd,  0x85,  0xe6,  0xbc,  0x0a,  0x0b,  0x1d, 
 0xd3,  0x62,  0x89,  0x00,  0xc3,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00, };
  return blob;
}
#endif //DDSCXX_HAS_TYPE_DISCOVERY

} //namespace topic
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

namespace dds {
namespace topic {

template <>
struct topic_type_name<::leju::msgs::ImuData>
{
    static std::string value()
    {
      return org::eclipse::cyclonedds::topic::TopicTraits<::leju::msgs::ImuData>::getTypeName();
    }
};

}
}

REGISTER_TOPIC_TYPE(::leju::msgs::ImuData)

namespace org{
namespace eclipse{
namespace cyclonedds{
namespace core{
namespace cdr{

template<>
propvec &get_type_props<::leju::msgs::ImuData>();

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool write(T& streamer, const ::leju::msgs::ImuData& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(true, true))
        return false;
      if (!write(streamer, instance.gyro()[0], instance.gyro().size()))
        return false;
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(true, true))
        return false;
      if (!write(streamer, instance.acc()[0], instance.acc().size()))
        return false;
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(true, true))
        return false;
      if (!write(streamer, instance.free_acc()[0], instance.free_acc().size()))
        return false;
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 3:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(true, true))
        return false;
      if (!write(streamer, instance.quat()[0], instance.quat().size()))
        return false;
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool write(S& str, const ::leju::msgs::ImuData& instance, bool as_key) {
  auto &props = get_type_props<::leju::msgs::ImuData>();
  str.set_mode(cdr_stream::stream_mode::write, as_key);
  return write(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool read(T& streamer, ::leju::msgs::ImuData& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(true, true))
        return false;
      if (!read(streamer, instance.gyro()[0], instance.gyro().size()))
        return false;
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(true, true))
        return false;
      if (!read(streamer, instance.acc()[0], instance.acc().size()))
        return false;
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(true, true))
        return false;
      if (!read(streamer, instance.free_acc()[0], instance.free_acc().size()))
        return false;
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 3:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(true, true))
        return false;
      if (!read(streamer, instance.quat()[0], instance.quat().size()))
        return false;
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool read(S& str, ::leju::msgs::ImuData& instance, bool as_key) {
  auto &props = get_type_props<::leju::msgs::ImuData>();
  str.set_mode(cdr_stream::stream_mode::read, as_key);
  return read(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool move(T& streamer, const ::leju::msgs::ImuData& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(true, true))
        return false;
      if (!move(streamer, instance.gyro()[0], instance.gyro().size()))
        return false;
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(true, true))
        return false;
      if (!move(streamer, instance.acc()[0], instance.acc().size()))
        return false;
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(true, true))
        return false;
      if (!move(streamer, instance.free_acc()[0], instance.free_acc().size()))
        return false;
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 3:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(true, true))
        return false;
      if (!move(streamer, instance.quat()[0], instance.quat().size()))
        return false;
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool move(S& str, const ::leju::msgs::ImuData& instance, bool as_key) {
  auto &props = get_type_props<::leju::msgs::ImuData>();
  str.set_mode(cdr_stream::stream_mode::move, as_key);
  return move(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool max(T& streamer, const ::leju::msgs::ImuData& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(true, true))
        return false;
      if (!max(streamer, instance.gyro()[0], instance.gyro().size()))
        return false;
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(true, true))
        return false;
      if (!max(streamer, instance.acc()[0], instance.acc().size()))
        return false;
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(true, true))
        return false;
      if (!max(streamer, instance.free_acc()[0], instance.free_acc().size()))
        return false;
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 3:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(true, true))
        return false;
      if (!max(streamer, instance.quat()[0], instance.quat().size()))
        return false;
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool max(S& str, const ::leju::msgs::ImuData& instance, bool as_key) {
  auto &props = get_type_props<::leju::msgs::ImuData>();
  str.set_mode(cdr_stream::stream_mode::max, as_key);
  return max(str, instance, props.data()); 
}

} //namespace cdr
} //namespace core
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

#endif // DDSCXX_IMUDATA_HPP
