/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to CXX Translator
  File name: JointCmd.idl
  Source: JointCmd.hpp
  Cyclone DDS: v0.10.2

*****************************************************************/
#ifndef DDSCXX_JOINTCMD_HPP
#define DDSCXX_JOINTCMD_HPP

#include <cstdint>
#include <vector>

namespace leju
{
namespace msgs
{
class JointCmd
{
private:
 int32_t header_sec_ = 0;
 uint32_t header_nanosec_ = 0;
 std::vector<double> joint_q_;
 std::vector<double> joint_v_;
 std::vector<double> tau_;
 std::vector<double> tau_max_;
 std::vector<double> tau_ratio_;
 std::vector<double> joint_kp_;
 std::vector<double> joint_kd_;
 std::vector<int32_t> control_modes_;

public:
  JointCmd() = default;

  explicit JointCmd(
    int32_t header_sec,
    uint32_t header_nanosec,
    const std::vector<double>& joint_q,
    const std::vector<double>& joint_v,
    const std::vector<double>& tau,
    const std::vector<double>& tau_max,
    const std::vector<double>& tau_ratio,
    const std::vector<double>& joint_kp,
    const std::vector<double>& joint_kd,
    const std::vector<int32_t>& control_modes) :
    header_sec_(header_sec),
    header_nanosec_(header_nanosec),
    joint_q_(joint_q),
    joint_v_(joint_v),
    tau_(tau),
    tau_max_(tau_max),
    tau_ratio_(tau_ratio),
    joint_kp_(joint_kp),
    joint_kd_(joint_kd),
    control_modes_(control_modes) { }

  int32_t header_sec() const { return this->header_sec_; }
  int32_t& header_sec() { return this->header_sec_; }
  void header_sec(int32_t _val_) { this->header_sec_ = _val_; }
  uint32_t header_nanosec() const { return this->header_nanosec_; }
  uint32_t& header_nanosec() { return this->header_nanosec_; }
  void header_nanosec(uint32_t _val_) { this->header_nanosec_ = _val_; }
  const std::vector<double>& joint_q() const { return this->joint_q_; }
  std::vector<double>& joint_q() { return this->joint_q_; }
  void joint_q(const std::vector<double>& _val_) { this->joint_q_ = _val_; }
  void joint_q(std::vector<double>&& _val_) { this->joint_q_ = _val_; }
  const std::vector<double>& joint_v() const { return this->joint_v_; }
  std::vector<double>& joint_v() { return this->joint_v_; }
  void joint_v(const std::vector<double>& _val_) { this->joint_v_ = _val_; }
  void joint_v(std::vector<double>&& _val_) { this->joint_v_ = _val_; }
  const std::vector<double>& tau() const { return this->tau_; }
  std::vector<double>& tau() { return this->tau_; }
  void tau(const std::vector<double>& _val_) { this->tau_ = _val_; }
  void tau(std::vector<double>&& _val_) { this->tau_ = _val_; }
  const std::vector<double>& tau_max() const { return this->tau_max_; }
  std::vector<double>& tau_max() { return this->tau_max_; }
  void tau_max(const std::vector<double>& _val_) { this->tau_max_ = _val_; }
  void tau_max(std::vector<double>&& _val_) { this->tau_max_ = _val_; }
  const std::vector<double>& tau_ratio() const { return this->tau_ratio_; }
  std::vector<double>& tau_ratio() { return this->tau_ratio_; }
  void tau_ratio(const std::vector<double>& _val_) { this->tau_ratio_ = _val_; }
  void tau_ratio(std::vector<double>&& _val_) { this->tau_ratio_ = _val_; }
  const std::vector<double>& joint_kp() const { return this->joint_kp_; }
  std::vector<double>& joint_kp() { return this->joint_kp_; }
  void joint_kp(const std::vector<double>& _val_) { this->joint_kp_ = _val_; }
  void joint_kp(std::vector<double>&& _val_) { this->joint_kp_ = _val_; }
  const std::vector<double>& joint_kd() const { return this->joint_kd_; }
  std::vector<double>& joint_kd() { return this->joint_kd_; }
  void joint_kd(const std::vector<double>& _val_) { this->joint_kd_ = _val_; }
  void joint_kd(std::vector<double>&& _val_) { this->joint_kd_ = _val_; }
  const std::vector<int32_t>& control_modes() const { return this->control_modes_; }
  std::vector<int32_t>& control_modes() { return this->control_modes_; }
  void control_modes(const std::vector<int32_t>& _val_) { this->control_modes_ = _val_; }
  void control_modes(std::vector<int32_t>&& _val_) { this->control_modes_ = _val_; }

  bool operator==(const JointCmd& _other) const
  {
    (void) _other;
    return header_sec_ == _other.header_sec_ &&
      header_nanosec_ == _other.header_nanosec_ &&
      joint_q_ == _other.joint_q_ &&
      joint_v_ == _other.joint_v_ &&
      tau_ == _other.tau_ &&
      tau_max_ == _other.tau_max_ &&
      tau_ratio_ == _other.tau_ratio_ &&
      joint_kp_ == _other.joint_kp_ &&
      joint_kd_ == _other.joint_kd_ &&
      control_modes_ == _other.control_modes_;
  }

  bool operator!=(const JointCmd& _other) const
  {
    return !(*this == _other);
  }

};

}

}

#include "dds/topic/TopicTraits.hpp"
#include "org/eclipse/cyclonedds/topic/datatopic.hpp"

namespace org {
namespace eclipse {
namespace cyclonedds {
namespace topic {

template <> constexpr const char* TopicTraits<::leju::msgs::JointCmd>::getTypeName()
{
  return "leju::msgs::JointCmd";
}

template <> constexpr bool TopicTraits<::leju::msgs::JointCmd>::isSelfContained()
{
  return false;
}

template <> constexpr bool TopicTraits<::leju::msgs::JointCmd>::isKeyless()
{
  return true;
}

#ifdef DDSCXX_HAS_TYPE_DISCOVERY
template<> constexpr unsigned int TopicTraits<::leju::msgs::JointCmd>::type_map_blob_sz() { return 678; }
template<> constexpr unsigned int TopicTraits<::leju::msgs::JointCmd>::type_info_blob_sz() { return 100; }
template<> inline const uint8_t * TopicTraits<::leju::msgs::JointCmd>::type_map_blob() {
  static const uint8_t blob[] = {
 0xec,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0xf1,  0xfd,  0x70,  0x9d,  0xe3,  0x5a,  0x59,  0x8e, 
 0xa9,  0x6a,  0x01,  0x2c,  0x02,  0x38,  0xb0,  0x00,  0xd4,  0x00,  0x00,  0x00,  0xf1,  0x51,  0x01,  0x00, 
 0x01,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0xc4,  0x00,  0x00,  0x00,  0x0a,  0x00,  0x00,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x01,  0x00,  0x04,  0x8d,  0xe9,  0xf3,  0x63,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0x01,  0x00,  0x07,  0x80,  0xf9,  0xcc,  0x35,  0x00, 
 0x10,  0x00,  0x00,  0x00,  0x02,  0x00,  0x00,  0x00,  0x01,  0x00,  0x80,  0xf3,  0x01,  0x00,  0x00,  0x0a, 
 0xaf,  0xd6,  0xc1,  0x7b,  0x10,  0x00,  0x00,  0x00,  0x03,  0x00,  0x00,  0x00,  0x01,  0x00,  0x80,  0xf3, 
 0x01,  0x00,  0x00,  0x0a,  0xb1,  0x1c,  0x3a,  0x81,  0x10,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x80,  0xf3,  0x01,  0x00,  0x00,  0x0a,  0x45,  0x80,  0xc2,  0x74,  0x10,  0x00,  0x00,  0x00, 
 0x05,  0x00,  0x00,  0x00,  0x01,  0x00,  0x80,  0xf3,  0x01,  0x00,  0x00,  0x0a,  0x09,  0x18,  0xc6,  0x8f, 
 0x10,  0x00,  0x00,  0x00,  0x06,  0x00,  0x00,  0x00,  0x01,  0x00,  0x80,  0xf3,  0x01,  0x00,  0x00,  0x0a, 
 0x1a,  0x49,  0x62,  0x51,  0x10,  0x00,  0x00,  0x00,  0x07,  0x00,  0x00,  0x00,  0x01,  0x00,  0x80,  0xf3, 
 0x01,  0x00,  0x00,  0x0a,  0xf9,  0xdc,  0x51,  0x53,  0x10,  0x00,  0x00,  0x00,  0x08,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x80,  0xf3,  0x01,  0x00,  0x00,  0x0a,  0x42,  0x11,  0x9e,  0x2f,  0x10,  0x00,  0x00,  0x00, 
 0x09,  0x00,  0x00,  0x00,  0x01,  0x00,  0x80,  0xf3,  0x01,  0x00,  0x00,  0x04,  0xc4,  0x50,  0xfb,  0x9c, 
 0x8c,  0x01,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0xf2,  0x77,  0x18,  0xb6,  0x05,  0xc7,  0x2c,  0x2f, 
 0xd3,  0xfc,  0xcc,  0x25,  0xf3,  0x13,  0x3a,  0x00,  0x74,  0x01,  0x00,  0x00,  0xf2,  0x51,  0x01,  0x00, 
 0x1d,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x15,  0x00,  0x00,  0x00,  0x6c,  0x65,  0x6a,  0x75, 
 0x3a,  0x3a,  0x6d,  0x73,  0x67,  0x73,  0x3a,  0x3a,  0x4a,  0x6f,  0x69,  0x6e,  0x74,  0x43,  0x6d,  0x64, 
 0x00,  0x00,  0x00,  0x00,  0x48,  0x01,  0x00,  0x00,  0x0a,  0x00,  0x00,  0x00,  0x19,  0x00,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00,  0x01,  0x00,  0x04,  0x00,  0x0b,  0x00,  0x00,  0x00,  0x68,  0x65,  0x61,  0x64, 
 0x65,  0x72,  0x5f,  0x73,  0x65,  0x63,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x1d,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x00,  0x00,  0x01,  0x00,  0x07,  0x00,  0x0f,  0x00,  0x00,  0x00,  0x68,  0x65,  0x61,  0x64, 
 0x65,  0x72,  0x5f,  0x6e,  0x61,  0x6e,  0x6f,  0x73,  0x65,  0x63,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00, 
 0x1a,  0x00,  0x00,  0x00,  0x02,  0x00,  0x00,  0x00,  0x01,  0x00,  0x80,  0xf3,  0x01,  0x00,  0x00,  0x0a, 
 0x08,  0x00,  0x00,  0x00,  0x6a,  0x6f,  0x69,  0x6e,  0x74,  0x5f,  0x71,  0x00,  0x00,  0x00,  0x00,  0x00, 
 0x1a,  0x00,  0x00,  0x00,  0x03,  0x00,  0x00,  0x00,  0x01,  0x00,  0x80,  0xf3,  0x01,  0x00,  0x00,  0x0a, 
 0x08,  0x00,  0x00,  0x00,  0x6a,  0x6f,  0x69,  0x6e,  0x74,  0x5f,  0x76,  0x00,  0x00,  0x00,  0x00,  0x00, 
 0x16,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00,  0x01,  0x00,  0x80,  0xf3,  0x01,  0x00,  0x00,  0x0a, 
 0x04,  0x00,  0x00,  0x00,  0x74,  0x61,  0x75,  0x00,  0x00,  0x00,  0x00,  0x00,  0x1a,  0x00,  0x00,  0x00, 
 0x05,  0x00,  0x00,  0x00,  0x01,  0x00,  0x80,  0xf3,  0x01,  0x00,  0x00,  0x0a,  0x08,  0x00,  0x00,  0x00, 
 0x74,  0x61,  0x75,  0x5f,  0x6d,  0x61,  0x78,  0x00,  0x00,  0x00,  0x00,  0x00,  0x1c,  0x00,  0x00,  0x00, 
 0x06,  0x00,  0x00,  0x00,  0x01,  0x00,  0x80,  0xf3,  0x01,  0x00,  0x00,  0x0a,  0x0a,  0x00,  0x00,  0x00, 
 0x74,  0x61,  0x75,  0x5f,  0x72,  0x61,  0x74,  0x69,  0x6f,  0x00,  0x00,  0x00,  0x1b,  0x00,  0x00,  0x00, 
 0x07,  0x00,  0x00,  0x00,  0x01,  0x00,  0x80,  0xf3,  0x01,  0x00,  0x00,  0x0a,  0x09,  0x00,  0x00,  0x00, 
 0x6a,  0x6f,  0x69,  0x6e,  0x74,  0x5f,  0x6b,  0x70,  0x00,  0x00,  0x00,  0x00,  0x1b,  0x00,  0x00,  0x00, 
 0x08,  0x00,  0x00,  0x00,  0x01,  0x00,  0x80,  0xf3,  0x01,  0x00,  0x00,  0x0a,  0x09,  0x00,  0x00,  0x00, 
 0x6a,  0x6f,  0x69,  0x6e,  0x74,  0x5f,  0x6b,  0x64,  0x00,  0x00,  0x00,  0x00,  0x20,  0x00,  0x00,  0x00, 
 0x09,  0x00,  0x00,  0x00,  0x01,  0x00,  0x80,  0xf3,  0x01,  0x00,  0x00,  0x04,  0x0e,  0x00,  0x00,  0x00, 
 0x63,  0x6f,  0x6e,  0x74,  0x72,  0x6f,  0x6c,  0x5f,  0x6d,  0x6f,  0x64,  0x65,  0x73,  0x00,  0x00,  0x00, 
 0x22,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0xf2,  0x77,  0x18,  0xb6,  0x05,  0xc7,  0x2c,  0x2f, 
 0xd3,  0xfc,  0xcc,  0x25,  0xf3,  0x13,  0x3a,  0xf1,  0xfd,  0x70,  0x9d,  0xe3,  0x5a,  0x59,  0x8e,  0xa9, 
 0x6a,  0x01,  0x2c,  0x02,  0x38,  0xb0, };
  return blob;
}
template<> inline const uint8_t * TopicTraits<::leju::msgs::JointCmd>::type_info_blob() {
  static const uint8_t blob[] = {
 0x60,  0x00,  0x00,  0x00,  0x01,  0x10,  0x00,  0x40,  0x28,  0x00,  0x00,  0x00,  0x24,  0x00,  0x00,  0x00, 
 0x14,  0x00,  0x00,  0x00,  0xf1,  0xfd,  0x70,  0x9d,  0xe3,  0x5a,  0x59,  0x8e,  0xa9,  0x6a,  0x01,  0x2c, 
 0x02,  0x38,  0xb0,  0x00,  0xd8,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00,  0x02,  0x10,  0x00,  0x40,  0x28,  0x00,  0x00,  0x00,  0x24,  0x00,  0x00,  0x00, 
 0x14,  0x00,  0x00,  0x00,  0xf2,  0x77,  0x18,  0xb6,  0x05,  0xc7,  0x2c,  0x2f,  0xd3,  0xfc,  0xcc,  0x25, 
 0xf3,  0x13,  0x3a,  0x00,  0x78,  0x01,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00, };
  return blob;
}
#endif //DDSCXX_HAS_TYPE_DISCOVERY

} //namespace topic
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

namespace dds {
namespace topic {

template <>
struct topic_type_name<::leju::msgs::JointCmd>
{
    static std::string value()
    {
      return org::eclipse::cyclonedds::topic::TopicTraits<::leju::msgs::JointCmd>::getTypeName();
    }
};

}
}

REGISTER_TOPIC_TYPE(::leju::msgs::JointCmd)

namespace org{
namespace eclipse{
namespace cyclonedds{
namespace core{
namespace cdr{

template<>
propvec &get_type_props<::leju::msgs::JointCmd>();

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool write(T& streamer, const ::leju::msgs::JointCmd& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.header_sec()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.header_nanosec()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.joint_q().size());
      if (!write(streamer, se_1))
        return false;
      if (se_1 > 0 &&
          !write(streamer, instance.joint_q()[0], se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 3:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.joint_v().size());
      if (!write(streamer, se_1))
        return false;
      if (se_1 > 0 &&
          !write(streamer, instance.joint_v()[0], se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 4:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.tau().size());
      if (!write(streamer, se_1))
        return false;
      if (se_1 > 0 &&
          !write(streamer, instance.tau()[0], se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 5:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.tau_max().size());
      if (!write(streamer, se_1))
        return false;
      if (se_1 > 0 &&
          !write(streamer, instance.tau_max()[0], se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 6:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.tau_ratio().size());
      if (!write(streamer, se_1))
        return false;
      if (se_1 > 0 &&
          !write(streamer, instance.tau_ratio()[0], se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 7:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.joint_kp().size());
      if (!write(streamer, se_1))
        return false;
      if (se_1 > 0 &&
          !write(streamer, instance.joint_kp()[0], se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 8:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.joint_kd().size());
      if (!write(streamer, se_1))
        return false;
      if (se_1 > 0 &&
          !write(streamer, instance.joint_kd()[0], se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 9:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.control_modes().size());
      if (!write(streamer, se_1))
        return false;
      if (se_1 > 0 &&
          !write(streamer, instance.control_modes()[0], se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool write(S& str, const ::leju::msgs::JointCmd& instance, bool as_key) {
  auto &props = get_type_props<::leju::msgs::JointCmd>();
  str.set_mode(cdr_stream::stream_mode::write, as_key);
  return write(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool read(T& streamer, ::leju::msgs::JointCmd& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.header_sec()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.header_nanosec()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.joint_q().size());
      if (!read(streamer, se_1))
        return false;
      instance.joint_q().resize(se_1);
      if (se_1 > 0 &&
          !read(streamer, instance.joint_q()[0], se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 3:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.joint_v().size());
      if (!read(streamer, se_1))
        return false;
      instance.joint_v().resize(se_1);
      if (se_1 > 0 &&
          !read(streamer, instance.joint_v()[0], se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 4:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.tau().size());
      if (!read(streamer, se_1))
        return false;
      instance.tau().resize(se_1);
      if (se_1 > 0 &&
          !read(streamer, instance.tau()[0], se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 5:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.tau_max().size());
      if (!read(streamer, se_1))
        return false;
      instance.tau_max().resize(se_1);
      if (se_1 > 0 &&
          !read(streamer, instance.tau_max()[0], se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 6:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.tau_ratio().size());
      if (!read(streamer, se_1))
        return false;
      instance.tau_ratio().resize(se_1);
      if (se_1 > 0 &&
          !read(streamer, instance.tau_ratio()[0], se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 7:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.joint_kp().size());
      if (!read(streamer, se_1))
        return false;
      instance.joint_kp().resize(se_1);
      if (se_1 > 0 &&
          !read(streamer, instance.joint_kp()[0], se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 8:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.joint_kd().size());
      if (!read(streamer, se_1))
        return false;
      instance.joint_kd().resize(se_1);
      if (se_1 > 0 &&
          !read(streamer, instance.joint_kd()[0], se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 9:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.control_modes().size());
      if (!read(streamer, se_1))
        return false;
      instance.control_modes().resize(se_1);
      if (se_1 > 0 &&
          !read(streamer, instance.control_modes()[0], se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool read(S& str, ::leju::msgs::JointCmd& instance, bool as_key) {
  auto &props = get_type_props<::leju::msgs::JointCmd>();
  str.set_mode(cdr_stream::stream_mode::read, as_key);
  return read(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool move(T& streamer, const ::leju::msgs::JointCmd& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.header_sec()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.header_nanosec()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.joint_q().size());
      if (!move(streamer, se_1))
        return false;
      if (se_1 > 0 &&
          !move(streamer, double(), se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 3:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.joint_v().size());
      if (!move(streamer, se_1))
        return false;
      if (se_1 > 0 &&
          !move(streamer, double(), se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 4:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.tau().size());
      if (!move(streamer, se_1))
        return false;
      if (se_1 > 0 &&
          !move(streamer, double(), se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 5:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.tau_max().size());
      if (!move(streamer, se_1))
        return false;
      if (se_1 > 0 &&
          !move(streamer, double(), se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 6:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.tau_ratio().size());
      if (!move(streamer, se_1))
        return false;
      if (se_1 > 0 &&
          !move(streamer, double(), se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 7:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.joint_kp().size());
      if (!move(streamer, se_1))
        return false;
      if (se_1 > 0 &&
          !move(streamer, double(), se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 8:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.joint_kd().size());
      if (!move(streamer, se_1))
        return false;
      if (se_1 > 0 &&
          !move(streamer, double(), se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 9:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.control_modes().size());
      if (!move(streamer, se_1))
        return false;
      if (se_1 > 0 &&
          !move(streamer, int32_t(), se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool move(S& str, const ::leju::msgs::JointCmd& instance, bool as_key) {
  auto &props = get_type_props<::leju::msgs::JointCmd>();
  str.set_mode(cdr_stream::stream_mode::move, as_key);
  return move(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool max(T& streamer, const ::leju::msgs::JointCmd& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.header_sec()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.header_nanosec()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = 0;
      if (!max(streamer, se_1))
        return false;
      if (se_1 > 0 &&
          !max(streamer, double(), se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      streamer.position(SIZE_MAX);
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 3:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = 0;
      if (!max(streamer, se_1))
        return false;
      if (se_1 > 0 &&
          !max(streamer, double(), se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      streamer.position(SIZE_MAX);
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 4:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = 0;
      if (!max(streamer, se_1))
        return false;
      if (se_1 > 0 &&
          !max(streamer, double(), se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      streamer.position(SIZE_MAX);
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 5:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = 0;
      if (!max(streamer, se_1))
        return false;
      if (se_1 > 0 &&
          !max(streamer, double(), se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      streamer.position(SIZE_MAX);
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 6:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = 0;
      if (!max(streamer, se_1))
        return false;
      if (se_1 > 0 &&
          !max(streamer, double(), se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      streamer.position(SIZE_MAX);
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 7:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = 0;
      if (!max(streamer, se_1))
        return false;
      if (se_1 > 0 &&
          !max(streamer, double(), se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      streamer.position(SIZE_MAX);
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 8:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = 0;
      if (!max(streamer, se_1))
        return false;
      if (se_1 > 0 &&
          !max(streamer, double(), se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      streamer.position(SIZE_MAX);
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 9:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = 0;
      if (!max(streamer, se_1))
        return false;
      if (se_1 > 0 &&
          !max(streamer, int32_t(), se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      streamer.position(SIZE_MAX);
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool max(S& str, const ::leju::msgs::JointCmd& instance, bool as_key) {
  auto &props = get_type_props<::leju::msgs::JointCmd>();
  str.set_mode(cdr_stream::stream_mode::max, as_key);
  return max(str, instance, props.data()); 
}

} //namespace cdr
} //namespace core
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

#endif // DDSCXX_JOINTCMD_HPP
