/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to CXX Translator
  File name: JointCmd.idl
  Source: JointCmd.cpp
  Cyclone DDS: v0.10.2

*****************************************************************/
#include "JointCmd.hpp"

namespace org{
namespace eclipse{
namespace cyclonedds{
namespace core{
namespace cdr{

template<>
propvec &get_type_props<::leju::msgs::JointCmd>() {
  static thread_local std::mutex mtx;
  static thread_local propvec props;
  static thread_local entity_properties_t *props_end = nullptr;
  static thread_local std::atomic_bool initialized {false};
  key_endpoint keylist;
  if (initialized.load(std::memory_order_relaxed)) {
    auto ptr = props.data();
    while (ptr < props_end)
      (ptr++)->is_present = false;
    return props;
  }
  std::lock_guard<std::mutex> lock(mtx);
  if (initialized.load(std::memory_order_relaxed)) {
    auto ptr = props.data();
    while (ptr < props_end)
      (ptr++)->is_present = false;
    return props;
  }
  props.clear();

  props.push_back(entity_properties_t(0, 0, false, bb_unset, extensibility::ext_final));  //root
  props.push_back(entity_properties_t(1, 0, false, get_bit_bound<int32_t>(), extensibility::ext_final, false));  //::header_sec
  props.push_back(entity_properties_t(1, 1, false, get_bit_bound<uint32_t>(), extensibility::ext_final, false));  //::header_nanosec
  props.push_back(entity_properties_t(1, 2, false, bb_unset, extensibility::ext_final, false));  //::joint_q
  props.push_back(entity_properties_t(1, 3, false, bb_unset, extensibility::ext_final, false));  //::joint_v
  props.push_back(entity_properties_t(1, 4, false, bb_unset, extensibility::ext_final, false));  //::tau
  props.push_back(entity_properties_t(1, 5, false, bb_unset, extensibility::ext_final, false));  //::tau_max
  props.push_back(entity_properties_t(1, 6, false, bb_unset, extensibility::ext_final, false));  //::tau_ratio
  props.push_back(entity_properties_t(1, 7, false, bb_unset, extensibility::ext_final, false));  //::joint_kp
  props.push_back(entity_properties_t(1, 8, false, bb_unset, extensibility::ext_final, false));  //::joint_kd
  props.push_back(entity_properties_t(1, 9, false, bb_unset, extensibility::ext_final, false));  //::control_modes

  entity_properties_t::finish(props, keylist);
  props_end = props.data() + props.size();
  initialized.store(true, std::memory_order_release);
  return props;
}

} //namespace cdr
} //namespace core
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

