// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: delayed_diagnosis.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from delayed_diagnosis.proto</summary>
public static partial class DelayedDiagnosisReflection {

  #region Descriptor
  /// <summary>File descriptor for delayed_diagnosis.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static DelayedDiagnosisReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChdkZWxheWVkX2RpYWdub3Npcy5wcm90byJhCgZSZXN1bHQSEgoKYmlhc19j",
          "YWxpYhgBIAEoARIYChB0aW1lX2RlbGF5X2NhbGliGAIgASgBEhEKCWJhbmR3",
          "aWR0aBgDIAEoARIWCg5tZWFuX2NvaGVyZW5jZRgEIAEoASJ9ChZEZWxheWVk",
          "RGlhZ25vc2lzUmVzdWx0EhcKBnN0YXR1cxgBIAEoDjIHLlN0YXR1cxIPCgdt",
          "ZXNzYWdlGAIgASgJEhAKCHByb2dyZXNzGAMgASgBEhwKBnJlc3VsdBgEIAEo",
          "CzIHLlJlc3VsdEgAiAEBQgkKB19yZXN1bHQqVQoGU3RhdHVzEg8KC05PVF9T",
          "VEFSVEVEEAASDwoLSU5fUFJPR1JFU1MQARILCgdTVUNDRVNTEAISCgoGRkFJ",
          "TEVEEAMSEAoMRk9SQ0VfS0lMTEVEEARiBnByb3RvMw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Status), }, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::Result), global::Result.Parser, new[]{ "BiasCalib", "TimeDelayCalib", "Bandwidth", "MeanCoherence" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::DelayedDiagnosisResult), global::DelayedDiagnosisResult.Parser, new[]{ "Status", "Message", "Progress", "Result" }, new[]{ "Result" }, null, null, null)
        }));
  }
  #endregion

}
#region Enums
public enum Status {
  /// <summary>
  /// 未开始
  /// </summary>
  [pbr::OriginalName("NOT_STARTED")] NotStarted = 0,
  /// <summary>
  /// 进行中
  /// </summary>
  [pbr::OriginalName("IN_PROGRESS")] InProgress = 1,
  /// <summary>
  /// 成功
  /// </summary>
  [pbr::OriginalName("SUCCESS")] Success = 2,
  /// <summary>
  /// 失败
  /// </summary>
  [pbr::OriginalName("FAILED")] Failed = 3,
  /// <summary>
  /// 强制停止
  /// </summary>
  [pbr::OriginalName("FORCE_KILLED")] ForceKilled = 4,
}

#endregion

#region Messages
public sealed partial class Result : pb::IMessage<Result>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<Result> _parser = new pb::MessageParser<Result>(() => new Result());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<Result> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::DelayedDiagnosisReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Result() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Result(Result other) : this() {
    biasCalib_ = other.biasCalib_;
    timeDelayCalib_ = other.timeDelayCalib_;
    bandwidth_ = other.bandwidth_;
    meanCoherence_ = other.meanCoherence_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Result Clone() {
    return new Result(this);
  }

  /// <summary>Field number for the "bias_calib" field.</summary>
  public const int BiasCalibFieldNumber = 1;
  private double biasCalib_;
  /// <summary>
  /// FINAL SYSTEM IDENTIFICATION RESULTS 最终系统辨识结果
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public double BiasCalib {
    get { return biasCalib_; }
    set {
      biasCalib_ = value;
    }
  }

  /// <summary>Field number for the "time_delay_calib" field.</summary>
  public const int TimeDelayCalibFieldNumber = 2;
  private double timeDelayCalib_;
  /// <summary>
  /// 时间延迟 (校准): 0.2602s
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public double TimeDelayCalib {
    get { return timeDelayCalib_; }
    set {
      timeDelayCalib_ = value;
    }
  }

  /// <summary>Field number for the "bandwidth" field.</summary>
  public const int BandwidthFieldNumber = 3;
  private double bandwidth_;
  /// <summary>
  /// 带宽 (-3dB): 0.85 Hz
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public double Bandwidth {
    get { return bandwidth_; }
    set {
      bandwidth_ = value;
    }
  }

  /// <summary>Field number for the "mean_coherence" field.</summary>
  public const int MeanCoherenceFieldNumber = 4;
  private double meanCoherence_;
  /// <summary>
  /// 平均相干性: 0.785
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public double MeanCoherence {
    get { return meanCoherence_; }
    set {
      meanCoherence_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as Result);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(Result other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(BiasCalib, other.BiasCalib)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(TimeDelayCalib, other.TimeDelayCalib)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Bandwidth, other.Bandwidth)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(MeanCoherence, other.MeanCoherence)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (BiasCalib != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(BiasCalib);
    if (TimeDelayCalib != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(TimeDelayCalib);
    if (Bandwidth != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Bandwidth);
    if (MeanCoherence != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(MeanCoherence);
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (BiasCalib != 0D) {
      output.WriteRawTag(9);
      output.WriteDouble(BiasCalib);
    }
    if (TimeDelayCalib != 0D) {
      output.WriteRawTag(17);
      output.WriteDouble(TimeDelayCalib);
    }
    if (Bandwidth != 0D) {
      output.WriteRawTag(25);
      output.WriteDouble(Bandwidth);
    }
    if (MeanCoherence != 0D) {
      output.WriteRawTag(33);
      output.WriteDouble(MeanCoherence);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (BiasCalib != 0D) {
      output.WriteRawTag(9);
      output.WriteDouble(BiasCalib);
    }
    if (TimeDelayCalib != 0D) {
      output.WriteRawTag(17);
      output.WriteDouble(TimeDelayCalib);
    }
    if (Bandwidth != 0D) {
      output.WriteRawTag(25);
      output.WriteDouble(Bandwidth);
    }
    if (MeanCoherence != 0D) {
      output.WriteRawTag(33);
      output.WriteDouble(MeanCoherence);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (BiasCalib != 0D) {
      size += 1 + 8;
    }
    if (TimeDelayCalib != 0D) {
      size += 1 + 8;
    }
    if (Bandwidth != 0D) {
      size += 1 + 8;
    }
    if (MeanCoherence != 0D) {
      size += 1 + 8;
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(Result other) {
    if (other == null) {
      return;
    }
    if (other.BiasCalib != 0D) {
      BiasCalib = other.BiasCalib;
    }
    if (other.TimeDelayCalib != 0D) {
      TimeDelayCalib = other.TimeDelayCalib;
    }
    if (other.Bandwidth != 0D) {
      Bandwidth = other.Bandwidth;
    }
    if (other.MeanCoherence != 0D) {
      MeanCoherence = other.MeanCoherence;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 9: {
          BiasCalib = input.ReadDouble();
          break;
        }
        case 17: {
          TimeDelayCalib = input.ReadDouble();
          break;
        }
        case 25: {
          Bandwidth = input.ReadDouble();
          break;
        }
        case 33: {
          MeanCoherence = input.ReadDouble();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 9: {
          BiasCalib = input.ReadDouble();
          break;
        }
        case 17: {
          TimeDelayCalib = input.ReadDouble();
          break;
        }
        case 25: {
          Bandwidth = input.ReadDouble();
          break;
        }
        case 33: {
          MeanCoherence = input.ReadDouble();
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class DelayedDiagnosisResult : pb::IMessage<DelayedDiagnosisResult>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<DelayedDiagnosisResult> _parser = new pb::MessageParser<DelayedDiagnosisResult>(() => new DelayedDiagnosisResult());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<DelayedDiagnosisResult> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::DelayedDiagnosisReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public DelayedDiagnosisResult() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public DelayedDiagnosisResult(DelayedDiagnosisResult other) : this() {
    status_ = other.status_;
    message_ = other.message_;
    progress_ = other.progress_;
    result_ = other.result_ != null ? other.result_.Clone() : null;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public DelayedDiagnosisResult Clone() {
    return new DelayedDiagnosisResult(this);
  }

  /// <summary>Field number for the "status" field.</summary>
  public const int StatusFieldNumber = 1;
  private global::Status status_ = global::Status.NotStarted;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::Status Status {
    get { return status_; }
    set {
      status_ = value;
    }
  }

  /// <summary>Field number for the "message" field.</summary>
  public const int MessageFieldNumber = 2;
  private string message_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Message {
    get { return message_; }
    set {
      message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "progress" field.</summary>
  public const int ProgressFieldNumber = 3;
  private double progress_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public double Progress {
    get { return progress_; }
    set {
      progress_ = value;
    }
  }

  /// <summary>Field number for the "result" field.</summary>
  public const int ResultFieldNumber = 4;
  private global::Result result_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::Result Result {
    get { return result_; }
    set {
      result_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as DelayedDiagnosisResult);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(DelayedDiagnosisResult other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Status != other.Status) return false;
    if (Message != other.Message) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Progress, other.Progress)) return false;
    if (!object.Equals(Result, other.Result)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Status != global::Status.NotStarted) hash ^= Status.GetHashCode();
    if (Message.Length != 0) hash ^= Message.GetHashCode();
    if (Progress != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Progress);
    if (result_ != null) hash ^= Result.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Status != global::Status.NotStarted) {
      output.WriteRawTag(8);
      output.WriteEnum((int) Status);
    }
    if (Message.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Message);
    }
    if (Progress != 0D) {
      output.WriteRawTag(25);
      output.WriteDouble(Progress);
    }
    if (result_ != null) {
      output.WriteRawTag(34);
      output.WriteMessage(Result);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Status != global::Status.NotStarted) {
      output.WriteRawTag(8);
      output.WriteEnum((int) Status);
    }
    if (Message.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Message);
    }
    if (Progress != 0D) {
      output.WriteRawTag(25);
      output.WriteDouble(Progress);
    }
    if (result_ != null) {
      output.WriteRawTag(34);
      output.WriteMessage(Result);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Status != global::Status.NotStarted) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Status);
    }
    if (Message.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Message);
    }
    if (Progress != 0D) {
      size += 1 + 8;
    }
    if (result_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Result);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(DelayedDiagnosisResult other) {
    if (other == null) {
      return;
    }
    if (other.Status != global::Status.NotStarted) {
      Status = other.Status;
    }
    if (other.Message.Length != 0) {
      Message = other.Message;
    }
    if (other.Progress != 0D) {
      Progress = other.Progress;
    }
    if (other.result_ != null) {
      if (result_ == null) {
        Result = new global::Result();
      }
      Result.MergeFrom(other.Result);
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Status = (global::Status) input.ReadEnum();
          break;
        }
        case 18: {
          Message = input.ReadString();
          break;
        }
        case 25: {
          Progress = input.ReadDouble();
          break;
        }
        case 34: {
          if (result_ == null) {
            Result = new global::Result();
          }
          input.ReadMessage(Result);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Status = (global::Status) input.ReadEnum();
          break;
        }
        case 18: {
          Message = input.ReadString();
          break;
        }
        case 25: {
          Progress = input.ReadDouble();
          break;
        }
        case 34: {
          if (result_ == null) {
            Result = new global::Result();
          }
          input.ReadMessage(Result);
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
