{
    "frames": [
        {
            "servos": [
                22.6,
                10,
                0,
                -54.4,
                22.6,
                -10,
                0,
                -54.4,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0
            ],
            "keyframe": 0,
            "attribute": {
                "1": {
                    "CP": [
                        [
                            0,
                            0
                        ],
                        [
                            9,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ]
                },
                "2": {
                    "CP": [
                        [
                            0,
                            0
                        ],
                        [
                            9,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ]
                },
                "3": {
                    "CP": [
                        [
                            0,
                            0
                        ],
                        [
                            9,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ]
                },
                "4": {
                    "CP": [
                        [
                            0,
                            0
                        ],
                        [
                            9,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ]
                },
                "5": {
                    "CP": [
                        [
                            0,
                            0
                        ],
                        [
                            9,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ]
                },
                "6": {
                    "CP": [
                        [
                            0,
                            0
                        ],
                        [
                            9,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ]
                },
                "7": {
                    "CP": [
                        [
                            0,
                            0
                        ],
                        [
                            9,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ]
                },
                "8": {
                    "CP": [
                        [
                            0,
                            0
                        ],
                        [
                            9,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ]
                },
                "9": {
                    "CP": [
                        [
                            0,
                            0
                        ],
                        [
                            9,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ]
                },
                "10": {
                    "CP": [
                        [
                            0,
                            0
                        ],
                        [
                            9,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ]
                },
                "11": {
                    "CP": [
                        [
                            0,
                            0
                        ],
                        [
                            9,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ]
                },
                "12": {
                    "CP": [
                        [
                            0,
                            0
                        ],
                        [
                            9,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ]
                },
                "13": {
                    "CP": [
                        [
                            0,
                            0
                        ],
                        [
                            9,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ]
                },
                "14": {
                    "CP": [
                        [
                            0,
                            0
                        ],
                        [
                            9,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ]
                },
                "15": {
                    "CP": [
                        [
                            0,
                            0
                        ],
                        [
                            9,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ]
                },
                "16": {
                    "CP": [
                        [
                            0,
                            0
                        ],
                        [
                            9,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ]
                },
                "17": {
                    "CP": [
                        [
                            0,
                            0
                        ],
                        [
                            9,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ]
                },
                "18": {
                    "CP": [
                        [
                            0,
                            0
                        ],
                        [
                            9,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ]
                },
                "19": {
                    "CP": [
                        [
                            0,
                            0
                        ],
                        [
                            9,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ]
                },
                "20": {
                    "CP": [
                        [
                            0,
                            0
                        ],
                        [
                            9,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ]
                },
                "21": {
                    "CP": [
                        [
                            0,
                            0
                        ],
                        [
                            9,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ]
                },
                "22": {
                    "CP": [
                        [
                            0,
                            0
                        ],
                        [
                            9,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ]
                },
                "23": {
                    "CP": [
                        [
                            0,
                            0
                        ],
                        [
                            9,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ]
                }
            }
        },
        {
            "servos": [
                0,
                10,
                0,
                0,
                0,
                -10,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0
            ],
            "keyframe": 30,
            "attribute": {
                "1": {
                    "CP": [
                        [
                            -9,
                            0
                        ],
                        [
                            6,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "2": {
                    "CP": [
                        [
                            -9,
                            0
                        ],
                        [
                            6,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "3": {
                    "CP": [
                        [
                            -9,
                            0
                        ],
                        [
                            6,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "4": {
                    "CP": [
                        [
                            -9,
                            0
                        ],
                        [
                            6,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "5": {
                    "CP": [
                        [
                            -9,
                            0
                        ],
                        [
                            6,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "6": {
                    "CP": [
                        [
                            -9,
                            0
                        ],
                        [
                            6,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "7": {
                    "CP": [
                        [
                            -9,
                            0
                        ],
                        [
                            6,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "8": {
                    "CP": [
                        [
                            -9,
                            0
                        ],
                        [
                            6,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "9": {
                    "CP": [
                        [
                            -9,
                            0
                        ],
                        [
                            6,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "10": {
                    "CP": [
                        [
                            -9,
                            0
                        ],
                        [
                            6,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "11": {
                    "CP": [
                        [
                            -9,
                            0
                        ],
                        [
                            6,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "12": {
                    "CP": [
                        [
                            -9,
                            0
                        ],
                        [
                            6,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "13": {
                    "CP": [
                        [
                            -9,
                            0
                        ],
                        [
                            6,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "14": {
                    "CP": [
                        [
                            -9,
                            0
                        ],
                        [
                            6,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "15": {
                    "CP": [
                        [
                            -9,
                            0
                        ],
                        [
                            6,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "16": {
                    "CP": [
                        [
                            -9,
                            0
                        ],
                        [
                            6,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "17": {
                    "CP": [
                        [
                            -9,
                            0
                        ],
                        [
                            6,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "18": {
                    "CP": [
                        [
                            -9,
                            0
                        ],
                        [
                            6,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "19": {
                    "CP": [
                        [
                            -9,
                            0
                        ],
                        [
                            6,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "20": {
                    "CP": [
                        [
                            -9,
                            0
                        ],
                        [
                            6,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "21": {
                    "CP": [
                        [
                            -9,
                            0
                        ],
                        [
                            6,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "22": {
                    "CP": [
                        [
                            -9,
                            0
                        ],
                        [
                            6,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "23": {
                    "CP": [
                        [
                            -9,
                            0
                        ],
                        [
                            6,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                }
            }
        },
        {
            "servos": [
                0,
                10,
                0,
                0,
                0,
                -10,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0
            ],
            "keyframe": 50,
            "attribute": {
                "1": {
                    "CP": [
                        [
                            -6,
                            0
                        ],
                        [
                            45,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "2": {
                    "CP": [
                        [
                            -6,
                            0
                        ],
                        [
                            45,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "3": {
                    "CP": [
                        [
                            -6,
                            0
                        ],
                        [
                            45,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "4": {
                    "CP": [
                        [
                            -6,
                            0
                        ],
                        [
                            45,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "5": {
                    "CP": [
                        [
                            -6,
                            0
                        ],
                        [
                            45,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "6": {
                    "CP": [
                        [
                            -6,
                            0
                        ],
                        [
                            45,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "7": {
                    "CP": [
                        [
                            -6,
                            0
                        ],
                        [
                            45,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "8": {
                    "CP": [
                        [
                            -6,
                            0
                        ],
                        [
                            45,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "9": {
                    "CP": [
                        [
                            -6,
                            0
                        ],
                        [
                            45,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "10": {
                    "CP": [
                        [
                            -6,
                            0
                        ],
                        [
                            45,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "11": {
                    "CP": [
                        [
                            -6,
                            0
                        ],
                        [
                            45,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "12": {
                    "CP": [
                        [
                            -6,
                            0
                        ],
                        [
                            45,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "13": {
                    "CP": [
                        [
                            -6,
                            0
                        ],
                        [
                            45,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "14": {
                    "CP": [
                        [
                            -6,
                            0
                        ],
                        [
                            45,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "15": {
                    "CP": [
                        [
                            -6,
                            0
                        ],
                        [
                            45,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "16": {
                    "CP": [
                        [
                            -6,
                            0
                        ],
                        [
                            45,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "17": {
                    "CP": [
                        [
                            -6,
                            0
                        ],
                        [
                            45,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "18": {
                    "CP": [
                        [
                            -6,
                            0
                        ],
                        [
                            45,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "19": {
                    "CP": [
                        [
                            -6,
                            0
                        ],
                        [
                            45,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "20": {
                    "CP": [
                        [
                            -6,
                            0
                        ],
                        [
                            45,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "21": {
                    "CP": [
                        [
                            -6,
                            0
                        ],
                        [
                            45,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "22": {
                    "CP": [
                        [
                            -6,
                            0
                        ],
                        [
                            45,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "23": {
                    "CP": [
                        [
                            -6,
                            0
                        ],
                        [
                            45,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                }
            }
        },
        {
            "servos": [
                0,
                10,
                0,
                0,
                -140,
                -23,
                55,
                -70,
                0,
                0,
                0,
                0,
                0,
                0,
                25,
                50,
                0,
                0,
                0,
                0,
                0,
                0,
                0
            ],
            "keyframe": 200,
            "attribute": {
                "1": {
                    "CP": [
                        [
                            -45,
                            0
                        ],
                        [
                            30,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "2": {
                    "CP": [
                        [
                            -45,
                            0
                        ],
                        [
                            30,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "3": {
                    "CP": [
                        [
                            -45,
                            0
                        ],
                        [
                            30,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "4": {
                    "CP": [
                        [
                            -45,
                            0
                        ],
                        [
                            30,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "5": {
                    "CP": [
                        [
                            -45,
                            0
                        ],
                        [
                            30,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "6": {
                    "CP": [
                        [
                            -45,
                            0
                        ],
                        [
                            30,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "7": {
                    "CP": [
                        [
                            -45,
                            0
                        ],
                        [
                            30,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "8": {
                    "CP": [
                        [
                            -45,
                            0
                        ],
                        [
                            30,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "9": {
                    "CP": [
                        [
                            -45,
                            0
                        ],
                        [
                            30,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "10": {
                    "CP": [
                        [
                            -45,
                            0
                        ],
                        [
                            30,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "11": {
                    "CP": [
                        [
                            -45,
                            0
                        ],
                        [
                            30,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "12": {
                    "CP": [
                        [
                            -45,
                            0
                        ],
                        [
                            30,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "13": {
                    "CP": [
                        [
                            -45,
                            0
                        ],
                        [
                            30,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "14": {
                    "CP": [
                        [
                            -45,
                            0
                        ],
                        [
                            30,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "15": {
                    "CP": [
                        [
                            -45,
                            0
                        ],
                        [
                            30,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "16": {
                    "CP": [
                        [
                            -45,
                            0
                        ],
                        [
                            30,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "17": {
                    "CP": [
                        [
                            -45,
                            0
                        ],
                        [
                            30,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "18": {
                    "CP": [
                        [
                            -45,
                            0
                        ],
                        [
                            30,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "19": {
                    "CP": [
                        [
                            -45,
                            0
                        ],
                        [
                            30,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "20": {
                    "CP": [
                        [
                            -45,
                            0
                        ],
                        [
                            30,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "21": {
                    "CP": [
                        [
                            -45,
                            0
                        ],
                        [
                            30,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "22": {
                    "CP": [
                        [
                            -45,
                            0
                        ],
                        [
                            30,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "23": {
                    "CP": [
                        [
                            -45,
                            0
                        ],
                        [
                            30,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                }
            }
        },
        {
            "servos": [
                0,
                10,
                0,
                0,
                -140,
                -23,
                55,
                -70,
                0,
                0,
                0,
                0,
                0,
                0,
                25,
                50,
                0,
                0,
                0,
                0,
                0,
                0,
                0
            ],
            "keyframe": 300,
            "attribute": {
                "1": {
                    "CP": [
                        [
                            -30,
                            0
                        ],
                        [
                            15,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "2": {
                    "CP": [
                        [
                            -30,
                            0
                        ],
                        [
                            15,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "3": {
                    "CP": [
                        [
                            -30,
                            0
                        ],
                        [
                            15,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "4": {
                    "CP": [
                        [
                            -30,
                            0
                        ],
                        [
                            15,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "5": {
                    "CP": [
                        [
                            -30,
                            0
                        ],
                        [
                            15,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "6": {
                    "CP": [
                        [
                            -30,
                            0
                        ],
                        [
                            15,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "7": {
                    "CP": [
                        [
                            -30,
                            0
                        ],
                        [
                            15,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "8": {
                    "CP": [
                        [
                            -30,
                            0
                        ],
                        [
                            15,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "9": {
                    "CP": [
                        [
                            -30,
                            0
                        ],
                        [
                            15,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "10": {
                    "CP": [
                        [
                            -30,
                            0
                        ],
                        [
                            15,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "11": {
                    "CP": [
                        [
                            -30,
                            0
                        ],
                        [
                            15,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "12": {
                    "CP": [
                        [
                            -30,
                            0
                        ],
                        [
                            15,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "13": {
                    "CP": [
                        [
                            -30,
                            0
                        ],
                        [
                            15,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "14": {
                    "CP": [
                        [
                            -30,
                            0
                        ],
                        [
                            15,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "15": {
                    "CP": [
                        [
                            -30,
                            0
                        ],
                        [
                            15,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "16": {
                    "CP": [
                        [
                            -30,
                            0
                        ],
                        [
                            15,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "17": {
                    "CP": [
                        [
                            -30,
                            0
                        ],
                        [
                            15,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "18": {
                    "CP": [
                        [
                            -30,
                            0
                        ],
                        [
                            15,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "19": {
                    "CP": [
                        [
                            -30,
                            0
                        ],
                        [
                            15,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "20": {
                    "CP": [
                        [
                            -30,
                            0
                        ],
                        [
                            15,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "21": {
                    "CP": [
                        [
                            -30,
                            0
                        ],
                        [
                            15,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "22": {
                    "CP": [
                        [
                            -30,
                            0
                        ],
                        [
                            15,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "23": {
                    "CP": [
                        [
                            -30,
                            0
                        ],
                        [
                            15,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                }
            }
        },
        {
            "servos": [
                0,
                10,
                0,
                0,
                -140,
                -23,
                55,
                -70,
                0,
                0,
                0,
                0,
                0,
                0,
                25,
                50,
                0,
                0,
                0,
                0,
                0,
                0,
                0
            ],
            "keyframe": 350,
            "attribute": {
                "1": {
                    "CP": [
                        [
                            -15,
                            0
                        ],
                        [
                            48,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "2": {
                    "CP": [
                        [
                            -15,
                            0
                        ],
                        [
                            48,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "3": {
                    "CP": [
                        [
                            -15,
                            0
                        ],
                        [
                            48,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "4": {
                    "CP": [
                        [
                            -15,
                            0
                        ],
                        [
                            48,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "5": {
                    "CP": [
                        [
                            -15,
                            0
                        ],
                        [
                            48,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "6": {
                    "CP": [
                        [
                            -15,
                            0
                        ],
                        [
                            48,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "7": {
                    "CP": [
                        [
                            -15,
                            0
                        ],
                        [
                            48,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "8": {
                    "CP": [
                        [
                            -15,
                            0
                        ],
                        [
                            48,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "9": {
                    "CP": [
                        [
                            -15,
                            0
                        ],
                        [
                            48,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "10": {
                    "CP": [
                        [
                            -15,
                            0
                        ],
                        [
                            48,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "11": {
                    "CP": [
                        [
                            -15,
                            0
                        ],
                        [
                            48,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "12": {
                    "CP": [
                        [
                            -15,
                            0
                        ],
                        [
                            48,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "13": {
                    "CP": [
                        [
                            -15,
                            0
                        ],
                        [
                            48,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "14": {
                    "CP": [
                        [
                            -15,
                            0
                        ],
                        [
                            48,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "15": {
                    "CP": [
                        [
                            -15,
                            0
                        ],
                        [
                            48,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "16": {
                    "CP": [
                        [
                            -15,
                            0
                        ],
                        [
                            48,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "17": {
                    "CP": [
                        [
                            -15,
                            0
                        ],
                        [
                            48,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "18": {
                    "CP": [
                        [
                            -15,
                            0
                        ],
                        [
                            48,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "19": {
                    "CP": [
                        [
                            -15,
                            0
                        ],
                        [
                            48,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "20": {
                    "CP": [
                        [
                            -15,
                            0
                        ],
                        [
                            48,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "21": {
                    "CP": [
                        [
                            -15,
                            0
                        ],
                        [
                            48,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "22": {
                    "CP": [
                        [
                            -15,
                            0
                        ],
                        [
                            48,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "23": {
                    "CP": [
                        [
                            -15,
                            0
                        ],
                        [
                            48,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                }
            }
        },
        {
            "servos": [
                0,
                10,
                0,
                0,
                0,
                -10,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0
            ],
            "keyframe": 510,
            "attribute": {
                "1": {
                    "CP": [
                        [
                            -48,
                            0
                        ],
                        [
                            6,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "2": {
                    "CP": [
                        [
                            -48,
                            0
                        ],
                        [
                            6,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "3": {
                    "CP": [
                        [
                            -48,
                            0
                        ],
                        [
                            6,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "4": {
                    "CP": [
                        [
                            -48,
                            0
                        ],
                        [
                            6,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "5": {
                    "CP": [
                        [
                            -48,
                            0
                        ],
                        [
                            6,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "6": {
                    "CP": [
                        [
                            -48,
                            0
                        ],
                        [
                            6,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "7": {
                    "CP": [
                        [
                            -48,
                            0
                        ],
                        [
                            6,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "8": {
                    "CP": [
                        [
                            -48,
                            0
                        ],
                        [
                            6,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "9": {
                    "CP": [
                        [
                            -48,
                            0
                        ],
                        [
                            6,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "10": {
                    "CP": [
                        [
                            -48,
                            0
                        ],
                        [
                            6,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "11": {
                    "CP": [
                        [
                            -48,
                            0
                        ],
                        [
                            6,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "12": {
                    "CP": [
                        [
                            -48,
                            0
                        ],
                        [
                            6,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "13": {
                    "CP": [
                        [
                            -48,
                            0
                        ],
                        [
                            6,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "14": {
                    "CP": [
                        [
                            -48,
                            0
                        ],
                        [
                            6,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "15": {
                    "CP": [
                        [
                            -48,
                            0
                        ],
                        [
                            6,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "16": {
                    "CP": [
                        [
                            -48,
                            0
                        ],
                        [
                            6,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "17": {
                    "CP": [
                        [
                            -48,
                            0
                        ],
                        [
                            6,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "18": {
                    "CP": [
                        [
                            -48,
                            0
                        ],
                        [
                            6,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "19": {
                    "CP": [
                        [
                            -48,
                            0
                        ],
                        [
                            6,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "20": {
                    "CP": [
                        [
                            -48,
                            0
                        ],
                        [
                            6,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "21": {
                    "CP": [
                        [
                            -48,
                            0
                        ],
                        [
                            6,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "22": {
                    "CP": [
                        [
                            -48,
                            0
                        ],
                        [
                            6,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "23": {
                    "CP": [
                        [
                            -48,
                            0
                        ],
                        [
                            6,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                }
            }
        },
        {
            "servos": [
                0,
                10,
                0,
                0,
                0,
                -10,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0
            ],
            "keyframe": 530,
            "attribute": {
                "1": {
                    "CP": [
                        [
                            -6,
                            0
                        ],
                        [
                            12,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "2": {
                    "CP": [
                        [
                            -6,
                            0
                        ],
                        [
                            12,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "3": {
                    "CP": [
                        [
                            -6,
                            0
                        ],
                        [
                            12,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "4": {
                    "CP": [
                        [
                            -6,
                            0
                        ],
                        [
                            12,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "5": {
                    "CP": [
                        [
                            -6,
                            0
                        ],
                        [
                            12,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "6": {
                    "CP": [
                        [
                            -6,
                            0
                        ],
                        [
                            12,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "7": {
                    "CP": [
                        [
                            -6,
                            0
                        ],
                        [
                            12,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "8": {
                    "CP": [
                        [
                            -6,
                            0
                        ],
                        [
                            12,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "9": {
                    "CP": [
                        [
                            -6,
                            0
                        ],
                        [
                            12,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "10": {
                    "CP": [
                        [
                            -6,
                            0
                        ],
                        [
                            12,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "11": {
                    "CP": [
                        [
                            -6,
                            0
                        ],
                        [
                            12,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "12": {
                    "CP": [
                        [
                            -6,
                            0
                        ],
                        [
                            12,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "13": {
                    "CP": [
                        [
                            -6,
                            0
                        ],
                        [
                            12,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "14": {
                    "CP": [
                        [
                            -6,
                            0
                        ],
                        [
                            12,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "15": {
                    "CP": [
                        [
                            -6,
                            0
                        ],
                        [
                            12,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "16": {
                    "CP": [
                        [
                            -6,
                            0
                        ],
                        [
                            12,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "17": {
                    "CP": [
                        [
                            -6,
                            0
                        ],
                        [
                            12,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "18": {
                    "CP": [
                        [
                            -6,
                            0
                        ],
                        [
                            12,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "19": {
                    "CP": [
                        [
                            -6,
                            0
                        ],
                        [
                            12,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "20": {
                    "CP": [
                        [
                            -6,
                            0
                        ],
                        [
                            12,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "21": {
                    "CP": [
                        [
                            -6,
                            0
                        ],
                        [
                            12,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "22": {
                    "CP": [
                        [
                            -6,
                            0
                        ],
                        [
                            12,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                },
                "23": {
                    "CP": [
                        [
                            -6,
                            0
                        ],
                        [
                            12,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ],
                    "select": false
                }
            }
        },
        {
            "servos": [
                22.6,
                10,
                0,
                -54.4,
                22.6,
                -10,
                0,
                -54.4,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0
            ],
            "keyframe": 570,
            "attribute": {
                "1": {
                    "CP": [
                        [
                            -12,
                            0
                        ],
                        [
                            0,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ]
                },
                "2": {
                    "CP": [
                        [
                            -12,
                            0
                        ],
                        [
                            0,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ]
                },
                "3": {
                    "CP": [
                        [
                            -12,
                            0
                        ],
                        [
                            0,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ]
                },
                "4": {
                    "CP": [
                        [
                            -12,
                            0
                        ],
                        [
                            0,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ]
                },
                "5": {
                    "CP": [
                        [
                            -12,
                            0
                        ],
                        [
                            0,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ]
                },
                "6": {
                    "CP": [
                        [
                            -12,
                            0
                        ],
                        [
                            0,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ]
                },
                "7": {
                    "CP": [
                        [
                            -12,
                            0
                        ],
                        [
                            0,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ]
                },
                "8": {
                    "CP": [
                        [
                            -12,
                            0
                        ],
                        [
                            0,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ]
                },
                "9": {
                    "CP": [
                        [
                            -12,
                            0
                        ],
                        [
                            0,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ]
                },
                "10": {
                    "CP": [
                        [
                            -12,
                            0
                        ],
                        [
                            0,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ]
                },
                "11": {
                    "CP": [
                        [
                            -12,
                            0
                        ],
                        [
                            0,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ]
                },
                "12": {
                    "CP": [
                        [
                            -12,
                            0
                        ],
                        [
                            0,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ]
                },
                "13": {
                    "CP": [
                        [
                            -12,
                            0
                        ],
                        [
                            0,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ]
                },
                "14": {
                    "CP": [
                        [
                            -12,
                            0
                        ],
                        [
                            0,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ]
                },
                "15": {
                    "CP": [
                        [
                            -12,
                            0
                        ],
                        [
                            0,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ]
                },
                "16": {
                    "CP": [
                        [
                            -12,
                            0
                        ],
                        [
                            0,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ]
                },
                "17": {
                    "CP": [
                        [
                            -12,
                            0
                        ],
                        [
                            0,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ]
                },
                "18": {
                    "CP": [
                        [
                            -12,
                            0
                        ],
                        [
                            0,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ]
                },
                "19": {
                    "CP": [
                        [
                            -12,
                            0
                        ],
                        [
                            0,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ]
                },
                "20": {
                    "CP": [
                        [
                            -12,
                            0
                        ],
                        [
                            0,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ]
                },
                "21": {
                    "CP": [
                        [
                            -12,
                            0
                        ],
                        [
                            0,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ]
                },
                "22": {
                    "CP": [
                        [
                            -12,
                            0
                        ],
                        [
                            0,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ]
                },
                "23": {
                    "CP": [
                        [
                            -12,
                            0
                        ],
                        [
                            0,
                            0
                        ]
                    ],
                    "CPType": [
                        "AUTO",
                        "AUTO"
                    ]
                }
            }
        }
    ],
    "musics": [],
    "finish": 571,
    "first": 0,
    "version": "1.2.0-484-g9f60709",
    "robotType": "11"
}