# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/kuavo_vr_events.proto
# Protobuf Python Version: 4.25.4
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cprotos/kuavo_vr_events.proto\"\x8a\x01\n\rKuavoVrEvents\x12\x1c\n\x14webrtc_signaling_url\x18\x01 \x01(\t\x12.\n\x0b\x63\x61mera_info\x18\x02 \x01(\x0b\x32\x19.KuavoVrEvents.CameraInfo\x1a+\n\nCameraInfo\x12\r\n\x05width\x18\x01 \x01(\x05\x12\x0e\n\x06height\x18\x02 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.kuavo_vr_events_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_KUAVOVREVENTS']._serialized_start=33
  _globals['_KUAVOVREVENTS']._serialized_end=171
  _globals['_KUAVOVREVENTS_CAMERAINFO']._serialized_start=128
  _globals['_KUAVOVREVENTS_CAMERAINFO']._serialized_end=171
# @@protoc_insertion_point(module_scope)
