// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hand_pose.proto

#ifndef PROTOBUF_INCLUDED_hand_5fpose_2eproto
#define PROTOBUF_INCLUDED_hand_5fpose_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_hand_5fpose_2eproto 

namespace protobuf_hand_5fpose_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[5];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_hand_5fpose_2eproto
class LejuHandPoseEvent;
class LejuHandPoseEventDefaultTypeInternal;
extern LejuHandPoseEventDefaultTypeInternal _LejuHandPoseEvent_default_instance_;
class LejuHandPoseEvent_Joystick;
class LejuHandPoseEvent_JoystickDefaultTypeInternal;
extern LejuHandPoseEvent_JoystickDefaultTypeInternal _LejuHandPoseEvent_Joystick_default_instance_;
class LejuHandPoseEvent_Pose;
class LejuHandPoseEvent_PoseDefaultTypeInternal;
extern LejuHandPoseEvent_PoseDefaultTypeInternal _LejuHandPoseEvent_Pose_default_instance_;
class LejuHandPoseEvent_Pose_Position;
class LejuHandPoseEvent_Pose_PositionDefaultTypeInternal;
extern LejuHandPoseEvent_Pose_PositionDefaultTypeInternal _LejuHandPoseEvent_Pose_Position_default_instance_;
class LejuHandPoseEvent_Pose_Quaternion;
class LejuHandPoseEvent_Pose_QuaternionDefaultTypeInternal;
extern LejuHandPoseEvent_Pose_QuaternionDefaultTypeInternal _LejuHandPoseEvent_Pose_Quaternion_default_instance_;
namespace google {
namespace protobuf {
template<> ::LejuHandPoseEvent* Arena::CreateMaybeMessage<::LejuHandPoseEvent>(Arena*);
template<> ::LejuHandPoseEvent_Joystick* Arena::CreateMaybeMessage<::LejuHandPoseEvent_Joystick>(Arena*);
template<> ::LejuHandPoseEvent_Pose* Arena::CreateMaybeMessage<::LejuHandPoseEvent_Pose>(Arena*);
template<> ::LejuHandPoseEvent_Pose_Position* Arena::CreateMaybeMessage<::LejuHandPoseEvent_Pose_Position>(Arena*);
template<> ::LejuHandPoseEvent_Pose_Quaternion* Arena::CreateMaybeMessage<::LejuHandPoseEvent_Pose_Quaternion>(Arena*);
}  // namespace protobuf
}  // namespace google

// ===================================================================

class LejuHandPoseEvent_Pose_Position : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:LejuHandPoseEvent.Pose.Position) */ {
 public:
  LejuHandPoseEvent_Pose_Position();
  virtual ~LejuHandPoseEvent_Pose_Position();

  LejuHandPoseEvent_Pose_Position(const LejuHandPoseEvent_Pose_Position& from);

  inline LejuHandPoseEvent_Pose_Position& operator=(const LejuHandPoseEvent_Pose_Position& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  LejuHandPoseEvent_Pose_Position(LejuHandPoseEvent_Pose_Position&& from) noexcept
    : LejuHandPoseEvent_Pose_Position() {
    *this = ::std::move(from);
  }

  inline LejuHandPoseEvent_Pose_Position& operator=(LejuHandPoseEvent_Pose_Position&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const LejuHandPoseEvent_Pose_Position& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const LejuHandPoseEvent_Pose_Position* internal_default_instance() {
    return reinterpret_cast<const LejuHandPoseEvent_Pose_Position*>(
               &_LejuHandPoseEvent_Pose_Position_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(LejuHandPoseEvent_Pose_Position* other);
  friend void swap(LejuHandPoseEvent_Pose_Position& a, LejuHandPoseEvent_Pose_Position& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline LejuHandPoseEvent_Pose_Position* New() const final {
    return CreateMaybeMessage<LejuHandPoseEvent_Pose_Position>(NULL);
  }

  LejuHandPoseEvent_Pose_Position* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<LejuHandPoseEvent_Pose_Position>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const LejuHandPoseEvent_Pose_Position& from);
  void MergeFrom(const LejuHandPoseEvent_Pose_Position& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LejuHandPoseEvent_Pose_Position* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // float x = 1;
  void clear_x();
  static const int kXFieldNumber = 1;
  float x() const;
  void set_x(float value);

  // float y = 2;
  void clear_y();
  static const int kYFieldNumber = 2;
  float y() const;
  void set_y(float value);

  // float z = 3;
  void clear_z();
  static const int kZFieldNumber = 3;
  float z() const;
  void set_z(float value);

  // @@protoc_insertion_point(class_scope:LejuHandPoseEvent.Pose.Position)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  float x_;
  float y_;
  float z_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_hand_5fpose_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class LejuHandPoseEvent_Pose_Quaternion : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:LejuHandPoseEvent.Pose.Quaternion) */ {
 public:
  LejuHandPoseEvent_Pose_Quaternion();
  virtual ~LejuHandPoseEvent_Pose_Quaternion();

  LejuHandPoseEvent_Pose_Quaternion(const LejuHandPoseEvent_Pose_Quaternion& from);

  inline LejuHandPoseEvent_Pose_Quaternion& operator=(const LejuHandPoseEvent_Pose_Quaternion& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  LejuHandPoseEvent_Pose_Quaternion(LejuHandPoseEvent_Pose_Quaternion&& from) noexcept
    : LejuHandPoseEvent_Pose_Quaternion() {
    *this = ::std::move(from);
  }

  inline LejuHandPoseEvent_Pose_Quaternion& operator=(LejuHandPoseEvent_Pose_Quaternion&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const LejuHandPoseEvent_Pose_Quaternion& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const LejuHandPoseEvent_Pose_Quaternion* internal_default_instance() {
    return reinterpret_cast<const LejuHandPoseEvent_Pose_Quaternion*>(
               &_LejuHandPoseEvent_Pose_Quaternion_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(LejuHandPoseEvent_Pose_Quaternion* other);
  friend void swap(LejuHandPoseEvent_Pose_Quaternion& a, LejuHandPoseEvent_Pose_Quaternion& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline LejuHandPoseEvent_Pose_Quaternion* New() const final {
    return CreateMaybeMessage<LejuHandPoseEvent_Pose_Quaternion>(NULL);
  }

  LejuHandPoseEvent_Pose_Quaternion* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<LejuHandPoseEvent_Pose_Quaternion>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const LejuHandPoseEvent_Pose_Quaternion& from);
  void MergeFrom(const LejuHandPoseEvent_Pose_Quaternion& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LejuHandPoseEvent_Pose_Quaternion* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // float x = 1;
  void clear_x();
  static const int kXFieldNumber = 1;
  float x() const;
  void set_x(float value);

  // float y = 2;
  void clear_y();
  static const int kYFieldNumber = 2;
  float y() const;
  void set_y(float value);

  // float z = 3;
  void clear_z();
  static const int kZFieldNumber = 3;
  float z() const;
  void set_z(float value);

  // float w = 4;
  void clear_w();
  static const int kWFieldNumber = 4;
  float w() const;
  void set_w(float value);

  // @@protoc_insertion_point(class_scope:LejuHandPoseEvent.Pose.Quaternion)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  float x_;
  float y_;
  float z_;
  float w_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_hand_5fpose_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class LejuHandPoseEvent_Pose : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:LejuHandPoseEvent.Pose) */ {
 public:
  LejuHandPoseEvent_Pose();
  virtual ~LejuHandPoseEvent_Pose();

  LejuHandPoseEvent_Pose(const LejuHandPoseEvent_Pose& from);

  inline LejuHandPoseEvent_Pose& operator=(const LejuHandPoseEvent_Pose& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  LejuHandPoseEvent_Pose(LejuHandPoseEvent_Pose&& from) noexcept
    : LejuHandPoseEvent_Pose() {
    *this = ::std::move(from);
  }

  inline LejuHandPoseEvent_Pose& operator=(LejuHandPoseEvent_Pose&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const LejuHandPoseEvent_Pose& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const LejuHandPoseEvent_Pose* internal_default_instance() {
    return reinterpret_cast<const LejuHandPoseEvent_Pose*>(
               &_LejuHandPoseEvent_Pose_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(LejuHandPoseEvent_Pose* other);
  friend void swap(LejuHandPoseEvent_Pose& a, LejuHandPoseEvent_Pose& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline LejuHandPoseEvent_Pose* New() const final {
    return CreateMaybeMessage<LejuHandPoseEvent_Pose>(NULL);
  }

  LejuHandPoseEvent_Pose* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<LejuHandPoseEvent_Pose>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const LejuHandPoseEvent_Pose& from);
  void MergeFrom(const LejuHandPoseEvent_Pose& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LejuHandPoseEvent_Pose* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef LejuHandPoseEvent_Pose_Position Position;
  typedef LejuHandPoseEvent_Pose_Quaternion Quaternion;

  // accessors -------------------------------------------------------

  // .LejuHandPoseEvent.Pose.Position position = 1;
  bool has_position() const;
  void clear_position();
  static const int kPositionFieldNumber = 1;
  private:
  const ::LejuHandPoseEvent_Pose_Position& _internal_position() const;
  public:
  const ::LejuHandPoseEvent_Pose_Position& position() const;
  ::LejuHandPoseEvent_Pose_Position* release_position();
  ::LejuHandPoseEvent_Pose_Position* mutable_position();
  void set_allocated_position(::LejuHandPoseEvent_Pose_Position* position);

  // .LejuHandPoseEvent.Pose.Quaternion quaternion = 2;
  bool has_quaternion() const;
  void clear_quaternion();
  static const int kQuaternionFieldNumber = 2;
  private:
  const ::LejuHandPoseEvent_Pose_Quaternion& _internal_quaternion() const;
  public:
  const ::LejuHandPoseEvent_Pose_Quaternion& quaternion() const;
  ::LejuHandPoseEvent_Pose_Quaternion* release_quaternion();
  ::LejuHandPoseEvent_Pose_Quaternion* mutable_quaternion();
  void set_allocated_quaternion(::LejuHandPoseEvent_Pose_Quaternion* quaternion);

  // @@protoc_insertion_point(class_scope:LejuHandPoseEvent.Pose)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::LejuHandPoseEvent_Pose_Position* position_;
  ::LejuHandPoseEvent_Pose_Quaternion* quaternion_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_hand_5fpose_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class LejuHandPoseEvent_Joystick : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:LejuHandPoseEvent.Joystick) */ {
 public:
  LejuHandPoseEvent_Joystick();
  virtual ~LejuHandPoseEvent_Joystick();

  LejuHandPoseEvent_Joystick(const LejuHandPoseEvent_Joystick& from);

  inline LejuHandPoseEvent_Joystick& operator=(const LejuHandPoseEvent_Joystick& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  LejuHandPoseEvent_Joystick(LejuHandPoseEvent_Joystick&& from) noexcept
    : LejuHandPoseEvent_Joystick() {
    *this = ::std::move(from);
  }

  inline LejuHandPoseEvent_Joystick& operator=(LejuHandPoseEvent_Joystick&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const LejuHandPoseEvent_Joystick& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const LejuHandPoseEvent_Joystick* internal_default_instance() {
    return reinterpret_cast<const LejuHandPoseEvent_Joystick*>(
               &_LejuHandPoseEvent_Joystick_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  void Swap(LejuHandPoseEvent_Joystick* other);
  friend void swap(LejuHandPoseEvent_Joystick& a, LejuHandPoseEvent_Joystick& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline LejuHandPoseEvent_Joystick* New() const final {
    return CreateMaybeMessage<LejuHandPoseEvent_Joystick>(NULL);
  }

  LejuHandPoseEvent_Joystick* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<LejuHandPoseEvent_Joystick>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const LejuHandPoseEvent_Joystick& from);
  void MergeFrom(const LejuHandPoseEvent_Joystick& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LejuHandPoseEvent_Joystick* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // float x = 1;
  void clear_x();
  static const int kXFieldNumber = 1;
  float x() const;
  void set_x(float value);

  // float y = 2;
  void clear_y();
  static const int kYFieldNumber = 2;
  float y() const;
  void set_y(float value);

  // float trigger = 3;
  void clear_trigger();
  static const int kTriggerFieldNumber = 3;
  float trigger() const;
  void set_trigger(float value);

  // float grip = 4;
  void clear_grip();
  static const int kGripFieldNumber = 4;
  float grip() const;
  void set_grip(float value);

  // bool firstButtonPressed = 5;
  void clear_firstbuttonpressed();
  static const int kFirstButtonPressedFieldNumber = 5;
  bool firstbuttonpressed() const;
  void set_firstbuttonpressed(bool value);

  // bool secondButtonPressed = 6;
  void clear_secondbuttonpressed();
  static const int kSecondButtonPressedFieldNumber = 6;
  bool secondbuttonpressed() const;
  void set_secondbuttonpressed(bool value);

  // bool firstButtonTouched = 7;
  void clear_firstbuttontouched();
  static const int kFirstButtonTouchedFieldNumber = 7;
  bool firstbuttontouched() const;
  void set_firstbuttontouched(bool value);

  // bool secondButtonTouched = 8;
  void clear_secondbuttontouched();
  static const int kSecondButtonTouchedFieldNumber = 8;
  bool secondbuttontouched() const;
  void set_secondbuttontouched(bool value);

  // @@protoc_insertion_point(class_scope:LejuHandPoseEvent.Joystick)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  float x_;
  float y_;
  float trigger_;
  float grip_;
  bool firstbuttonpressed_;
  bool secondbuttonpressed_;
  bool firstbuttontouched_;
  bool secondbuttontouched_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_hand_5fpose_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class LejuHandPoseEvent : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:LejuHandPoseEvent) */ {
 public:
  LejuHandPoseEvent();
  virtual ~LejuHandPoseEvent();

  LejuHandPoseEvent(const LejuHandPoseEvent& from);

  inline LejuHandPoseEvent& operator=(const LejuHandPoseEvent& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  LejuHandPoseEvent(LejuHandPoseEvent&& from) noexcept
    : LejuHandPoseEvent() {
    *this = ::std::move(from);
  }

  inline LejuHandPoseEvent& operator=(LejuHandPoseEvent&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const LejuHandPoseEvent& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const LejuHandPoseEvent* internal_default_instance() {
    return reinterpret_cast<const LejuHandPoseEvent*>(
               &_LejuHandPoseEvent_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  void Swap(LejuHandPoseEvent* other);
  friend void swap(LejuHandPoseEvent& a, LejuHandPoseEvent& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline LejuHandPoseEvent* New() const final {
    return CreateMaybeMessage<LejuHandPoseEvent>(NULL);
  }

  LejuHandPoseEvent* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<LejuHandPoseEvent>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const LejuHandPoseEvent& from);
  void MergeFrom(const LejuHandPoseEvent& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LejuHandPoseEvent* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef LejuHandPoseEvent_Pose Pose;
  typedef LejuHandPoseEvent_Joystick Joystick;

  // accessors -------------------------------------------------------

  // repeated .LejuHandPoseEvent.Pose poses = 2;
  int poses_size() const;
  void clear_poses();
  static const int kPosesFieldNumber = 2;
  ::LejuHandPoseEvent_Pose* mutable_poses(int index);
  ::google::protobuf::RepeatedPtrField< ::LejuHandPoseEvent_Pose >*
      mutable_poses();
  const ::LejuHandPoseEvent_Pose& poses(int index) const;
  ::LejuHandPoseEvent_Pose* add_poses();
  const ::google::protobuf::RepeatedPtrField< ::LejuHandPoseEvent_Pose >&
      poses() const;

  // .LejuHandPoseEvent.Joystick left_joystick = 5;
  bool has_left_joystick() const;
  void clear_left_joystick();
  static const int kLeftJoystickFieldNumber = 5;
  private:
  const ::LejuHandPoseEvent_Joystick& _internal_left_joystick() const;
  public:
  const ::LejuHandPoseEvent_Joystick& left_joystick() const;
  ::LejuHandPoseEvent_Joystick* release_left_joystick();
  ::LejuHandPoseEvent_Joystick* mutable_left_joystick();
  void set_allocated_left_joystick(::LejuHandPoseEvent_Joystick* left_joystick);

  // .LejuHandPoseEvent.Joystick right_joystick = 6;
  bool has_right_joystick() const;
  void clear_right_joystick();
  static const int kRightJoystickFieldNumber = 6;
  private:
  const ::LejuHandPoseEvent_Joystick& _internal_right_joystick() const;
  public:
  const ::LejuHandPoseEvent_Joystick& right_joystick() const;
  ::LejuHandPoseEvent_Joystick* release_right_joystick();
  ::LejuHandPoseEvent_Joystick* mutable_right_joystick();
  void set_allocated_right_joystick(::LejuHandPoseEvent_Joystick* right_joystick);

  // int64 timestamp = 1;
  void clear_timestamp();
  static const int kTimestampFieldNumber = 1;
  ::google::protobuf::int64 timestamp() const;
  void set_timestamp(::google::protobuf::int64 value);

  // bool IsDataHighConfidence = 3;
  void clear_isdatahighconfidence();
  static const int kIsDataHighConfidenceFieldNumber = 3;
  bool isdatahighconfidence() const;
  void set_isdatahighconfidence(bool value);

  // bool IsHandTracking = 4;
  void clear_ishandtracking();
  static const int kIsHandTrackingFieldNumber = 4;
  bool ishandtracking() const;
  void set_ishandtracking(bool value);

  // @@protoc_insertion_point(class_scope:LejuHandPoseEvent)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::LejuHandPoseEvent_Pose > poses_;
  ::LejuHandPoseEvent_Joystick* left_joystick_;
  ::LejuHandPoseEvent_Joystick* right_joystick_;
  ::google::protobuf::int64 timestamp_;
  bool isdatahighconfidence_;
  bool ishandtracking_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_hand_5fpose_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// LejuHandPoseEvent_Pose_Position

// float x = 1;
inline void LejuHandPoseEvent_Pose_Position::clear_x() {
  x_ = 0;
}
inline float LejuHandPoseEvent_Pose_Position::x() const {
  // @@protoc_insertion_point(field_get:LejuHandPoseEvent.Pose.Position.x)
  return x_;
}
inline void LejuHandPoseEvent_Pose_Position::set_x(float value) {
  
  x_ = value;
  // @@protoc_insertion_point(field_set:LejuHandPoseEvent.Pose.Position.x)
}

// float y = 2;
inline void LejuHandPoseEvent_Pose_Position::clear_y() {
  y_ = 0;
}
inline float LejuHandPoseEvent_Pose_Position::y() const {
  // @@protoc_insertion_point(field_get:LejuHandPoseEvent.Pose.Position.y)
  return y_;
}
inline void LejuHandPoseEvent_Pose_Position::set_y(float value) {
  
  y_ = value;
  // @@protoc_insertion_point(field_set:LejuHandPoseEvent.Pose.Position.y)
}

// float z = 3;
inline void LejuHandPoseEvent_Pose_Position::clear_z() {
  z_ = 0;
}
inline float LejuHandPoseEvent_Pose_Position::z() const {
  // @@protoc_insertion_point(field_get:LejuHandPoseEvent.Pose.Position.z)
  return z_;
}
inline void LejuHandPoseEvent_Pose_Position::set_z(float value) {
  
  z_ = value;
  // @@protoc_insertion_point(field_set:LejuHandPoseEvent.Pose.Position.z)
}

// -------------------------------------------------------------------

// LejuHandPoseEvent_Pose_Quaternion

// float x = 1;
inline void LejuHandPoseEvent_Pose_Quaternion::clear_x() {
  x_ = 0;
}
inline float LejuHandPoseEvent_Pose_Quaternion::x() const {
  // @@protoc_insertion_point(field_get:LejuHandPoseEvent.Pose.Quaternion.x)
  return x_;
}
inline void LejuHandPoseEvent_Pose_Quaternion::set_x(float value) {
  
  x_ = value;
  // @@protoc_insertion_point(field_set:LejuHandPoseEvent.Pose.Quaternion.x)
}

// float y = 2;
inline void LejuHandPoseEvent_Pose_Quaternion::clear_y() {
  y_ = 0;
}
inline float LejuHandPoseEvent_Pose_Quaternion::y() const {
  // @@protoc_insertion_point(field_get:LejuHandPoseEvent.Pose.Quaternion.y)
  return y_;
}
inline void LejuHandPoseEvent_Pose_Quaternion::set_y(float value) {
  
  y_ = value;
  // @@protoc_insertion_point(field_set:LejuHandPoseEvent.Pose.Quaternion.y)
}

// float z = 3;
inline void LejuHandPoseEvent_Pose_Quaternion::clear_z() {
  z_ = 0;
}
inline float LejuHandPoseEvent_Pose_Quaternion::z() const {
  // @@protoc_insertion_point(field_get:LejuHandPoseEvent.Pose.Quaternion.z)
  return z_;
}
inline void LejuHandPoseEvent_Pose_Quaternion::set_z(float value) {
  
  z_ = value;
  // @@protoc_insertion_point(field_set:LejuHandPoseEvent.Pose.Quaternion.z)
}

// float w = 4;
inline void LejuHandPoseEvent_Pose_Quaternion::clear_w() {
  w_ = 0;
}
inline float LejuHandPoseEvent_Pose_Quaternion::w() const {
  // @@protoc_insertion_point(field_get:LejuHandPoseEvent.Pose.Quaternion.w)
  return w_;
}
inline void LejuHandPoseEvent_Pose_Quaternion::set_w(float value) {
  
  w_ = value;
  // @@protoc_insertion_point(field_set:LejuHandPoseEvent.Pose.Quaternion.w)
}

// -------------------------------------------------------------------

// LejuHandPoseEvent_Pose

// .LejuHandPoseEvent.Pose.Position position = 1;
inline bool LejuHandPoseEvent_Pose::has_position() const {
  return this != internal_default_instance() && position_ != NULL;
}
inline void LejuHandPoseEvent_Pose::clear_position() {
  if (GetArenaNoVirtual() == NULL && position_ != NULL) {
    delete position_;
  }
  position_ = NULL;
}
inline const ::LejuHandPoseEvent_Pose_Position& LejuHandPoseEvent_Pose::_internal_position() const {
  return *position_;
}
inline const ::LejuHandPoseEvent_Pose_Position& LejuHandPoseEvent_Pose::position() const {
  const ::LejuHandPoseEvent_Pose_Position* p = position_;
  // @@protoc_insertion_point(field_get:LejuHandPoseEvent.Pose.position)
  return p != NULL ? *p : *reinterpret_cast<const ::LejuHandPoseEvent_Pose_Position*>(
      &::_LejuHandPoseEvent_Pose_Position_default_instance_);
}
inline ::LejuHandPoseEvent_Pose_Position* LejuHandPoseEvent_Pose::release_position() {
  // @@protoc_insertion_point(field_release:LejuHandPoseEvent.Pose.position)
  
  ::LejuHandPoseEvent_Pose_Position* temp = position_;
  position_ = NULL;
  return temp;
}
inline ::LejuHandPoseEvent_Pose_Position* LejuHandPoseEvent_Pose::mutable_position() {
  
  if (position_ == NULL) {
    auto* p = CreateMaybeMessage<::LejuHandPoseEvent_Pose_Position>(GetArenaNoVirtual());
    position_ = p;
  }
  // @@protoc_insertion_point(field_mutable:LejuHandPoseEvent.Pose.position)
  return position_;
}
inline void LejuHandPoseEvent_Pose::set_allocated_position(::LejuHandPoseEvent_Pose_Position* position) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete position_;
  }
  if (position) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      position = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, position, submessage_arena);
    }
    
  } else {
    
  }
  position_ = position;
  // @@protoc_insertion_point(field_set_allocated:LejuHandPoseEvent.Pose.position)
}

// .LejuHandPoseEvent.Pose.Quaternion quaternion = 2;
inline bool LejuHandPoseEvent_Pose::has_quaternion() const {
  return this != internal_default_instance() && quaternion_ != NULL;
}
inline void LejuHandPoseEvent_Pose::clear_quaternion() {
  if (GetArenaNoVirtual() == NULL && quaternion_ != NULL) {
    delete quaternion_;
  }
  quaternion_ = NULL;
}
inline const ::LejuHandPoseEvent_Pose_Quaternion& LejuHandPoseEvent_Pose::_internal_quaternion() const {
  return *quaternion_;
}
inline const ::LejuHandPoseEvent_Pose_Quaternion& LejuHandPoseEvent_Pose::quaternion() const {
  const ::LejuHandPoseEvent_Pose_Quaternion* p = quaternion_;
  // @@protoc_insertion_point(field_get:LejuHandPoseEvent.Pose.quaternion)
  return p != NULL ? *p : *reinterpret_cast<const ::LejuHandPoseEvent_Pose_Quaternion*>(
      &::_LejuHandPoseEvent_Pose_Quaternion_default_instance_);
}
inline ::LejuHandPoseEvent_Pose_Quaternion* LejuHandPoseEvent_Pose::release_quaternion() {
  // @@protoc_insertion_point(field_release:LejuHandPoseEvent.Pose.quaternion)
  
  ::LejuHandPoseEvent_Pose_Quaternion* temp = quaternion_;
  quaternion_ = NULL;
  return temp;
}
inline ::LejuHandPoseEvent_Pose_Quaternion* LejuHandPoseEvent_Pose::mutable_quaternion() {
  
  if (quaternion_ == NULL) {
    auto* p = CreateMaybeMessage<::LejuHandPoseEvent_Pose_Quaternion>(GetArenaNoVirtual());
    quaternion_ = p;
  }
  // @@protoc_insertion_point(field_mutable:LejuHandPoseEvent.Pose.quaternion)
  return quaternion_;
}
inline void LejuHandPoseEvent_Pose::set_allocated_quaternion(::LejuHandPoseEvent_Pose_Quaternion* quaternion) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete quaternion_;
  }
  if (quaternion) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      quaternion = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, quaternion, submessage_arena);
    }
    
  } else {
    
  }
  quaternion_ = quaternion;
  // @@protoc_insertion_point(field_set_allocated:LejuHandPoseEvent.Pose.quaternion)
}

// -------------------------------------------------------------------

// LejuHandPoseEvent_Joystick

// float x = 1;
inline void LejuHandPoseEvent_Joystick::clear_x() {
  x_ = 0;
}
inline float LejuHandPoseEvent_Joystick::x() const {
  // @@protoc_insertion_point(field_get:LejuHandPoseEvent.Joystick.x)
  return x_;
}
inline void LejuHandPoseEvent_Joystick::set_x(float value) {
  
  x_ = value;
  // @@protoc_insertion_point(field_set:LejuHandPoseEvent.Joystick.x)
}

// float y = 2;
inline void LejuHandPoseEvent_Joystick::clear_y() {
  y_ = 0;
}
inline float LejuHandPoseEvent_Joystick::y() const {
  // @@protoc_insertion_point(field_get:LejuHandPoseEvent.Joystick.y)
  return y_;
}
inline void LejuHandPoseEvent_Joystick::set_y(float value) {
  
  y_ = value;
  // @@protoc_insertion_point(field_set:LejuHandPoseEvent.Joystick.y)
}

// float trigger = 3;
inline void LejuHandPoseEvent_Joystick::clear_trigger() {
  trigger_ = 0;
}
inline float LejuHandPoseEvent_Joystick::trigger() const {
  // @@protoc_insertion_point(field_get:LejuHandPoseEvent.Joystick.trigger)
  return trigger_;
}
inline void LejuHandPoseEvent_Joystick::set_trigger(float value) {
  
  trigger_ = value;
  // @@protoc_insertion_point(field_set:LejuHandPoseEvent.Joystick.trigger)
}

// float grip = 4;
inline void LejuHandPoseEvent_Joystick::clear_grip() {
  grip_ = 0;
}
inline float LejuHandPoseEvent_Joystick::grip() const {
  // @@protoc_insertion_point(field_get:LejuHandPoseEvent.Joystick.grip)
  return grip_;
}
inline void LejuHandPoseEvent_Joystick::set_grip(float value) {
  
  grip_ = value;
  // @@protoc_insertion_point(field_set:LejuHandPoseEvent.Joystick.grip)
}

// bool firstButtonPressed = 5;
inline void LejuHandPoseEvent_Joystick::clear_firstbuttonpressed() {
  firstbuttonpressed_ = false;
}
inline bool LejuHandPoseEvent_Joystick::firstbuttonpressed() const {
  // @@protoc_insertion_point(field_get:LejuHandPoseEvent.Joystick.firstButtonPressed)
  return firstbuttonpressed_;
}
inline void LejuHandPoseEvent_Joystick::set_firstbuttonpressed(bool value) {
  
  firstbuttonpressed_ = value;
  // @@protoc_insertion_point(field_set:LejuHandPoseEvent.Joystick.firstButtonPressed)
}

// bool secondButtonPressed = 6;
inline void LejuHandPoseEvent_Joystick::clear_secondbuttonpressed() {
  secondbuttonpressed_ = false;
}
inline bool LejuHandPoseEvent_Joystick::secondbuttonpressed() const {
  // @@protoc_insertion_point(field_get:LejuHandPoseEvent.Joystick.secondButtonPressed)
  return secondbuttonpressed_;
}
inline void LejuHandPoseEvent_Joystick::set_secondbuttonpressed(bool value) {
  
  secondbuttonpressed_ = value;
  // @@protoc_insertion_point(field_set:LejuHandPoseEvent.Joystick.secondButtonPressed)
}

// bool firstButtonTouched = 7;
inline void LejuHandPoseEvent_Joystick::clear_firstbuttontouched() {
  firstbuttontouched_ = false;
}
inline bool LejuHandPoseEvent_Joystick::firstbuttontouched() const {
  // @@protoc_insertion_point(field_get:LejuHandPoseEvent.Joystick.firstButtonTouched)
  return firstbuttontouched_;
}
inline void LejuHandPoseEvent_Joystick::set_firstbuttontouched(bool value) {
  
  firstbuttontouched_ = value;
  // @@protoc_insertion_point(field_set:LejuHandPoseEvent.Joystick.firstButtonTouched)
}

// bool secondButtonTouched = 8;
inline void LejuHandPoseEvent_Joystick::clear_secondbuttontouched() {
  secondbuttontouched_ = false;
}
inline bool LejuHandPoseEvent_Joystick::secondbuttontouched() const {
  // @@protoc_insertion_point(field_get:LejuHandPoseEvent.Joystick.secondButtonTouched)
  return secondbuttontouched_;
}
inline void LejuHandPoseEvent_Joystick::set_secondbuttontouched(bool value) {
  
  secondbuttontouched_ = value;
  // @@protoc_insertion_point(field_set:LejuHandPoseEvent.Joystick.secondButtonTouched)
}

// -------------------------------------------------------------------

// LejuHandPoseEvent

// int64 timestamp = 1;
inline void LejuHandPoseEvent::clear_timestamp() {
  timestamp_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 LejuHandPoseEvent::timestamp() const {
  // @@protoc_insertion_point(field_get:LejuHandPoseEvent.timestamp)
  return timestamp_;
}
inline void LejuHandPoseEvent::set_timestamp(::google::protobuf::int64 value) {
  
  timestamp_ = value;
  // @@protoc_insertion_point(field_set:LejuHandPoseEvent.timestamp)
}

// repeated .LejuHandPoseEvent.Pose poses = 2;
inline int LejuHandPoseEvent::poses_size() const {
  return poses_.size();
}
inline void LejuHandPoseEvent::clear_poses() {
  poses_.Clear();
}
inline ::LejuHandPoseEvent_Pose* LejuHandPoseEvent::mutable_poses(int index) {
  // @@protoc_insertion_point(field_mutable:LejuHandPoseEvent.poses)
  return poses_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::LejuHandPoseEvent_Pose >*
LejuHandPoseEvent::mutable_poses() {
  // @@protoc_insertion_point(field_mutable_list:LejuHandPoseEvent.poses)
  return &poses_;
}
inline const ::LejuHandPoseEvent_Pose& LejuHandPoseEvent::poses(int index) const {
  // @@protoc_insertion_point(field_get:LejuHandPoseEvent.poses)
  return poses_.Get(index);
}
inline ::LejuHandPoseEvent_Pose* LejuHandPoseEvent::add_poses() {
  // @@protoc_insertion_point(field_add:LejuHandPoseEvent.poses)
  return poses_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::LejuHandPoseEvent_Pose >&
LejuHandPoseEvent::poses() const {
  // @@protoc_insertion_point(field_list:LejuHandPoseEvent.poses)
  return poses_;
}

// bool IsDataHighConfidence = 3;
inline void LejuHandPoseEvent::clear_isdatahighconfidence() {
  isdatahighconfidence_ = false;
}
inline bool LejuHandPoseEvent::isdatahighconfidence() const {
  // @@protoc_insertion_point(field_get:LejuHandPoseEvent.IsDataHighConfidence)
  return isdatahighconfidence_;
}
inline void LejuHandPoseEvent::set_isdatahighconfidence(bool value) {
  
  isdatahighconfidence_ = value;
  // @@protoc_insertion_point(field_set:LejuHandPoseEvent.IsDataHighConfidence)
}

// bool IsHandTracking = 4;
inline void LejuHandPoseEvent::clear_ishandtracking() {
  ishandtracking_ = false;
}
inline bool LejuHandPoseEvent::ishandtracking() const {
  // @@protoc_insertion_point(field_get:LejuHandPoseEvent.IsHandTracking)
  return ishandtracking_;
}
inline void LejuHandPoseEvent::set_ishandtracking(bool value) {
  
  ishandtracking_ = value;
  // @@protoc_insertion_point(field_set:LejuHandPoseEvent.IsHandTracking)
}

// .LejuHandPoseEvent.Joystick left_joystick = 5;
inline bool LejuHandPoseEvent::has_left_joystick() const {
  return this != internal_default_instance() && left_joystick_ != NULL;
}
inline void LejuHandPoseEvent::clear_left_joystick() {
  if (GetArenaNoVirtual() == NULL && left_joystick_ != NULL) {
    delete left_joystick_;
  }
  left_joystick_ = NULL;
}
inline const ::LejuHandPoseEvent_Joystick& LejuHandPoseEvent::_internal_left_joystick() const {
  return *left_joystick_;
}
inline const ::LejuHandPoseEvent_Joystick& LejuHandPoseEvent::left_joystick() const {
  const ::LejuHandPoseEvent_Joystick* p = left_joystick_;
  // @@protoc_insertion_point(field_get:LejuHandPoseEvent.left_joystick)
  return p != NULL ? *p : *reinterpret_cast<const ::LejuHandPoseEvent_Joystick*>(
      &::_LejuHandPoseEvent_Joystick_default_instance_);
}
inline ::LejuHandPoseEvent_Joystick* LejuHandPoseEvent::release_left_joystick() {
  // @@protoc_insertion_point(field_release:LejuHandPoseEvent.left_joystick)
  
  ::LejuHandPoseEvent_Joystick* temp = left_joystick_;
  left_joystick_ = NULL;
  return temp;
}
inline ::LejuHandPoseEvent_Joystick* LejuHandPoseEvent::mutable_left_joystick() {
  
  if (left_joystick_ == NULL) {
    auto* p = CreateMaybeMessage<::LejuHandPoseEvent_Joystick>(GetArenaNoVirtual());
    left_joystick_ = p;
  }
  // @@protoc_insertion_point(field_mutable:LejuHandPoseEvent.left_joystick)
  return left_joystick_;
}
inline void LejuHandPoseEvent::set_allocated_left_joystick(::LejuHandPoseEvent_Joystick* left_joystick) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete left_joystick_;
  }
  if (left_joystick) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      left_joystick = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, left_joystick, submessage_arena);
    }
    
  } else {
    
  }
  left_joystick_ = left_joystick;
  // @@protoc_insertion_point(field_set_allocated:LejuHandPoseEvent.left_joystick)
}

// .LejuHandPoseEvent.Joystick right_joystick = 6;
inline bool LejuHandPoseEvent::has_right_joystick() const {
  return this != internal_default_instance() && right_joystick_ != NULL;
}
inline void LejuHandPoseEvent::clear_right_joystick() {
  if (GetArenaNoVirtual() == NULL && right_joystick_ != NULL) {
    delete right_joystick_;
  }
  right_joystick_ = NULL;
}
inline const ::LejuHandPoseEvent_Joystick& LejuHandPoseEvent::_internal_right_joystick() const {
  return *right_joystick_;
}
inline const ::LejuHandPoseEvent_Joystick& LejuHandPoseEvent::right_joystick() const {
  const ::LejuHandPoseEvent_Joystick* p = right_joystick_;
  // @@protoc_insertion_point(field_get:LejuHandPoseEvent.right_joystick)
  return p != NULL ? *p : *reinterpret_cast<const ::LejuHandPoseEvent_Joystick*>(
      &::_LejuHandPoseEvent_Joystick_default_instance_);
}
inline ::LejuHandPoseEvent_Joystick* LejuHandPoseEvent::release_right_joystick() {
  // @@protoc_insertion_point(field_release:LejuHandPoseEvent.right_joystick)
  
  ::LejuHandPoseEvent_Joystick* temp = right_joystick_;
  right_joystick_ = NULL;
  return temp;
}
inline ::LejuHandPoseEvent_Joystick* LejuHandPoseEvent::mutable_right_joystick() {
  
  if (right_joystick_ == NULL) {
    auto* p = CreateMaybeMessage<::LejuHandPoseEvent_Joystick>(GetArenaNoVirtual());
    right_joystick_ = p;
  }
  // @@protoc_insertion_point(field_mutable:LejuHandPoseEvent.right_joystick)
  return right_joystick_;
}
inline void LejuHandPoseEvent::set_allocated_right_joystick(::LejuHandPoseEvent_Joystick* right_joystick) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete right_joystick_;
  }
  if (right_joystick) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      right_joystick = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, right_joystick, submessage_arena);
    }
    
  } else {
    
  }
  right_joystick_ = right_joystick;
  // @@protoc_insertion_point(field_set_allocated:LejuHandPoseEvent.right_joystick)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_hand_5fpose_2eproto
