// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hand_pose.proto

#include "hand_pose.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_hand_5fpose_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_hand_5fpose_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_LejuHandPoseEvent_Joystick;
extern PROTOBUF_INTERNAL_EXPORT_protobuf_hand_5fpose_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_LejuHandPoseEvent_Pose_Position;
extern PROTOBUF_INTERNAL_EXPORT_protobuf_hand_5fpose_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_LejuHandPoseEvent_Pose_Quaternion;
extern PROTOBUF_INTERNAL_EXPORT_protobuf_hand_5fpose_2eproto ::google::protobuf::internal::SCCInfo<2> scc_info_LejuHandPoseEvent_Pose;
}  // namespace protobuf_hand_5fpose_2eproto
class LejuHandPoseEvent_Pose_PositionDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<LejuHandPoseEvent_Pose_Position>
      _instance;
} _LejuHandPoseEvent_Pose_Position_default_instance_;
class LejuHandPoseEvent_Pose_QuaternionDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<LejuHandPoseEvent_Pose_Quaternion>
      _instance;
} _LejuHandPoseEvent_Pose_Quaternion_default_instance_;
class LejuHandPoseEvent_PoseDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<LejuHandPoseEvent_Pose>
      _instance;
} _LejuHandPoseEvent_Pose_default_instance_;
class LejuHandPoseEvent_JoystickDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<LejuHandPoseEvent_Joystick>
      _instance;
} _LejuHandPoseEvent_Joystick_default_instance_;
class LejuHandPoseEventDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<LejuHandPoseEvent>
      _instance;
} _LejuHandPoseEvent_default_instance_;
namespace protobuf_hand_5fpose_2eproto {
static void InitDefaultsLejuHandPoseEvent_Pose_Position() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_LejuHandPoseEvent_Pose_Position_default_instance_;
    new (ptr) ::LejuHandPoseEvent_Pose_Position();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::LejuHandPoseEvent_Pose_Position::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_LejuHandPoseEvent_Pose_Position =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsLejuHandPoseEvent_Pose_Position}, {}};

static void InitDefaultsLejuHandPoseEvent_Pose_Quaternion() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_LejuHandPoseEvent_Pose_Quaternion_default_instance_;
    new (ptr) ::LejuHandPoseEvent_Pose_Quaternion();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::LejuHandPoseEvent_Pose_Quaternion::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_LejuHandPoseEvent_Pose_Quaternion =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsLejuHandPoseEvent_Pose_Quaternion}, {}};

static void InitDefaultsLejuHandPoseEvent_Pose() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_LejuHandPoseEvent_Pose_default_instance_;
    new (ptr) ::LejuHandPoseEvent_Pose();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::LejuHandPoseEvent_Pose::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<2> scc_info_LejuHandPoseEvent_Pose =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 2, InitDefaultsLejuHandPoseEvent_Pose}, {
      &protobuf_hand_5fpose_2eproto::scc_info_LejuHandPoseEvent_Pose_Position.base,
      &protobuf_hand_5fpose_2eproto::scc_info_LejuHandPoseEvent_Pose_Quaternion.base,}};

static void InitDefaultsLejuHandPoseEvent_Joystick() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_LejuHandPoseEvent_Joystick_default_instance_;
    new (ptr) ::LejuHandPoseEvent_Joystick();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::LejuHandPoseEvent_Joystick::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_LejuHandPoseEvent_Joystick =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsLejuHandPoseEvent_Joystick}, {}};

static void InitDefaultsLejuHandPoseEvent() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_LejuHandPoseEvent_default_instance_;
    new (ptr) ::LejuHandPoseEvent();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::LejuHandPoseEvent::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<2> scc_info_LejuHandPoseEvent =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 2, InitDefaultsLejuHandPoseEvent}, {
      &protobuf_hand_5fpose_2eproto::scc_info_LejuHandPoseEvent_Pose.base,
      &protobuf_hand_5fpose_2eproto::scc_info_LejuHandPoseEvent_Joystick.base,}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_LejuHandPoseEvent_Pose_Position.base);
  ::google::protobuf::internal::InitSCC(&scc_info_LejuHandPoseEvent_Pose_Quaternion.base);
  ::google::protobuf::internal::InitSCC(&scc_info_LejuHandPoseEvent_Pose.base);
  ::google::protobuf::internal::InitSCC(&scc_info_LejuHandPoseEvent_Joystick.base);
  ::google::protobuf::internal::InitSCC(&scc_info_LejuHandPoseEvent.base);
}

::google::protobuf::Metadata file_level_metadata[5];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::LejuHandPoseEvent_Pose_Position, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::LejuHandPoseEvent_Pose_Position, x_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::LejuHandPoseEvent_Pose_Position, y_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::LejuHandPoseEvent_Pose_Position, z_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::LejuHandPoseEvent_Pose_Quaternion, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::LejuHandPoseEvent_Pose_Quaternion, x_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::LejuHandPoseEvent_Pose_Quaternion, y_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::LejuHandPoseEvent_Pose_Quaternion, z_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::LejuHandPoseEvent_Pose_Quaternion, w_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::LejuHandPoseEvent_Pose, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::LejuHandPoseEvent_Pose, position_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::LejuHandPoseEvent_Pose, quaternion_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::LejuHandPoseEvent_Joystick, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::LejuHandPoseEvent_Joystick, x_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::LejuHandPoseEvent_Joystick, y_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::LejuHandPoseEvent_Joystick, trigger_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::LejuHandPoseEvent_Joystick, grip_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::LejuHandPoseEvent_Joystick, firstbuttonpressed_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::LejuHandPoseEvent_Joystick, secondbuttonpressed_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::LejuHandPoseEvent_Joystick, firstbuttontouched_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::LejuHandPoseEvent_Joystick, secondbuttontouched_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::LejuHandPoseEvent, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::LejuHandPoseEvent, timestamp_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::LejuHandPoseEvent, poses_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::LejuHandPoseEvent, isdatahighconfidence_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::LejuHandPoseEvent, ishandtracking_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::LejuHandPoseEvent, left_joystick_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::LejuHandPoseEvent, right_joystick_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::LejuHandPoseEvent_Pose_Position)},
  { 8, -1, sizeof(::LejuHandPoseEvent_Pose_Quaternion)},
  { 17, -1, sizeof(::LejuHandPoseEvent_Pose)},
  { 24, -1, sizeof(::LejuHandPoseEvent_Joystick)},
  { 37, -1, sizeof(::LejuHandPoseEvent)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::_LejuHandPoseEvent_Pose_Position_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::_LejuHandPoseEvent_Pose_Quaternion_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::_LejuHandPoseEvent_Pose_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::_LejuHandPoseEvent_Joystick_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::_LejuHandPoseEvent_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "hand_pose.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 5);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\017hand_pose.proto\"\375\004\n\021LejuHandPoseEvent\022"
      "\021\n\ttimestamp\030\001 \001(\003\022&\n\005poses\030\002 \003(\0132\027.Leju"
      "HandPoseEvent.Pose\022\034\n\024IsDataHighConfiden"
      "ce\030\003 \001(\010\022\026\n\016IsHandTracking\030\004 \001(\010\0222\n\rleft"
      "_joystick\030\005 \001(\0132\033.LejuHandPoseEvent.Joys"
      "tick\0223\n\016right_joystick\030\006 \001(\0132\033.LejuHandP"
      "oseEvent.Joystick\032\331\001\n\004Pose\0222\n\010position\030\001"
      " \001(\0132 .LejuHandPoseEvent.Pose.Position\0226"
      "\n\nquaternion\030\002 \001(\0132\".LejuHandPoseEvent.P"
      "ose.Quaternion\032+\n\010Position\022\t\n\001x\030\001 \001(\002\022\t\n"
      "\001y\030\002 \001(\002\022\t\n\001z\030\003 \001(\002\0328\n\nQuaternion\022\t\n\001x\030\001"
      " \001(\002\022\t\n\001y\030\002 \001(\002\022\t\n\001z\030\003 \001(\002\022\t\n\001w\030\004 \001(\002\032\261\001"
      "\n\010Joystick\022\t\n\001x\030\001 \001(\002\022\t\n\001y\030\002 \001(\002\022\017\n\007trig"
      "ger\030\003 \001(\002\022\014\n\004grip\030\004 \001(\002\022\032\n\022firstButtonPr"
      "essed\030\005 \001(\010\022\033\n\023secondButtonPressed\030\006 \001(\010"
      "\022\032\n\022firstButtonTouched\030\007 \001(\010\022\033\n\023secondBu"
      "ttonTouched\030\010 \001(\010b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 665);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "hand_pose.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_hand_5fpose_2eproto

// ===================================================================

void LejuHandPoseEvent_Pose_Position::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int LejuHandPoseEvent_Pose_Position::kXFieldNumber;
const int LejuHandPoseEvent_Pose_Position::kYFieldNumber;
const int LejuHandPoseEvent_Pose_Position::kZFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

LejuHandPoseEvent_Pose_Position::LejuHandPoseEvent_Pose_Position()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_hand_5fpose_2eproto::scc_info_LejuHandPoseEvent_Pose_Position.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:LejuHandPoseEvent.Pose.Position)
}
LejuHandPoseEvent_Pose_Position::LejuHandPoseEvent_Pose_Position(const LejuHandPoseEvent_Pose_Position& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&x_, &from.x_,
    static_cast<size_t>(reinterpret_cast<char*>(&z_) -
    reinterpret_cast<char*>(&x_)) + sizeof(z_));
  // @@protoc_insertion_point(copy_constructor:LejuHandPoseEvent.Pose.Position)
}

void LejuHandPoseEvent_Pose_Position::SharedCtor() {
  ::memset(&x_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&z_) -
      reinterpret_cast<char*>(&x_)) + sizeof(z_));
}

LejuHandPoseEvent_Pose_Position::~LejuHandPoseEvent_Pose_Position() {
  // @@protoc_insertion_point(destructor:LejuHandPoseEvent.Pose.Position)
  SharedDtor();
}

void LejuHandPoseEvent_Pose_Position::SharedDtor() {
}

void LejuHandPoseEvent_Pose_Position::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* LejuHandPoseEvent_Pose_Position::descriptor() {
  ::protobuf_hand_5fpose_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_hand_5fpose_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const LejuHandPoseEvent_Pose_Position& LejuHandPoseEvent_Pose_Position::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_hand_5fpose_2eproto::scc_info_LejuHandPoseEvent_Pose_Position.base);
  return *internal_default_instance();
}


void LejuHandPoseEvent_Pose_Position::Clear() {
// @@protoc_insertion_point(message_clear_start:LejuHandPoseEvent.Pose.Position)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&x_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&z_) -
      reinterpret_cast<char*>(&x_)) + sizeof(z_));
  _internal_metadata_.Clear();
}

bool LejuHandPoseEvent_Pose_Position::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:LejuHandPoseEvent.Pose.Position)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // float x = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(13u /* 13 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &x_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float y = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(21u /* 21 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &y_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float z = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(29u /* 29 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &z_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:LejuHandPoseEvent.Pose.Position)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:LejuHandPoseEvent.Pose.Position)
  return false;
#undef DO_
}

void LejuHandPoseEvent_Pose_Position::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:LejuHandPoseEvent.Pose.Position)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // float x = 1;
  if (this->x() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(1, this->x(), output);
  }

  // float y = 2;
  if (this->y() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(2, this->y(), output);
  }

  // float z = 3;
  if (this->z() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(3, this->z(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:LejuHandPoseEvent.Pose.Position)
}

::google::protobuf::uint8* LejuHandPoseEvent_Pose_Position::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:LejuHandPoseEvent.Pose.Position)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // float x = 1;
  if (this->x() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(1, this->x(), target);
  }

  // float y = 2;
  if (this->y() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(2, this->y(), target);
  }

  // float z = 3;
  if (this->z() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(3, this->z(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:LejuHandPoseEvent.Pose.Position)
  return target;
}

size_t LejuHandPoseEvent_Pose_Position::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:LejuHandPoseEvent.Pose.Position)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // float x = 1;
  if (this->x() != 0) {
    total_size += 1 + 4;
  }

  // float y = 2;
  if (this->y() != 0) {
    total_size += 1 + 4;
  }

  // float z = 3;
  if (this->z() != 0) {
    total_size += 1 + 4;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void LejuHandPoseEvent_Pose_Position::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:LejuHandPoseEvent.Pose.Position)
  GOOGLE_DCHECK_NE(&from, this);
  const LejuHandPoseEvent_Pose_Position* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const LejuHandPoseEvent_Pose_Position>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:LejuHandPoseEvent.Pose.Position)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:LejuHandPoseEvent.Pose.Position)
    MergeFrom(*source);
  }
}

void LejuHandPoseEvent_Pose_Position::MergeFrom(const LejuHandPoseEvent_Pose_Position& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:LejuHandPoseEvent.Pose.Position)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.x() != 0) {
    set_x(from.x());
  }
  if (from.y() != 0) {
    set_y(from.y());
  }
  if (from.z() != 0) {
    set_z(from.z());
  }
}

void LejuHandPoseEvent_Pose_Position::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:LejuHandPoseEvent.Pose.Position)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void LejuHandPoseEvent_Pose_Position::CopyFrom(const LejuHandPoseEvent_Pose_Position& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:LejuHandPoseEvent.Pose.Position)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool LejuHandPoseEvent_Pose_Position::IsInitialized() const {
  return true;
}

void LejuHandPoseEvent_Pose_Position::Swap(LejuHandPoseEvent_Pose_Position* other) {
  if (other == this) return;
  InternalSwap(other);
}
void LejuHandPoseEvent_Pose_Position::InternalSwap(LejuHandPoseEvent_Pose_Position* other) {
  using std::swap;
  swap(x_, other->x_);
  swap(y_, other->y_);
  swap(z_, other->z_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata LejuHandPoseEvent_Pose_Position::GetMetadata() const {
  protobuf_hand_5fpose_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_hand_5fpose_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void LejuHandPoseEvent_Pose_Quaternion::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int LejuHandPoseEvent_Pose_Quaternion::kXFieldNumber;
const int LejuHandPoseEvent_Pose_Quaternion::kYFieldNumber;
const int LejuHandPoseEvent_Pose_Quaternion::kZFieldNumber;
const int LejuHandPoseEvent_Pose_Quaternion::kWFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

LejuHandPoseEvent_Pose_Quaternion::LejuHandPoseEvent_Pose_Quaternion()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_hand_5fpose_2eproto::scc_info_LejuHandPoseEvent_Pose_Quaternion.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:LejuHandPoseEvent.Pose.Quaternion)
}
LejuHandPoseEvent_Pose_Quaternion::LejuHandPoseEvent_Pose_Quaternion(const LejuHandPoseEvent_Pose_Quaternion& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&x_, &from.x_,
    static_cast<size_t>(reinterpret_cast<char*>(&w_) -
    reinterpret_cast<char*>(&x_)) + sizeof(w_));
  // @@protoc_insertion_point(copy_constructor:LejuHandPoseEvent.Pose.Quaternion)
}

void LejuHandPoseEvent_Pose_Quaternion::SharedCtor() {
  ::memset(&x_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&w_) -
      reinterpret_cast<char*>(&x_)) + sizeof(w_));
}

LejuHandPoseEvent_Pose_Quaternion::~LejuHandPoseEvent_Pose_Quaternion() {
  // @@protoc_insertion_point(destructor:LejuHandPoseEvent.Pose.Quaternion)
  SharedDtor();
}

void LejuHandPoseEvent_Pose_Quaternion::SharedDtor() {
}

void LejuHandPoseEvent_Pose_Quaternion::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* LejuHandPoseEvent_Pose_Quaternion::descriptor() {
  ::protobuf_hand_5fpose_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_hand_5fpose_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const LejuHandPoseEvent_Pose_Quaternion& LejuHandPoseEvent_Pose_Quaternion::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_hand_5fpose_2eproto::scc_info_LejuHandPoseEvent_Pose_Quaternion.base);
  return *internal_default_instance();
}


void LejuHandPoseEvent_Pose_Quaternion::Clear() {
// @@protoc_insertion_point(message_clear_start:LejuHandPoseEvent.Pose.Quaternion)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&x_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&w_) -
      reinterpret_cast<char*>(&x_)) + sizeof(w_));
  _internal_metadata_.Clear();
}

bool LejuHandPoseEvent_Pose_Quaternion::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:LejuHandPoseEvent.Pose.Quaternion)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // float x = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(13u /* 13 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &x_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float y = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(21u /* 21 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &y_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float z = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(29u /* 29 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &z_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float w = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(37u /* 37 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &w_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:LejuHandPoseEvent.Pose.Quaternion)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:LejuHandPoseEvent.Pose.Quaternion)
  return false;
#undef DO_
}

void LejuHandPoseEvent_Pose_Quaternion::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:LejuHandPoseEvent.Pose.Quaternion)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // float x = 1;
  if (this->x() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(1, this->x(), output);
  }

  // float y = 2;
  if (this->y() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(2, this->y(), output);
  }

  // float z = 3;
  if (this->z() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(3, this->z(), output);
  }

  // float w = 4;
  if (this->w() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(4, this->w(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:LejuHandPoseEvent.Pose.Quaternion)
}

::google::protobuf::uint8* LejuHandPoseEvent_Pose_Quaternion::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:LejuHandPoseEvent.Pose.Quaternion)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // float x = 1;
  if (this->x() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(1, this->x(), target);
  }

  // float y = 2;
  if (this->y() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(2, this->y(), target);
  }

  // float z = 3;
  if (this->z() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(3, this->z(), target);
  }

  // float w = 4;
  if (this->w() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(4, this->w(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:LejuHandPoseEvent.Pose.Quaternion)
  return target;
}

size_t LejuHandPoseEvent_Pose_Quaternion::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:LejuHandPoseEvent.Pose.Quaternion)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // float x = 1;
  if (this->x() != 0) {
    total_size += 1 + 4;
  }

  // float y = 2;
  if (this->y() != 0) {
    total_size += 1 + 4;
  }

  // float z = 3;
  if (this->z() != 0) {
    total_size += 1 + 4;
  }

  // float w = 4;
  if (this->w() != 0) {
    total_size += 1 + 4;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void LejuHandPoseEvent_Pose_Quaternion::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:LejuHandPoseEvent.Pose.Quaternion)
  GOOGLE_DCHECK_NE(&from, this);
  const LejuHandPoseEvent_Pose_Quaternion* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const LejuHandPoseEvent_Pose_Quaternion>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:LejuHandPoseEvent.Pose.Quaternion)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:LejuHandPoseEvent.Pose.Quaternion)
    MergeFrom(*source);
  }
}

void LejuHandPoseEvent_Pose_Quaternion::MergeFrom(const LejuHandPoseEvent_Pose_Quaternion& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:LejuHandPoseEvent.Pose.Quaternion)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.x() != 0) {
    set_x(from.x());
  }
  if (from.y() != 0) {
    set_y(from.y());
  }
  if (from.z() != 0) {
    set_z(from.z());
  }
  if (from.w() != 0) {
    set_w(from.w());
  }
}

void LejuHandPoseEvent_Pose_Quaternion::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:LejuHandPoseEvent.Pose.Quaternion)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void LejuHandPoseEvent_Pose_Quaternion::CopyFrom(const LejuHandPoseEvent_Pose_Quaternion& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:LejuHandPoseEvent.Pose.Quaternion)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool LejuHandPoseEvent_Pose_Quaternion::IsInitialized() const {
  return true;
}

void LejuHandPoseEvent_Pose_Quaternion::Swap(LejuHandPoseEvent_Pose_Quaternion* other) {
  if (other == this) return;
  InternalSwap(other);
}
void LejuHandPoseEvent_Pose_Quaternion::InternalSwap(LejuHandPoseEvent_Pose_Quaternion* other) {
  using std::swap;
  swap(x_, other->x_);
  swap(y_, other->y_);
  swap(z_, other->z_);
  swap(w_, other->w_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata LejuHandPoseEvent_Pose_Quaternion::GetMetadata() const {
  protobuf_hand_5fpose_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_hand_5fpose_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void LejuHandPoseEvent_Pose::InitAsDefaultInstance() {
  ::_LejuHandPoseEvent_Pose_default_instance_._instance.get_mutable()->position_ = const_cast< ::LejuHandPoseEvent_Pose_Position*>(
      ::LejuHandPoseEvent_Pose_Position::internal_default_instance());
  ::_LejuHandPoseEvent_Pose_default_instance_._instance.get_mutable()->quaternion_ = const_cast< ::LejuHandPoseEvent_Pose_Quaternion*>(
      ::LejuHandPoseEvent_Pose_Quaternion::internal_default_instance());
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int LejuHandPoseEvent_Pose::kPositionFieldNumber;
const int LejuHandPoseEvent_Pose::kQuaternionFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

LejuHandPoseEvent_Pose::LejuHandPoseEvent_Pose()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_hand_5fpose_2eproto::scc_info_LejuHandPoseEvent_Pose.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:LejuHandPoseEvent.Pose)
}
LejuHandPoseEvent_Pose::LejuHandPoseEvent_Pose(const LejuHandPoseEvent_Pose& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_position()) {
    position_ = new ::LejuHandPoseEvent_Pose_Position(*from.position_);
  } else {
    position_ = NULL;
  }
  if (from.has_quaternion()) {
    quaternion_ = new ::LejuHandPoseEvent_Pose_Quaternion(*from.quaternion_);
  } else {
    quaternion_ = NULL;
  }
  // @@protoc_insertion_point(copy_constructor:LejuHandPoseEvent.Pose)
}

void LejuHandPoseEvent_Pose::SharedCtor() {
  ::memset(&position_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&quaternion_) -
      reinterpret_cast<char*>(&position_)) + sizeof(quaternion_));
}

LejuHandPoseEvent_Pose::~LejuHandPoseEvent_Pose() {
  // @@protoc_insertion_point(destructor:LejuHandPoseEvent.Pose)
  SharedDtor();
}

void LejuHandPoseEvent_Pose::SharedDtor() {
  if (this != internal_default_instance()) delete position_;
  if (this != internal_default_instance()) delete quaternion_;
}

void LejuHandPoseEvent_Pose::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* LejuHandPoseEvent_Pose::descriptor() {
  ::protobuf_hand_5fpose_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_hand_5fpose_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const LejuHandPoseEvent_Pose& LejuHandPoseEvent_Pose::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_hand_5fpose_2eproto::scc_info_LejuHandPoseEvent_Pose.base);
  return *internal_default_instance();
}


void LejuHandPoseEvent_Pose::Clear() {
// @@protoc_insertion_point(message_clear_start:LejuHandPoseEvent.Pose)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaNoVirtual() == NULL && position_ != NULL) {
    delete position_;
  }
  position_ = NULL;
  if (GetArenaNoVirtual() == NULL && quaternion_ != NULL) {
    delete quaternion_;
  }
  quaternion_ = NULL;
  _internal_metadata_.Clear();
}

bool LejuHandPoseEvent_Pose::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:LejuHandPoseEvent.Pose)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .LejuHandPoseEvent.Pose.Position position = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_position()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .LejuHandPoseEvent.Pose.Quaternion quaternion = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_quaternion()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:LejuHandPoseEvent.Pose)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:LejuHandPoseEvent.Pose)
  return false;
#undef DO_
}

void LejuHandPoseEvent_Pose::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:LejuHandPoseEvent.Pose)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .LejuHandPoseEvent.Pose.Position position = 1;
  if (this->has_position()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->_internal_position(), output);
  }

  // .LejuHandPoseEvent.Pose.Quaternion quaternion = 2;
  if (this->has_quaternion()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->_internal_quaternion(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:LejuHandPoseEvent.Pose)
}

::google::protobuf::uint8* LejuHandPoseEvent_Pose::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:LejuHandPoseEvent.Pose)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .LejuHandPoseEvent.Pose.Position position = 1;
  if (this->has_position()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, this->_internal_position(), deterministic, target);
  }

  // .LejuHandPoseEvent.Pose.Quaternion quaternion = 2;
  if (this->has_quaternion()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        2, this->_internal_quaternion(), deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:LejuHandPoseEvent.Pose)
  return target;
}

size_t LejuHandPoseEvent_Pose::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:LejuHandPoseEvent.Pose)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // .LejuHandPoseEvent.Pose.Position position = 1;
  if (this->has_position()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *position_);
  }

  // .LejuHandPoseEvent.Pose.Quaternion quaternion = 2;
  if (this->has_quaternion()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *quaternion_);
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void LejuHandPoseEvent_Pose::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:LejuHandPoseEvent.Pose)
  GOOGLE_DCHECK_NE(&from, this);
  const LejuHandPoseEvent_Pose* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const LejuHandPoseEvent_Pose>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:LejuHandPoseEvent.Pose)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:LejuHandPoseEvent.Pose)
    MergeFrom(*source);
  }
}

void LejuHandPoseEvent_Pose::MergeFrom(const LejuHandPoseEvent_Pose& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:LejuHandPoseEvent.Pose)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_position()) {
    mutable_position()->::LejuHandPoseEvent_Pose_Position::MergeFrom(from.position());
  }
  if (from.has_quaternion()) {
    mutable_quaternion()->::LejuHandPoseEvent_Pose_Quaternion::MergeFrom(from.quaternion());
  }
}

void LejuHandPoseEvent_Pose::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:LejuHandPoseEvent.Pose)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void LejuHandPoseEvent_Pose::CopyFrom(const LejuHandPoseEvent_Pose& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:LejuHandPoseEvent.Pose)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool LejuHandPoseEvent_Pose::IsInitialized() const {
  return true;
}

void LejuHandPoseEvent_Pose::Swap(LejuHandPoseEvent_Pose* other) {
  if (other == this) return;
  InternalSwap(other);
}
void LejuHandPoseEvent_Pose::InternalSwap(LejuHandPoseEvent_Pose* other) {
  using std::swap;
  swap(position_, other->position_);
  swap(quaternion_, other->quaternion_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata LejuHandPoseEvent_Pose::GetMetadata() const {
  protobuf_hand_5fpose_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_hand_5fpose_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void LejuHandPoseEvent_Joystick::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int LejuHandPoseEvent_Joystick::kXFieldNumber;
const int LejuHandPoseEvent_Joystick::kYFieldNumber;
const int LejuHandPoseEvent_Joystick::kTriggerFieldNumber;
const int LejuHandPoseEvent_Joystick::kGripFieldNumber;
const int LejuHandPoseEvent_Joystick::kFirstButtonPressedFieldNumber;
const int LejuHandPoseEvent_Joystick::kSecondButtonPressedFieldNumber;
const int LejuHandPoseEvent_Joystick::kFirstButtonTouchedFieldNumber;
const int LejuHandPoseEvent_Joystick::kSecondButtonTouchedFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

LejuHandPoseEvent_Joystick::LejuHandPoseEvent_Joystick()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_hand_5fpose_2eproto::scc_info_LejuHandPoseEvent_Joystick.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:LejuHandPoseEvent.Joystick)
}
LejuHandPoseEvent_Joystick::LejuHandPoseEvent_Joystick(const LejuHandPoseEvent_Joystick& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&x_, &from.x_,
    static_cast<size_t>(reinterpret_cast<char*>(&secondbuttontouched_) -
    reinterpret_cast<char*>(&x_)) + sizeof(secondbuttontouched_));
  // @@protoc_insertion_point(copy_constructor:LejuHandPoseEvent.Joystick)
}

void LejuHandPoseEvent_Joystick::SharedCtor() {
  ::memset(&x_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&secondbuttontouched_) -
      reinterpret_cast<char*>(&x_)) + sizeof(secondbuttontouched_));
}

LejuHandPoseEvent_Joystick::~LejuHandPoseEvent_Joystick() {
  // @@protoc_insertion_point(destructor:LejuHandPoseEvent.Joystick)
  SharedDtor();
}

void LejuHandPoseEvent_Joystick::SharedDtor() {
}

void LejuHandPoseEvent_Joystick::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* LejuHandPoseEvent_Joystick::descriptor() {
  ::protobuf_hand_5fpose_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_hand_5fpose_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const LejuHandPoseEvent_Joystick& LejuHandPoseEvent_Joystick::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_hand_5fpose_2eproto::scc_info_LejuHandPoseEvent_Joystick.base);
  return *internal_default_instance();
}


void LejuHandPoseEvent_Joystick::Clear() {
// @@protoc_insertion_point(message_clear_start:LejuHandPoseEvent.Joystick)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&x_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&secondbuttontouched_) -
      reinterpret_cast<char*>(&x_)) + sizeof(secondbuttontouched_));
  _internal_metadata_.Clear();
}

bool LejuHandPoseEvent_Joystick::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:LejuHandPoseEvent.Joystick)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // float x = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(13u /* 13 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &x_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float y = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(21u /* 21 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &y_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float trigger = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(29u /* 29 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &trigger_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float grip = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(37u /* 37 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &grip_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bool firstButtonPressed = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(40u /* 40 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &firstbuttonpressed_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bool secondButtonPressed = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(48u /* 48 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &secondbuttonpressed_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bool firstButtonTouched = 7;
      case 7: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(56u /* 56 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &firstbuttontouched_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bool secondButtonTouched = 8;
      case 8: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(64u /* 64 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &secondbuttontouched_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:LejuHandPoseEvent.Joystick)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:LejuHandPoseEvent.Joystick)
  return false;
#undef DO_
}

void LejuHandPoseEvent_Joystick::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:LejuHandPoseEvent.Joystick)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // float x = 1;
  if (this->x() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(1, this->x(), output);
  }

  // float y = 2;
  if (this->y() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(2, this->y(), output);
  }

  // float trigger = 3;
  if (this->trigger() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(3, this->trigger(), output);
  }

  // float grip = 4;
  if (this->grip() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(4, this->grip(), output);
  }

  // bool firstButtonPressed = 5;
  if (this->firstbuttonpressed() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(5, this->firstbuttonpressed(), output);
  }

  // bool secondButtonPressed = 6;
  if (this->secondbuttonpressed() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(6, this->secondbuttonpressed(), output);
  }

  // bool firstButtonTouched = 7;
  if (this->firstbuttontouched() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(7, this->firstbuttontouched(), output);
  }

  // bool secondButtonTouched = 8;
  if (this->secondbuttontouched() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(8, this->secondbuttontouched(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:LejuHandPoseEvent.Joystick)
}

::google::protobuf::uint8* LejuHandPoseEvent_Joystick::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:LejuHandPoseEvent.Joystick)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // float x = 1;
  if (this->x() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(1, this->x(), target);
  }

  // float y = 2;
  if (this->y() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(2, this->y(), target);
  }

  // float trigger = 3;
  if (this->trigger() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(3, this->trigger(), target);
  }

  // float grip = 4;
  if (this->grip() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(4, this->grip(), target);
  }

  // bool firstButtonPressed = 5;
  if (this->firstbuttonpressed() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(5, this->firstbuttonpressed(), target);
  }

  // bool secondButtonPressed = 6;
  if (this->secondbuttonpressed() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(6, this->secondbuttonpressed(), target);
  }

  // bool firstButtonTouched = 7;
  if (this->firstbuttontouched() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(7, this->firstbuttontouched(), target);
  }

  // bool secondButtonTouched = 8;
  if (this->secondbuttontouched() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(8, this->secondbuttontouched(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:LejuHandPoseEvent.Joystick)
  return target;
}

size_t LejuHandPoseEvent_Joystick::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:LejuHandPoseEvent.Joystick)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // float x = 1;
  if (this->x() != 0) {
    total_size += 1 + 4;
  }

  // float y = 2;
  if (this->y() != 0) {
    total_size += 1 + 4;
  }

  // float trigger = 3;
  if (this->trigger() != 0) {
    total_size += 1 + 4;
  }

  // float grip = 4;
  if (this->grip() != 0) {
    total_size += 1 + 4;
  }

  // bool firstButtonPressed = 5;
  if (this->firstbuttonpressed() != 0) {
    total_size += 1 + 1;
  }

  // bool secondButtonPressed = 6;
  if (this->secondbuttonpressed() != 0) {
    total_size += 1 + 1;
  }

  // bool firstButtonTouched = 7;
  if (this->firstbuttontouched() != 0) {
    total_size += 1 + 1;
  }

  // bool secondButtonTouched = 8;
  if (this->secondbuttontouched() != 0) {
    total_size += 1 + 1;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void LejuHandPoseEvent_Joystick::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:LejuHandPoseEvent.Joystick)
  GOOGLE_DCHECK_NE(&from, this);
  const LejuHandPoseEvent_Joystick* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const LejuHandPoseEvent_Joystick>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:LejuHandPoseEvent.Joystick)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:LejuHandPoseEvent.Joystick)
    MergeFrom(*source);
  }
}

void LejuHandPoseEvent_Joystick::MergeFrom(const LejuHandPoseEvent_Joystick& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:LejuHandPoseEvent.Joystick)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.x() != 0) {
    set_x(from.x());
  }
  if (from.y() != 0) {
    set_y(from.y());
  }
  if (from.trigger() != 0) {
    set_trigger(from.trigger());
  }
  if (from.grip() != 0) {
    set_grip(from.grip());
  }
  if (from.firstbuttonpressed() != 0) {
    set_firstbuttonpressed(from.firstbuttonpressed());
  }
  if (from.secondbuttonpressed() != 0) {
    set_secondbuttonpressed(from.secondbuttonpressed());
  }
  if (from.firstbuttontouched() != 0) {
    set_firstbuttontouched(from.firstbuttontouched());
  }
  if (from.secondbuttontouched() != 0) {
    set_secondbuttontouched(from.secondbuttontouched());
  }
}

void LejuHandPoseEvent_Joystick::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:LejuHandPoseEvent.Joystick)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void LejuHandPoseEvent_Joystick::CopyFrom(const LejuHandPoseEvent_Joystick& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:LejuHandPoseEvent.Joystick)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool LejuHandPoseEvent_Joystick::IsInitialized() const {
  return true;
}

void LejuHandPoseEvent_Joystick::Swap(LejuHandPoseEvent_Joystick* other) {
  if (other == this) return;
  InternalSwap(other);
}
void LejuHandPoseEvent_Joystick::InternalSwap(LejuHandPoseEvent_Joystick* other) {
  using std::swap;
  swap(x_, other->x_);
  swap(y_, other->y_);
  swap(trigger_, other->trigger_);
  swap(grip_, other->grip_);
  swap(firstbuttonpressed_, other->firstbuttonpressed_);
  swap(secondbuttonpressed_, other->secondbuttonpressed_);
  swap(firstbuttontouched_, other->firstbuttontouched_);
  swap(secondbuttontouched_, other->secondbuttontouched_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata LejuHandPoseEvent_Joystick::GetMetadata() const {
  protobuf_hand_5fpose_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_hand_5fpose_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void LejuHandPoseEvent::InitAsDefaultInstance() {
  ::_LejuHandPoseEvent_default_instance_._instance.get_mutable()->left_joystick_ = const_cast< ::LejuHandPoseEvent_Joystick*>(
      ::LejuHandPoseEvent_Joystick::internal_default_instance());
  ::_LejuHandPoseEvent_default_instance_._instance.get_mutable()->right_joystick_ = const_cast< ::LejuHandPoseEvent_Joystick*>(
      ::LejuHandPoseEvent_Joystick::internal_default_instance());
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int LejuHandPoseEvent::kTimestampFieldNumber;
const int LejuHandPoseEvent::kPosesFieldNumber;
const int LejuHandPoseEvent::kIsDataHighConfidenceFieldNumber;
const int LejuHandPoseEvent::kIsHandTrackingFieldNumber;
const int LejuHandPoseEvent::kLeftJoystickFieldNumber;
const int LejuHandPoseEvent::kRightJoystickFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

LejuHandPoseEvent::LejuHandPoseEvent()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_hand_5fpose_2eproto::scc_info_LejuHandPoseEvent.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:LejuHandPoseEvent)
}
LejuHandPoseEvent::LejuHandPoseEvent(const LejuHandPoseEvent& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      poses_(from.poses_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_left_joystick()) {
    left_joystick_ = new ::LejuHandPoseEvent_Joystick(*from.left_joystick_);
  } else {
    left_joystick_ = NULL;
  }
  if (from.has_right_joystick()) {
    right_joystick_ = new ::LejuHandPoseEvent_Joystick(*from.right_joystick_);
  } else {
    right_joystick_ = NULL;
  }
  ::memcpy(&timestamp_, &from.timestamp_,
    static_cast<size_t>(reinterpret_cast<char*>(&ishandtracking_) -
    reinterpret_cast<char*>(&timestamp_)) + sizeof(ishandtracking_));
  // @@protoc_insertion_point(copy_constructor:LejuHandPoseEvent)
}

void LejuHandPoseEvent::SharedCtor() {
  ::memset(&left_joystick_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&ishandtracking_) -
      reinterpret_cast<char*>(&left_joystick_)) + sizeof(ishandtracking_));
}

LejuHandPoseEvent::~LejuHandPoseEvent() {
  // @@protoc_insertion_point(destructor:LejuHandPoseEvent)
  SharedDtor();
}

void LejuHandPoseEvent::SharedDtor() {
  if (this != internal_default_instance()) delete left_joystick_;
  if (this != internal_default_instance()) delete right_joystick_;
}

void LejuHandPoseEvent::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* LejuHandPoseEvent::descriptor() {
  ::protobuf_hand_5fpose_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_hand_5fpose_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const LejuHandPoseEvent& LejuHandPoseEvent::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_hand_5fpose_2eproto::scc_info_LejuHandPoseEvent.base);
  return *internal_default_instance();
}


void LejuHandPoseEvent::Clear() {
// @@protoc_insertion_point(message_clear_start:LejuHandPoseEvent)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  poses_.Clear();
  if (GetArenaNoVirtual() == NULL && left_joystick_ != NULL) {
    delete left_joystick_;
  }
  left_joystick_ = NULL;
  if (GetArenaNoVirtual() == NULL && right_joystick_ != NULL) {
    delete right_joystick_;
  }
  right_joystick_ = NULL;
  ::memset(&timestamp_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&ishandtracking_) -
      reinterpret_cast<char*>(&timestamp_)) + sizeof(ishandtracking_));
  _internal_metadata_.Clear();
}

bool LejuHandPoseEvent::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:LejuHandPoseEvent)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int64 timestamp = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &timestamp_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .LejuHandPoseEvent.Pose poses = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_poses()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bool IsDataHighConfidence = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &isdatahighconfidence_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bool IsHandTracking = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(32u /* 32 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &ishandtracking_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .LejuHandPoseEvent.Joystick left_joystick = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(42u /* 42 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_left_joystick()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .LejuHandPoseEvent.Joystick right_joystick = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(50u /* 50 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_right_joystick()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:LejuHandPoseEvent)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:LejuHandPoseEvent)
  return false;
#undef DO_
}

void LejuHandPoseEvent::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:LejuHandPoseEvent)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 timestamp = 1;
  if (this->timestamp() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(1, this->timestamp(), output);
  }

  // repeated .LejuHandPoseEvent.Pose poses = 2;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->poses_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2,
      this->poses(static_cast<int>(i)),
      output);
  }

  // bool IsDataHighConfidence = 3;
  if (this->isdatahighconfidence() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(3, this->isdatahighconfidence(), output);
  }

  // bool IsHandTracking = 4;
  if (this->ishandtracking() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(4, this->ishandtracking(), output);
  }

  // .LejuHandPoseEvent.Joystick left_joystick = 5;
  if (this->has_left_joystick()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      5, this->_internal_left_joystick(), output);
  }

  // .LejuHandPoseEvent.Joystick right_joystick = 6;
  if (this->has_right_joystick()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      6, this->_internal_right_joystick(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:LejuHandPoseEvent)
}

::google::protobuf::uint8* LejuHandPoseEvent::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:LejuHandPoseEvent)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 timestamp = 1;
  if (this->timestamp() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(1, this->timestamp(), target);
  }

  // repeated .LejuHandPoseEvent.Pose poses = 2;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->poses_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        2, this->poses(static_cast<int>(i)), deterministic, target);
  }

  // bool IsDataHighConfidence = 3;
  if (this->isdatahighconfidence() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(3, this->isdatahighconfidence(), target);
  }

  // bool IsHandTracking = 4;
  if (this->ishandtracking() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(4, this->ishandtracking(), target);
  }

  // .LejuHandPoseEvent.Joystick left_joystick = 5;
  if (this->has_left_joystick()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        5, this->_internal_left_joystick(), deterministic, target);
  }

  // .LejuHandPoseEvent.Joystick right_joystick = 6;
  if (this->has_right_joystick()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        6, this->_internal_right_joystick(), deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:LejuHandPoseEvent)
  return target;
}

size_t LejuHandPoseEvent::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:LejuHandPoseEvent)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated .LejuHandPoseEvent.Pose poses = 2;
  {
    unsigned int count = static_cast<unsigned int>(this->poses_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->poses(static_cast<int>(i)));
    }
  }

  // .LejuHandPoseEvent.Joystick left_joystick = 5;
  if (this->has_left_joystick()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *left_joystick_);
  }

  // .LejuHandPoseEvent.Joystick right_joystick = 6;
  if (this->has_right_joystick()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *right_joystick_);
  }

  // int64 timestamp = 1;
  if (this->timestamp() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->timestamp());
  }

  // bool IsDataHighConfidence = 3;
  if (this->isdatahighconfidence() != 0) {
    total_size += 1 + 1;
  }

  // bool IsHandTracking = 4;
  if (this->ishandtracking() != 0) {
    total_size += 1 + 1;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void LejuHandPoseEvent::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:LejuHandPoseEvent)
  GOOGLE_DCHECK_NE(&from, this);
  const LejuHandPoseEvent* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const LejuHandPoseEvent>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:LejuHandPoseEvent)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:LejuHandPoseEvent)
    MergeFrom(*source);
  }
}

void LejuHandPoseEvent::MergeFrom(const LejuHandPoseEvent& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:LejuHandPoseEvent)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  poses_.MergeFrom(from.poses_);
  if (from.has_left_joystick()) {
    mutable_left_joystick()->::LejuHandPoseEvent_Joystick::MergeFrom(from.left_joystick());
  }
  if (from.has_right_joystick()) {
    mutable_right_joystick()->::LejuHandPoseEvent_Joystick::MergeFrom(from.right_joystick());
  }
  if (from.timestamp() != 0) {
    set_timestamp(from.timestamp());
  }
  if (from.isdatahighconfidence() != 0) {
    set_isdatahighconfidence(from.isdatahighconfidence());
  }
  if (from.ishandtracking() != 0) {
    set_ishandtracking(from.ishandtracking());
  }
}

void LejuHandPoseEvent::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:LejuHandPoseEvent)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void LejuHandPoseEvent::CopyFrom(const LejuHandPoseEvent& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:LejuHandPoseEvent)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool LejuHandPoseEvent::IsInitialized() const {
  return true;
}

void LejuHandPoseEvent::Swap(LejuHandPoseEvent* other) {
  if (other == this) return;
  InternalSwap(other);
}
void LejuHandPoseEvent::InternalSwap(LejuHandPoseEvent* other) {
  using std::swap;
  CastToBase(&poses_)->InternalSwap(CastToBase(&other->poses_));
  swap(left_joystick_, other->left_joystick_);
  swap(right_joystick_, other->right_joystick_);
  swap(timestamp_, other->timestamp_);
  swap(isdatahighconfidence_, other->isdatahighconfidence_);
  swap(ishandtracking_, other->ishandtracking_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata LejuHandPoseEvent::GetMetadata() const {
  protobuf_hand_5fpose_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_hand_5fpose_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::LejuHandPoseEvent_Pose_Position* Arena::CreateMaybeMessage< ::LejuHandPoseEvent_Pose_Position >(Arena* arena) {
  return Arena::CreateInternal< ::LejuHandPoseEvent_Pose_Position >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::LejuHandPoseEvent_Pose_Quaternion* Arena::CreateMaybeMessage< ::LejuHandPoseEvent_Pose_Quaternion >(Arena* arena) {
  return Arena::CreateInternal< ::LejuHandPoseEvent_Pose_Quaternion >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::LejuHandPoseEvent_Pose* Arena::CreateMaybeMessage< ::LejuHandPoseEvent_Pose >(Arena* arena) {
  return Arena::CreateInternal< ::LejuHandPoseEvent_Pose >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::LejuHandPoseEvent_Joystick* Arena::CreateMaybeMessage< ::LejuHandPoseEvent_Joystick >(Arena* arena) {
  return Arena::CreateInternal< ::LejuHandPoseEvent_Joystick >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::LejuHandPoseEvent* Arena::CreateMaybeMessage< ::LejuHandPoseEvent >(Arena* arena) {
  return Arena::CreateInternal< ::LejuHandPoseEvent >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
