// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: robot_state.proto

#ifndef PROTOBUF_INCLUDED_robot_5fstate_2eproto
#define PROTOBUF_INCLUDED_robot_5fstate_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_robot_5fstate_2eproto 

namespace protobuf_robot_5fstate_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[4];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_robot_5fstate_2eproto
class EndEffectorState;
class EndEffectorStateDefaultTypeInternal;
extern EndEffectorStateDefaultTypeInternal _EndEffectorState_default_instance_;
class Header;
class HeaderDefaultTypeInternal;
extern HeaderDefaultTypeInternal _Header_default_instance_;
class JointState;
class JointStateDefaultTypeInternal;
extern JointStateDefaultTypeInternal _JointState_default_instance_;
class RobotState;
class RobotStateDefaultTypeInternal;
extern RobotStateDefaultTypeInternal _RobotState_default_instance_;
namespace google {
namespace protobuf {
template<> ::EndEffectorState* Arena::CreateMaybeMessage<::EndEffectorState>(Arena*);
template<> ::Header* Arena::CreateMaybeMessage<::Header>(Arena*);
template<> ::JointState* Arena::CreateMaybeMessage<::JointState>(Arena*);
template<> ::RobotState* Arena::CreateMaybeMessage<::RobotState>(Arena*);
}  // namespace protobuf
}  // namespace google

// ===================================================================

class Header : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Header) */ {
 public:
  Header();
  virtual ~Header();

  Header(const Header& from);

  inline Header& operator=(const Header& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Header(Header&& from) noexcept
    : Header() {
    *this = ::std::move(from);
  }

  inline Header& operator=(Header&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const Header& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Header* internal_default_instance() {
    return reinterpret_cast<const Header*>(
               &_Header_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(Header* other);
  friend void swap(Header& a, Header& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Header* New() const final {
    return CreateMaybeMessage<Header>(NULL);
  }

  Header* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Header>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Header& from);
  void MergeFrom(const Header& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Header* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int64 timestamp = 1;
  void clear_timestamp();
  static const int kTimestampFieldNumber = 1;
  ::google::protobuf::int64 timestamp() const;
  void set_timestamp(::google::protobuf::int64 value);

  // int64 id = 2;
  void clear_id();
  static const int kIdFieldNumber = 2;
  ::google::protobuf::int64 id() const;
  void set_id(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:Header)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int64 timestamp_;
  ::google::protobuf::int64 id_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_robot_5fstate_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class EndEffectorState : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:EndEffectorState) */ {
 public:
  EndEffectorState();
  virtual ~EndEffectorState();

  EndEffectorState(const EndEffectorState& from);

  inline EndEffectorState& operator=(const EndEffectorState& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  EndEffectorState(EndEffectorState&& from) noexcept
    : EndEffectorState() {
    *this = ::std::move(from);
  }

  inline EndEffectorState& operator=(EndEffectorState&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const EndEffectorState& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const EndEffectorState* internal_default_instance() {
    return reinterpret_cast<const EndEffectorState*>(
               &_EndEffectorState_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(EndEffectorState* other);
  friend void swap(EndEffectorState& a, EndEffectorState& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline EndEffectorState* New() const final {
    return CreateMaybeMessage<EndEffectorState>(NULL);
  }

  EndEffectorState* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<EndEffectorState>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const EndEffectorState& from);
  void MergeFrom(const EndEffectorState& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(EndEffectorState* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated double position = 1;
  int position_size() const;
  void clear_position();
  static const int kPositionFieldNumber = 1;
  double position(int index) const;
  void set_position(int index, double value);
  void add_position(double value);
  const ::google::protobuf::RepeatedField< double >&
      position() const;
  ::google::protobuf::RepeatedField< double >*
      mutable_position();

  // repeated double velocity = 2;
  int velocity_size() const;
  void clear_velocity();
  static const int kVelocityFieldNumber = 2;
  double velocity(int index) const;
  void set_velocity(int index, double value);
  void add_velocity(double value);
  const ::google::protobuf::RepeatedField< double >&
      velocity() const;
  ::google::protobuf::RepeatedField< double >*
      mutable_velocity();

  // repeated double effort = 3;
  int effort_size() const;
  void clear_effort();
  static const int kEffortFieldNumber = 3;
  double effort(int index) const;
  void set_effort(int index, double value);
  void add_effort(double value);
  const ::google::protobuf::RepeatedField< double >&
      effort() const;
  ::google::protobuf::RepeatedField< double >*
      mutable_effort();

  // @@protoc_insertion_point(class_scope:EndEffectorState)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedField< double > position_;
  mutable int _position_cached_byte_size_;
  ::google::protobuf::RepeatedField< double > velocity_;
  mutable int _velocity_cached_byte_size_;
  ::google::protobuf::RepeatedField< double > effort_;
  mutable int _effort_cached_byte_size_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_robot_5fstate_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class JointState : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:JointState) */ {
 public:
  JointState();
  virtual ~JointState();

  JointState(const JointState& from);

  inline JointState& operator=(const JointState& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  JointState(JointState&& from) noexcept
    : JointState() {
    *this = ::std::move(from);
  }

  inline JointState& operator=(JointState&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const JointState& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const JointState* internal_default_instance() {
    return reinterpret_cast<const JointState*>(
               &_JointState_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(JointState* other);
  friend void swap(JointState& a, JointState& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline JointState* New() const final {
    return CreateMaybeMessage<JointState>(NULL);
  }

  JointState* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<JointState>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const JointState& from);
  void MergeFrom(const JointState& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(JointState* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated double position = 1;
  int position_size() const;
  void clear_position();
  static const int kPositionFieldNumber = 1;
  double position(int index) const;
  void set_position(int index, double value);
  void add_position(double value);
  const ::google::protobuf::RepeatedField< double >&
      position() const;
  ::google::protobuf::RepeatedField< double >*
      mutable_position();

  // repeated double velocity = 2;
  int velocity_size() const;
  void clear_velocity();
  static const int kVelocityFieldNumber = 2;
  double velocity(int index) const;
  void set_velocity(int index, double value);
  void add_velocity(double value);
  const ::google::protobuf::RepeatedField< double >&
      velocity() const;
  ::google::protobuf::RepeatedField< double >*
      mutable_velocity();

  // repeated double torque = 3;
  int torque_size() const;
  void clear_torque();
  static const int kTorqueFieldNumber = 3;
  double torque(int index) const;
  void set_torque(int index, double value);
  void add_torque(double value);
  const ::google::protobuf::RepeatedField< double >&
      torque() const;
  ::google::protobuf::RepeatedField< double >*
      mutable_torque();

  // @@protoc_insertion_point(class_scope:JointState)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedField< double > position_;
  mutable int _position_cached_byte_size_;
  ::google::protobuf::RepeatedField< double > velocity_;
  mutable int _velocity_cached_byte_size_;
  ::google::protobuf::RepeatedField< double > torque_;
  mutable int _torque_cached_byte_size_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_robot_5fstate_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class RobotState : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:RobotState) */ {
 public:
  RobotState();
  virtual ~RobotState();

  RobotState(const RobotState& from);

  inline RobotState& operator=(const RobotState& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  RobotState(RobotState&& from) noexcept
    : RobotState() {
    *this = ::std::move(from);
  }

  inline RobotState& operator=(RobotState&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const RobotState& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const RobotState* internal_default_instance() {
    return reinterpret_cast<const RobotState*>(
               &_RobotState_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  void Swap(RobotState* other);
  friend void swap(RobotState& a, RobotState& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline RobotState* New() const final {
    return CreateMaybeMessage<RobotState>(NULL);
  }

  RobotState* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<RobotState>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const RobotState& from);
  void MergeFrom(const RobotState& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RobotState* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .Header header = 1;
  bool has_header() const;
  void clear_header();
  static const int kHeaderFieldNumber = 1;
  private:
  const ::Header& _internal_header() const;
  public:
  const ::Header& header() const;
  ::Header* release_header();
  ::Header* mutable_header();
  void set_allocated_header(::Header* header);

  // .EndEffectorState ee_state = 2;
  bool has_ee_state() const;
  void clear_ee_state();
  static const int kEeStateFieldNumber = 2;
  private:
  const ::EndEffectorState& _internal_ee_state() const;
  public:
  const ::EndEffectorState& ee_state() const;
  ::EndEffectorState* release_ee_state();
  ::EndEffectorState* mutable_ee_state();
  void set_allocated_ee_state(::EndEffectorState* ee_state);

  // .JointState joint_state = 3;
  bool has_joint_state() const;
  void clear_joint_state();
  static const int kJointStateFieldNumber = 3;
  private:
  const ::JointState& _internal_joint_state() const;
  public:
  const ::JointState& joint_state() const;
  ::JointState* release_joint_state();
  ::JointState* mutable_joint_state();
  void set_allocated_joint_state(::JointState* joint_state);

  // @@protoc_insertion_point(class_scope:RobotState)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::Header* header_;
  ::EndEffectorState* ee_state_;
  ::JointState* joint_state_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_robot_5fstate_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Header

// int64 timestamp = 1;
inline void Header::clear_timestamp() {
  timestamp_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 Header::timestamp() const {
  // @@protoc_insertion_point(field_get:Header.timestamp)
  return timestamp_;
}
inline void Header::set_timestamp(::google::protobuf::int64 value) {
  
  timestamp_ = value;
  // @@protoc_insertion_point(field_set:Header.timestamp)
}

// int64 id = 2;
inline void Header::clear_id() {
  id_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 Header::id() const {
  // @@protoc_insertion_point(field_get:Header.id)
  return id_;
}
inline void Header::set_id(::google::protobuf::int64 value) {
  
  id_ = value;
  // @@protoc_insertion_point(field_set:Header.id)
}

// -------------------------------------------------------------------

// EndEffectorState

// repeated double position = 1;
inline int EndEffectorState::position_size() const {
  return position_.size();
}
inline void EndEffectorState::clear_position() {
  position_.Clear();
}
inline double EndEffectorState::position(int index) const {
  // @@protoc_insertion_point(field_get:EndEffectorState.position)
  return position_.Get(index);
}
inline void EndEffectorState::set_position(int index, double value) {
  position_.Set(index, value);
  // @@protoc_insertion_point(field_set:EndEffectorState.position)
}
inline void EndEffectorState::add_position(double value) {
  position_.Add(value);
  // @@protoc_insertion_point(field_add:EndEffectorState.position)
}
inline const ::google::protobuf::RepeatedField< double >&
EndEffectorState::position() const {
  // @@protoc_insertion_point(field_list:EndEffectorState.position)
  return position_;
}
inline ::google::protobuf::RepeatedField< double >*
EndEffectorState::mutable_position() {
  // @@protoc_insertion_point(field_mutable_list:EndEffectorState.position)
  return &position_;
}

// repeated double velocity = 2;
inline int EndEffectorState::velocity_size() const {
  return velocity_.size();
}
inline void EndEffectorState::clear_velocity() {
  velocity_.Clear();
}
inline double EndEffectorState::velocity(int index) const {
  // @@protoc_insertion_point(field_get:EndEffectorState.velocity)
  return velocity_.Get(index);
}
inline void EndEffectorState::set_velocity(int index, double value) {
  velocity_.Set(index, value);
  // @@protoc_insertion_point(field_set:EndEffectorState.velocity)
}
inline void EndEffectorState::add_velocity(double value) {
  velocity_.Add(value);
  // @@protoc_insertion_point(field_add:EndEffectorState.velocity)
}
inline const ::google::protobuf::RepeatedField< double >&
EndEffectorState::velocity() const {
  // @@protoc_insertion_point(field_list:EndEffectorState.velocity)
  return velocity_;
}
inline ::google::protobuf::RepeatedField< double >*
EndEffectorState::mutable_velocity() {
  // @@protoc_insertion_point(field_mutable_list:EndEffectorState.velocity)
  return &velocity_;
}

// repeated double effort = 3;
inline int EndEffectorState::effort_size() const {
  return effort_.size();
}
inline void EndEffectorState::clear_effort() {
  effort_.Clear();
}
inline double EndEffectorState::effort(int index) const {
  // @@protoc_insertion_point(field_get:EndEffectorState.effort)
  return effort_.Get(index);
}
inline void EndEffectorState::set_effort(int index, double value) {
  effort_.Set(index, value);
  // @@protoc_insertion_point(field_set:EndEffectorState.effort)
}
inline void EndEffectorState::add_effort(double value) {
  effort_.Add(value);
  // @@protoc_insertion_point(field_add:EndEffectorState.effort)
}
inline const ::google::protobuf::RepeatedField< double >&
EndEffectorState::effort() const {
  // @@protoc_insertion_point(field_list:EndEffectorState.effort)
  return effort_;
}
inline ::google::protobuf::RepeatedField< double >*
EndEffectorState::mutable_effort() {
  // @@protoc_insertion_point(field_mutable_list:EndEffectorState.effort)
  return &effort_;
}

// -------------------------------------------------------------------

// JointState

// repeated double position = 1;
inline int JointState::position_size() const {
  return position_.size();
}
inline void JointState::clear_position() {
  position_.Clear();
}
inline double JointState::position(int index) const {
  // @@protoc_insertion_point(field_get:JointState.position)
  return position_.Get(index);
}
inline void JointState::set_position(int index, double value) {
  position_.Set(index, value);
  // @@protoc_insertion_point(field_set:JointState.position)
}
inline void JointState::add_position(double value) {
  position_.Add(value);
  // @@protoc_insertion_point(field_add:JointState.position)
}
inline const ::google::protobuf::RepeatedField< double >&
JointState::position() const {
  // @@protoc_insertion_point(field_list:JointState.position)
  return position_;
}
inline ::google::protobuf::RepeatedField< double >*
JointState::mutable_position() {
  // @@protoc_insertion_point(field_mutable_list:JointState.position)
  return &position_;
}

// repeated double velocity = 2;
inline int JointState::velocity_size() const {
  return velocity_.size();
}
inline void JointState::clear_velocity() {
  velocity_.Clear();
}
inline double JointState::velocity(int index) const {
  // @@protoc_insertion_point(field_get:JointState.velocity)
  return velocity_.Get(index);
}
inline void JointState::set_velocity(int index, double value) {
  velocity_.Set(index, value);
  // @@protoc_insertion_point(field_set:JointState.velocity)
}
inline void JointState::add_velocity(double value) {
  velocity_.Add(value);
  // @@protoc_insertion_point(field_add:JointState.velocity)
}
inline const ::google::protobuf::RepeatedField< double >&
JointState::velocity() const {
  // @@protoc_insertion_point(field_list:JointState.velocity)
  return velocity_;
}
inline ::google::protobuf::RepeatedField< double >*
JointState::mutable_velocity() {
  // @@protoc_insertion_point(field_mutable_list:JointState.velocity)
  return &velocity_;
}

// repeated double torque = 3;
inline int JointState::torque_size() const {
  return torque_.size();
}
inline void JointState::clear_torque() {
  torque_.Clear();
}
inline double JointState::torque(int index) const {
  // @@protoc_insertion_point(field_get:JointState.torque)
  return torque_.Get(index);
}
inline void JointState::set_torque(int index, double value) {
  torque_.Set(index, value);
  // @@protoc_insertion_point(field_set:JointState.torque)
}
inline void JointState::add_torque(double value) {
  torque_.Add(value);
  // @@protoc_insertion_point(field_add:JointState.torque)
}
inline const ::google::protobuf::RepeatedField< double >&
JointState::torque() const {
  // @@protoc_insertion_point(field_list:JointState.torque)
  return torque_;
}
inline ::google::protobuf::RepeatedField< double >*
JointState::mutable_torque() {
  // @@protoc_insertion_point(field_mutable_list:JointState.torque)
  return &torque_;
}

// -------------------------------------------------------------------

// RobotState

// .Header header = 1;
inline bool RobotState::has_header() const {
  return this != internal_default_instance() && header_ != NULL;
}
inline void RobotState::clear_header() {
  if (GetArenaNoVirtual() == NULL && header_ != NULL) {
    delete header_;
  }
  header_ = NULL;
}
inline const ::Header& RobotState::_internal_header() const {
  return *header_;
}
inline const ::Header& RobotState::header() const {
  const ::Header* p = header_;
  // @@protoc_insertion_point(field_get:RobotState.header)
  return p != NULL ? *p : *reinterpret_cast<const ::Header*>(
      &::_Header_default_instance_);
}
inline ::Header* RobotState::release_header() {
  // @@protoc_insertion_point(field_release:RobotState.header)
  
  ::Header* temp = header_;
  header_ = NULL;
  return temp;
}
inline ::Header* RobotState::mutable_header() {
  
  if (header_ == NULL) {
    auto* p = CreateMaybeMessage<::Header>(GetArenaNoVirtual());
    header_ = p;
  }
  // @@protoc_insertion_point(field_mutable:RobotState.header)
  return header_;
}
inline void RobotState::set_allocated_header(::Header* header) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete header_;
  }
  if (header) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      header = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, header, submessage_arena);
    }
    
  } else {
    
  }
  header_ = header;
  // @@protoc_insertion_point(field_set_allocated:RobotState.header)
}

// .EndEffectorState ee_state = 2;
inline bool RobotState::has_ee_state() const {
  return this != internal_default_instance() && ee_state_ != NULL;
}
inline void RobotState::clear_ee_state() {
  if (GetArenaNoVirtual() == NULL && ee_state_ != NULL) {
    delete ee_state_;
  }
  ee_state_ = NULL;
}
inline const ::EndEffectorState& RobotState::_internal_ee_state() const {
  return *ee_state_;
}
inline const ::EndEffectorState& RobotState::ee_state() const {
  const ::EndEffectorState* p = ee_state_;
  // @@protoc_insertion_point(field_get:RobotState.ee_state)
  return p != NULL ? *p : *reinterpret_cast<const ::EndEffectorState*>(
      &::_EndEffectorState_default_instance_);
}
inline ::EndEffectorState* RobotState::release_ee_state() {
  // @@protoc_insertion_point(field_release:RobotState.ee_state)
  
  ::EndEffectorState* temp = ee_state_;
  ee_state_ = NULL;
  return temp;
}
inline ::EndEffectorState* RobotState::mutable_ee_state() {
  
  if (ee_state_ == NULL) {
    auto* p = CreateMaybeMessage<::EndEffectorState>(GetArenaNoVirtual());
    ee_state_ = p;
  }
  // @@protoc_insertion_point(field_mutable:RobotState.ee_state)
  return ee_state_;
}
inline void RobotState::set_allocated_ee_state(::EndEffectorState* ee_state) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete ee_state_;
  }
  if (ee_state) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      ee_state = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, ee_state, submessage_arena);
    }
    
  } else {
    
  }
  ee_state_ = ee_state;
  // @@protoc_insertion_point(field_set_allocated:RobotState.ee_state)
}

// .JointState joint_state = 3;
inline bool RobotState::has_joint_state() const {
  return this != internal_default_instance() && joint_state_ != NULL;
}
inline void RobotState::clear_joint_state() {
  if (GetArenaNoVirtual() == NULL && joint_state_ != NULL) {
    delete joint_state_;
  }
  joint_state_ = NULL;
}
inline const ::JointState& RobotState::_internal_joint_state() const {
  return *joint_state_;
}
inline const ::JointState& RobotState::joint_state() const {
  const ::JointState* p = joint_state_;
  // @@protoc_insertion_point(field_get:RobotState.joint_state)
  return p != NULL ? *p : *reinterpret_cast<const ::JointState*>(
      &::_JointState_default_instance_);
}
inline ::JointState* RobotState::release_joint_state() {
  // @@protoc_insertion_point(field_release:RobotState.joint_state)
  
  ::JointState* temp = joint_state_;
  joint_state_ = NULL;
  return temp;
}
inline ::JointState* RobotState::mutable_joint_state() {
  
  if (joint_state_ == NULL) {
    auto* p = CreateMaybeMessage<::JointState>(GetArenaNoVirtual());
    joint_state_ = p;
  }
  // @@protoc_insertion_point(field_mutable:RobotState.joint_state)
  return joint_state_;
}
inline void RobotState::set_allocated_joint_state(::JointState* joint_state) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete joint_state_;
  }
  if (joint_state) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      joint_state = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, joint_state, submessage_arena);
    }
    
  } else {
    
  }
  joint_state_ = joint_state;
  // @@protoc_insertion_point(field_set_allocated:RobotState.joint_state)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_robot_5fstate_2eproto
