// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: robot_info.proto

#ifndef PROTOBUF_INCLUDED_robot_5finfo_2eproto
#define PROTOBUF_INCLUDED_robot_5finfo_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_robot_5finfo_2eproto 

namespace protobuf_robot_5finfo_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_robot_5finfo_2eproto
class RobotDescription;
class RobotDescriptionDefaultTypeInternal;
extern RobotDescriptionDefaultTypeInternal _RobotDescription_default_instance_;
namespace google {
namespace protobuf {
template<> ::RobotDescription* Arena::CreateMaybeMessage<::RobotDescription>(Arena*);
}  // namespace protobuf
}  // namespace google

// ===================================================================

class RobotDescription : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:RobotDescription) */ {
 public:
  RobotDescription();
  virtual ~RobotDescription();

  RobotDescription(const RobotDescription& from);

  inline RobotDescription& operator=(const RobotDescription& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  RobotDescription(RobotDescription&& from) noexcept
    : RobotDescription() {
    *this = ::std::move(from);
  }

  inline RobotDescription& operator=(RobotDescription&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const RobotDescription& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const RobotDescription* internal_default_instance() {
    return reinterpret_cast<const RobotDescription*>(
               &_RobotDescription_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(RobotDescription* other);
  friend void swap(RobotDescription& a, RobotDescription& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline RobotDescription* New() const final {
    return CreateMaybeMessage<RobotDescription>(NULL);
  }

  RobotDescription* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<RobotDescription>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const RobotDescription& from);
  void MergeFrom(const RobotDescription& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RobotDescription* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string robot_name = 1;
  void clear_robot_name();
  static const int kRobotNameFieldNumber = 1;
  const ::std::string& robot_name() const;
  void set_robot_name(const ::std::string& value);
  #if LANG_CXX11
  void set_robot_name(::std::string&& value);
  #endif
  void set_robot_name(const char* value);
  void set_robot_name(const char* value, size_t size);
  ::std::string* mutable_robot_name();
  ::std::string* release_robot_name();
  void set_allocated_robot_name(::std::string* robot_name);

  // int32 robot_version = 2;
  void clear_robot_version();
  static const int kRobotVersionFieldNumber = 2;
  ::google::protobuf::int32 robot_version() const;
  void set_robot_version(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:RobotDescription)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr robot_name_;
  ::google::protobuf::int32 robot_version_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_robot_5finfo_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// RobotDescription

// string robot_name = 1;
inline void RobotDescription::clear_robot_name() {
  robot_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& RobotDescription::robot_name() const {
  // @@protoc_insertion_point(field_get:RobotDescription.robot_name)
  return robot_name_.GetNoArena();
}
inline void RobotDescription::set_robot_name(const ::std::string& value) {
  
  robot_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:RobotDescription.robot_name)
}
#if LANG_CXX11
inline void RobotDescription::set_robot_name(::std::string&& value) {
  
  robot_name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:RobotDescription.robot_name)
}
#endif
inline void RobotDescription::set_robot_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  robot_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:RobotDescription.robot_name)
}
inline void RobotDescription::set_robot_name(const char* value, size_t size) {
  
  robot_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:RobotDescription.robot_name)
}
inline ::std::string* RobotDescription::mutable_robot_name() {
  
  // @@protoc_insertion_point(field_mutable:RobotDescription.robot_name)
  return robot_name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* RobotDescription::release_robot_name() {
  // @@protoc_insertion_point(field_release:RobotDescription.robot_name)
  
  return robot_name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void RobotDescription::set_allocated_robot_name(::std::string* robot_name) {
  if (robot_name != NULL) {
    
  } else {
    
  }
  robot_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), robot_name);
  // @@protoc_insertion_point(field_set_allocated:RobotDescription.robot_name)
}

// int32 robot_version = 2;
inline void RobotDescription::clear_robot_version() {
  robot_version_ = 0;
}
inline ::google::protobuf::int32 RobotDescription::robot_version() const {
  // @@protoc_insertion_point(field_get:RobotDescription.robot_version)
  return robot_version_;
}
inline void RobotDescription::set_robot_version(::google::protobuf::int32 value) {
  
  robot_version_ = value;
  // @@protoc_insertion_point(field_set:RobotDescription.robot_version)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_robot_5finfo_2eproto
