# 每个关键帧需包含 time 字段（单位: 秒），关节角度
# 可根据实际需求增删关键帧，一般关键帧是两个一起出现，一个用来插值和发布mark（用于数据分析），一个用来保持（用于动捕记录）
trajectory:

  - time: 0
    torso_pose: [0, 0, 0.4, 0, 0, 0]

    joint_angles: [20, 0, 0, -90, 0, 0, 0,
                   20, 0, 0, -90, 0, 0, 0]



  - time: 4
    torso_pose: [0, 0, 0.8, 0, 0, 0]
    
    joint_angles: [-20.0, 30.0, -25.0, -20.0, 40.0, -15.0, 25.0, 
                   -20.0, -30.0, 25.0, -20.0, -40.0, 15.0, 25.0]          
    mark: True

  - time: 14
    torso_pose: [0, 0, 0.8, 0, 0, 0]
    
    joint_angles: [-20.0, 30.0, -25.0, -20.0, 40.0, -15.0, 25.0, 
                   -20.0, -30.0, 25.0, -20.0, -40.0, 15.0, 25.0]       

  - time: 18
    torso_pose: [0, 0, 0.4, 0, 0, 0]

    joint_angles: [20, 0, 0, -90, 0, 0, 0,
                   20, 0, 0, -90, 0, 0, 0]
    