int8 planner_index      # 0: 底盘世界系位置运动, 1: 底盘局部系位置运动, 2: 躯干笛卡尔局部系运动, 3: 下肢关节运动, 
                        # 4: 左臂笛卡尔世界系运动, 5: 右臂笛卡尔世界系运动, 6: 左臂笛卡尔局部系运动, 
                        # 7: 右臂笛卡尔局部系运动, 8: 左臂上肢关节运动, 9: 右臂上肢关节运动

float32 desireTime      # 期望执行时间
float64[]  cmdVec       # 命令向量

---

bool isSuccess          # 是否能成功执行
float32 actualTime      # 实际执行需要的时间
string message          # 详细信息