# RL控制器列表配置文件
# 定义该版本机器人需要加载的RL控制器
# class: 控制器大类，可选值：BASE_CONTROLLER, FALL_STAND_CONTROLLER
# type: 具体控制器类型，可选值：MPC, AMP_CONTROLLER, FALL_STAND_CONTROLLER, DANCE_CONTROLLER

controllers:
  - name: "amp_controller"
    class: "BASE_CONTROLLER"  # 基础行走控制器
    type: "AMP_CONTROLLER"    # 具体控制器类型
    config_file: "rl/skw_rl_param.info" 
    enabled: true  
  
  - name: "dance_controller"
    class: "DANCE_CONTROLLER"  # 舞蹈控制器
    type: "DANCE_CONTROLLER"  # 具体控制器类型
    config_file: "rl/dance_param.info"  # 相对于版本配置目录的路径
    enabled: true  # 是否启用该控制器  

  - name: "depth_loco_controller"
    class: "BASE_CONTROLLER"  # 基础行走控制器
    type: "DEPTH_LOCO_CONTROLLER"    # 具体控制器类型
    config_file: "rl/depth_loco_param.info" 
    enabled: true  

