# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/hand_pose.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protos import hand_wrench_srv_pb2 as protos_dot_hand__wrench__srv__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16protos/hand_pose.proto\x12\x06protos\x1a\x1cprotos/hand_wrench_srv.proto\"\x80\x06\n\x11LejuHandPoseEvent\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\x12-\n\x05poses\x18\x02 \x03(\x0b\x32\x1e.protos.LejuHandPoseEvent.Pose\x12\x1c\n\x14IsDataHighConfidence\x18\x03 \x01(\x08\x12\x16\n\x0eIsHandTracking\x18\x04 \x01(\x08\x12\x39\n\rleft_joystick\x18\x05 \x01(\x0b\x32\".protos.LejuHandPoseEvent.Joystick\x12:\n\x0eright_joystick\x18\x06 \x01(\x0b\x32\".protos.LejuHandPoseEvent.Joystick\x12\x42\n\x17item_mass_force_request\x18\x07 \x01(\x0b\x32\x1c.protos.ItemMassForceRequestH\x00\x88\x01\x01\x1a\xe7\x01\n\x04Pose\x12\x39\n\x08position\x18\x01 \x01(\x0b\x32\'.protos.LejuHandPoseEvent.Pose.Position\x12=\n\nquaternion\x18\x02 \x01(\x0b\x32).protos.LejuHandPoseEvent.Pose.Quaternion\x1a+\n\x08Position\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\x1a\x38\n\nQuaternion\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\x12\t\n\x01w\x18\x04 \x01(\x02\x1a\xb1\x01\n\x08Joystick\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\x0f\n\x07trigger\x18\x03 \x01(\x02\x12\x0c\n\x04grip\x18\x04 \x01(\x02\x12\x1a\n\x12\x66irstButtonPressed\x18\x05 \x01(\x08\x12\x1b\n\x13secondButtonPressed\x18\x06 \x01(\x08\x12\x1a\n\x12\x66irstButtonTouched\x18\x07 \x01(\x08\x12\x1b\n\x13secondButtonTouched\x18\x08 \x01(\x08\x42\x1a\n\x18_item_mass_force_requestb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.hand_pose_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LEJUHANDPOSEEVENT._serialized_start=65
  _LEJUHANDPOSEEVENT._serialized_end=833
  _LEJUHANDPOSEEVENT_POSE._serialized_start=394
  _LEJUHANDPOSEEVENT_POSE._serialized_end=625
  _LEJUHANDPOSEEVENT_POSE_POSITION._serialized_start=524
  _LEJUHANDPOSEEVENT_POSE_POSITION._serialized_end=567
  _LEJUHANDPOSEEVENT_POSE_QUATERNION._serialized_start=569
  _LEJUHANDPOSEEVENT_POSE_QUATERNION._serialized_end=625
  _LEJUHANDPOSEEVENT_JOYSTICK._serialized_start=628
  _LEJUHANDPOSEEVENT_JOYSTICK._serialized_end=805
# @@protoc_insertion_point(module_scope)
