# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/hand_wrench_srv.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cprotos/hand_wrench_srv.proto\x12\x06protos\"\x80\x01\n\rItemMassForce\x12\x11\n\tcase_name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x11\n\titem_mass\x18\x03 \x01(\x01\x12\x10\n\x08lforce_x\x18\x04 \x01(\x01\x12\x10\n\x08lforce_y\x18\x05 \x01(\x01\x12\x10\n\x08lforce_z\x18\x06 \x01(\x01\"|\n\x14ItemMassForceRequest\x12\x31\n\toperation\x18\x01 \x01(\x0e\x32\x1e.protos.ItemMassForceOperation\x12(\n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32\x15.protos.ItemMassForceH\x00\x88\x01\x01\x42\x07\n\x05_data\"\x9c\x02\n\x15ItemMassForceResponse\x12\x31\n\toperation\x18\x01 \x01(\x0e\x32\x1e.protos.ItemMassForceOperation\x12=\n\x06status\x18\x02 \x01(\x0e\x32-.protos.ItemMassForceResponse.OperationStatus\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12/\n\x10item_mass_forces\x18\x04 \x03(\x0b\x32\x15.protos.ItemMassForce\"K\n\x0fOperationStatus\x12\x0b\n\x07SUCCESS\x10\x00\x12\t\n\x05\x45RROR\x10\x01\x12\x0b\n\x07TIMEOUT\x10\x02\x12\x13\n\x0fINVALID_REQUEST\x10\x03**\n\x16ItemMassForceOperation\x12\x07\n\x03GET\x10\x00\x12\x07\n\x03SET\x10\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.hand_wrench_srv_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ITEMMASSFORCEOPERATION._serialized_start=584
  _ITEMMASSFORCEOPERATION._serialized_end=626
  _ITEMMASSFORCE._serialized_start=41
  _ITEMMASSFORCE._serialized_end=169
  _ITEMMASSFORCEREQUEST._serialized_start=171
  _ITEMMASSFORCEREQUEST._serialized_end=295
  _ITEMMASSFORCERESPONSE._serialized_start=298
  _ITEMMASSFORCERESPONSE._serialized_end=582
  _ITEMMASSFORCERESPONSE_OPERATIONSTATUS._serialized_start=507
  _ITEMMASSFORCERESPONSE_OPERATIONSTATUS._serialized_end=582
# @@protoc_insertion_point(module_scope)
